(define canvas (js-create-element "canvas"))
(js-set-canvas-width! canvas 300)
(js-set-canvas-height! canvas 300)
(js-append-child! (js-document-body) canvas)

(define ctx (js-canvas-get-context canvas "2d" (js-undefined)))

(js-set-canvas2d-fill-style! ctx "gold")
(js-set-canvas2d-stroke-style! ctx "black")
(js-set-canvas2d-line-width! ctx 2.)

(define (draw-star ctx cx cy spikes outerR innerR)
  (define step (/ pi spikes))
  (define rot (/ pi 2))
  (js-canvas2d-begin-path ctx)
  (js-canvas2d-move-to ctx cx (- cy outerR))
  (for ([i (in-range spikes)])
    (define x1 (+ cx (* (cos rot) outerR)))
    (define y1 (+ cy (* (sin rot) outerR)))
    (js-canvas2d-line-to ctx x1 y1)
    (set! rot (+ rot step))
    (define x2 (+ cx (* (cos rot) innerR)))
    (define y2 (+ cy (* (sin rot) innerR)))
    (js-canvas2d-line-to ctx x2 y2)
    (set! rot (+ rot step)))
  (js-canvas2d-close-path ctx)
  (js-canvas2d-fill ctx (js-undefined) "nonzero")
  (js-canvas2d-stroke ctx (js-undefined)))

(draw-star ctx 150. 150. 5 100. 40.)
