;;;
;;; dom.ffi
;;;

;; Focused tests for the Window, Document, and Element wrapper libraries.
;;
;; Build:
;;   racket -l errortrace -t ../webracket.rkt -- --ffi ../ffi/standard.ffi --ffi ../ffi/dom.ffi -r test-dom-window-document.rkt

(include-lib window)
(include-lib performance)
(include-lib document)
(include-lib element)
(include-lib domrect)

(define (check-equal got want label)
  (unless (equal? got want)
    (error 'check-equal (format "~a: got ~s want ~s" label got want))))

(define (check-true got label)
  (unless got
    (error 'check-true label)))

(define (check-false got label)
  (when got
    (error 'check-false label)))

(define (expect-contract-error thunk)
  (with-handlers ([exn:fail:contract? (lambda (_e) #t)])
    (thunk)
    #f))

(define (install!)
  (js-eval
   "window.name = 'dom-suite';
    window.confirm = function (message) { window.lastConfirm = message; return 1; };
    window.open = function (url, target, features, replace) {
      window.lastOpen = [url, target, features, replace];
      return { kind: 'popup', url, target, features, replace };
    };
    window.scrollTo = function (x, y, options) {
      window.lastScrollTo = [x, y, options];
    };
    window.setTimeout = function (callback, delay) {
      window.lastTimeout = [callback, delay];
      callback();
      return 17;
    };
    window.__domTest = window.__domTest || {};
    document.body.innerHTML = '';
    const host = document.createElement('div');
    host.id = 'dom-host';
    host.setAttribute('data-state', 'ready');
    const leaf = document.createElement('span');
    leaf.className = 'leaf';
    leaf.textContent = 'leaf';
    host.appendChild(leaf);
    document.body.appendChild(host);
    const shadowHost = document.createElement('section');
    shadowHost.id = 'shadow-host';
    shadowHost.attachShadow({mode: 'open'});
    document.body.appendChild(shadowHost);
    window.__domTest.host = host;
    window.__domTest.leaf = leaf;
    window.__domTest.shadowHost = shadowHost;
    performance.clearMarks('webracket-performance-start');
    performance.clearMarks('webracket-performance-end');
    performance.clearMeasures('webracket-performance-span');"))

(define (dom-test-fixture name)
  (js-ref (js-var "__domTest") name))

(list
 (list "Window wrappers"
       (let ()
         (install!)
         (define timeout-fired 0)
         (define win (Window))
         (define doc-info (window-document))
         (define loc-info (window-location))
         (check-true (window? win) "window wrapper")
         (check-true (external? (window-raw win)) "window wrapper raw")
         (check-true (window? (window-self)) "window self wrapper")
         (check-true (window-document-info? doc-info) "window document wrapper")
         (check-true (external? (window-document-info-raw doc-info))
                     "window document wrapper raw")
         (check-true (window-location-info? loc-info) "window location wrapper")
         (check-true (external? (window-location-info-raw loc-info))
                     "window location wrapper raw")
         (check-equal (window-name) "dom-suite" "window name")
         (window-set-name! 'web-bracket)
         (check-equal (window-name) "web-bracket" "window set name")
         (check-true (window-confirm 'proceed?) "window confirm")
         (check-equal (js-ref (js-var "window") "lastConfirm") "proceed?" "window confirm arg")
         (define opened (window-open "https://example.invalid" 'tab 'noopener #f))
         (check-true (window? opened) "window open result")
         (check-true (external? (window-raw opened)) "window open payload raw")
         (check-equal (js-ref (window-raw opened) "kind") "popup" "window open payload")
         (define scroll-options (make-window-scroll-options #f #f 'smooth))
         (window-scroll-to 11 22 scroll-options)
         (define scroll-record (js-ref (js-var "window") "lastScrollTo"))
         (check-equal (js-ref (vector-ref scroll-record 0) "top") 22 "window scroll top")
         (check-equal (js-ref (vector-ref scroll-record 0) "left") 11 "window scroll left")
         (check-equal (js-ref (vector-ref scroll-record 0) "behavior") "smooth" "window scroll behavior")
         (check-equal (window-set-timeout/delay (procedure->external (lambda () (set! timeout-fired (add1 timeout-fired))))
                                                10.0)
                      17
                      "window timeout handle")
         (check-equal timeout-fired 1 "window timeout callback")
         (check-equal (vector-ref (js-ref (js-var "window") "lastTimeout") 1) 10 "window timeout recorded")
         (check-true (void? (window-scroll-to 0 240)) "window scroll default")
         (check-true (expect-contract-error (lambda () (window-set-name! 1))) "window name validation")
         (check-true (expect-contract-error (lambda () (window-open 1))) "window open validation")
         (check-true (expect-contract-error (lambda () (window-confirm 1))) "window confirm validation")
         #t))
 (list "Performance wrappers"
       (let ()
         (install!)
         (check-true (real? (performance-now)) "performance now")
         (check-true (real? (performance-time-origin)) "performance time origin")
         (check-true (exact-nonnegative-integer? (performance-interaction-count))
                     "performance interaction count")
         (define event-counts (performance-event-counts))
         (check-true (or (not event-counts)
                         (performance-event-count-map? event-counts))
                     "performance event counts")
         (when event-counts
         (check-true (external? (performance-event-count-map-raw event-counts))
                       "performance event count raw")
          (check-true (exact-nonnegative-integer? (performance-event-count-map-size event-counts))
                       "performance event count size")
           (check-true (iterator? (performance-event-count-map-entries event-counts))
                       "performance event count entries")
           (check-true (iterator? (performance-event-count-map-keys event-counts))
                       "performance event count keys")
           (check-true (iterator? (performance-event-count-map-values event-counts))
                       "performance event count values")
           (check-true (vector? (iterator->vector (performance-event-count-map-entries event-counts)))
                       "performance event count entries vector")
           (check-true (vector? (iterator->vector (performance-event-count-map-keys event-counts)))
                       "performance event count keys vector")
           (check-true (vector? (iterator->vector (performance-event-count-map-values event-counts)))
                       "performance event count values vector")
           (check-true (boolean? (performance-event-count-map-has? event-counts 'click))
                       "performance event count has")
           (check-true (or (not (performance-event-count-map-get event-counts 'click))
                           (exact-nonnegative-integer? (performance-event-count-map-get event-counts 'click)))
                       "performance event count get")
           (check-true (void? (performance-event-count-map-for-each
                               event-counts
                               (lambda (count event-type map)
                                 (void count event-type map))))
                       "performance event count for-each")
           (check-true (external? (iterator-raw (performance-event-count-map-entries event-counts)))
                       "performance event count entries raw"))
         (define memory-info (performance-memory))
         (check-true (or (not memory-info)
                         (performance-memory-info? memory-info))
                     "performance memory")
         (when memory-info
           (check-true (exact-nonnegative-integer? (performance-memory-info-js-heap-size-limit memory-info))
                       "performance memory js heap size limit")
           (check-true (exact-nonnegative-integer? (performance-memory-info-total-js-heap-size memory-info))
                       "performance memory total js heap size")
           (check-true (exact-nonnegative-integer? (performance-memory-info-used-js-heap-size memory-info))
                       "performance memory used js heap size"))
         (performance-clear-marks 'webracket-performance-start)
         (performance-clear-marks 'webracket-performance-end)
         (performance-clear-measures 'webracket-performance-span)
         (performance-clear-resource-timings)
         (check-true (void? (performance-clear-marks #f))
                     "performance clear marks default")
         (check-true (void? (performance-clear-measures #f))
                     "performance clear measures default")
         (performance-mark 'webracket-performance-start)
         (performance-mark 'webracket-performance-end)
         (performance-measure 'webracket-performance-span
                              'webracket-performance-start
                              'webracket-performance-end)
         (define marks
           (performance-get-entries-by-name 'webracket-performance-start))
         (define measures
           (performance-get-entries-by-name 'webracket-performance-span 'measure))
         (define mark-entries
           (performance-get-entries-by-type 'mark))
         (define performance-json
           (performance-to-json))
         (check-true (>= (js-ref marks "length") 1) "performance marks by name")
         (check-true (>= (js-ref measures "length") 1) "performance measures by name")
         (check-true (>= (js-ref mark-entries "length") 1) "performance entries by type")
         (check-true (or (not performance-json)
                         (external? performance-json))
                     "performance to-json")
         (check-true (procedure? performance-measure-user-agent-specific-memory)
                     "performance memory estimator available")
         (performance-set-resource-timing-buffer-size 256)
         (check-true (expect-contract-error (lambda () (performance-clear-marks 1)))
                     "performance clear marks validation")
         (check-true (expect-contract-error (lambda () (performance-clear-measures 1)))
                     "performance clear measures validation")
         (check-true (expect-contract-error (lambda () (performance-get-entries-by-name 1)))
                     "performance get entries by name validation")
         (check-true (expect-contract-error (lambda () (performance-get-entries-by-type 1)))
                     "performance get entries by type validation")
         (check-true (expect-contract-error (lambda () (performance-event-count-map-size 1)))
                     "performance event count map size validation")
         (check-true (expect-contract-error (lambda () (performance-event-count-map-entries 1)))
                     "performance event count map entries validation")
         (check-true (expect-contract-error (lambda () (performance-event-count-map-keys 1)))
                     "performance event count map keys validation")
         (check-true (expect-contract-error (lambda () (performance-event-count-map-values 1)))
                     "performance event count map values validation")
         (check-true (expect-contract-error (lambda () (performance-event-count-map-get 1 "click")))
                     "performance event count map get validation")
         (check-true (expect-contract-error (lambda () (performance-event-count-map-get event-counts 1)))
                     "performance event count map get type validation")
         (check-true (expect-contract-error (lambda () (performance-event-count-map-has? 1 "click")))
                     "performance event count map has validation")
         (check-true (expect-contract-error (lambda () (performance-event-count-map-has? event-counts 1)))
                     "performance event count map has type validation")
         (check-true (expect-contract-error (lambda () (performance-event-count-map-for-each 1 void)))
                     "performance event count map for-each validation")
         (check-true (expect-contract-error (lambda () (performance-event-count-map-for-each event-counts 1)))
                     "performance event count map for-each proc validation")
         (check-true (expect-contract-error (lambda () (performance-memory-info-js-heap-size-limit 1)))
                     "performance memory info heap size validation")
         (check-true (expect-contract-error (lambda () (performance-memory-info-total-js-heap-size 1)))
                     "performance memory info total validation")
         (check-true (expect-contract-error (lambda () (performance-memory-info-used-js-heap-size 1)))
                     "performance memory info used validation")
         (check-true (expect-contract-error (lambda () (performance-mark 1)))
                     "performance mark validation")
         (check-true (expect-contract-error (lambda () (performance-measure 1)))
                     "performance measure validation")
         (check-true (expect-contract-error (lambda () (performance-set-resource-timing-buffer-size -1)))
                     "performance buffer size validation")
         #t))
(list "Document and element wrappers"
      (let ()
         (install!)
         (define doc (Document))
         (define body (document-body))
         (define host (document-create-element 'div))
         (define leaf (document-create-text-node 'leaf))
         (define child (document-create-element 'span))
         (define probe (document-create-element 'article))
         (define class-box (document-create-element 'div))
         (check-true (document? doc) "document wrapper")
         (check-true (external? (document-raw doc)) "document wrapper raw")
         (check-true (element? body) "document body wrapper")
         (check-true (element? host) "document create-element wrapper")
         (check-true (element? child) "document child wrapper")
         (check-true (text? leaf) "document create-text-node wrapper")
         (check-true (external? (text-raw leaf)) "document create-text-node raw")
         (element-set-id! child 'dom-child)
         (check-equal (element-id (dom-test-fixture "host")) "dom-host" "element id")
         (element-set-id! host 'dom-host-2)
         (check-equal (element-id host) "dom-host-2" "element set id")
         (element-set-class-name! host 'sprout)
         (check-equal (element-class-name host) "sprout" "element set class name")
         (define class-list (element-class-list class-box))
         (check-true (or (not class-list) (dom-token-list? class-list))
                     "element class list wrapper")
         (when class-list
           (check-true (string? (dom-token-list-value class-list))
                       "element class list value")
           (check-true (exact-nonnegative-integer? (dom-token-list-length class-list))
                       "element class list length")
           (dom-token-list-add! class-list 'alpha)
           (check-true (dom-token-list-contains? class-list 'alpha)
                       "element class list contains after add")
           (check-equal (dom-token-list-item class-list 0) "alpha"
                        "element class list item")
           (check-true (dom-token-list-toggle! class-list 'alpha)
                       "element class list toggle")
           (check-false (dom-token-list-contains? class-list 'alpha)
                        "element class list removed by toggle")
           (check-true (dom-token-list-toggle! class-list 'alpha (lambda () #f))
                       "element class list toggle forced false"))
         (define shadow-host (dom-test-fixture "shadowHost"))
         (check-true (or (not shadow-host) (external? shadow-host))
                     "element shadow host fixture")
         (define shadow-root (element-shadow-root shadow-host))
         (check-true (or (not shadow-root) (shadow-root? shadow-root))
                     "element shadow root wrapper")
         (when shadow-root
           (check-true (element? (shadow-root-host shadow-root))
                       "shadow root host wrapper")
           (check-equal (shadow-root-mode shadow-root) "open"
                        "shadow root mode")
           (check-false (shadow-root-delegates-focus? shadow-root)
                        "shadow root delegates focus"))
         (define shadow-probe (document-create-element 'div))
         (define attached-shadow
           (element-attach-shadow! shadow-probe
                                   (js-object (vector (vector "mode" "open")))))
         (check-true (shadow-root? attached-shadow)
                     "attach shadow wrapper")
         (check-true (element? (shadow-root-host attached-shadow))
                     "attach shadow host wrapper")
         (append-child! host leaf)
         (append-child! host child)
         (append-child! body host)
         (define rect (element-get-bounding-client-rect host))
         (check-true (dom-rect? rect) "element bounding rect wrapper")
         (check-true (real? (dom-rect-left rect)) "element bounding rect left")
         (check-true (real? (dom-rect-top rect)) "element bounding rect top")
         (element-set-attribute! host 'data-kind 'notice)
         (check-equal (element-get-attribute host 'data-kind) "notice" "element attribute symbol")
         (check-equal (element-get-attribute (dom-test-fixture "host") 'data-state) "ready" "element attribute")
         (check-true (element-has-attribute? (dom-test-fixture "host") 'data-state)
                     "element has attribute")
         (check-true (element-has-attributes? (dom-test-fixture "host"))
                     "element has attributes")
         (check-false (element-has-attribute? (dom-test-fixture "host") 'missing-attribute)
                      "element missing attribute")
         (define attr-names (element-get-attribute-names (dom-test-fixture "host")))
         (check-true (vector? attr-names) "element attribute names vector")
         (check-true (member "data-state" (vector->list attr-names))
                     "element attribute names include data-state")
         (check-true (element-matches? (dom-test-fixture "host") 'div)
                     "element matches selector")
         (check-true (element? (element-closest (dom-test-fixture "leaf") 'div))
                     "element closest wrapper")
         (check-true (element? (element-query-selector host 'span))
                     "element query selector wrapper")
         (element-remove-attribute! host 'data-kind)
         (check-false (element-has-attribute? host 'data-kind)
                      "element remove attribute")
         (check-true (element? (document-get-element-by-id 'dom-host-2)) "document lookup wrapper")
         (check-true (element? (document-query-selector 'span)) "document query selector wrapper")
         (define span-list (document-query-selector-all "#dom-child"))
         (check-true (node-list? span-list) "document query selector all node list")
         (check-equal (node-list-length span-list) 1 "document query selector all")
         (check-true (element? (node-list-item span-list 0)) "document query selector all item")
         (define element-span-list (element-query-selector-all host 'span))
         (check-true (node-list? element-span-list) "element query selector all node list")
         (check-equal (node-list-length element-span-list) 1 "element query selector all")
         (check-true (element? (node-list-item element-span-list 0)) "element query selector all item")
         (define host-rects (element-get-client-rects host))
         (check-true (vector? host-rects) "element client rects vector")
         (check-true (dom-rect? (vector-ref host-rects 0)) "element client rects item")
         (define point-list (document-elements-from-point (dom-rect-left rect) (dom-rect-top rect)))
         (check-true (vector? point-list) "document elements from point vector")
         (check-true (element? (vector-ref point-list 0)) "document elements from point item")
         (check-equal (element-child-element-count host) 1 "element child element count")
         (define host-children (element-children host))
         (check-true (html-collection? host-children) "element children html collection")
         (check-equal (html-collection-length host-children) 1 "element children count")
         (check-true (element? (html-collection-item host-children 0)) "element children item")
         (check-true (element? (html-collection-named-item host-children 'dom-child))
                     "element children named item")
         (check-true (element? (element-first-element-child host)) "element first child")
         (check-true (element? (element-last-element-child host)) "element last child")
         (check-equal (element-tag-name host) "DIV" "element tag name")
         (check-equal (element-local-name host) "div" "element local name")
         (check-true (or (not (element-namespace-uri host))
                         (string? (element-namespace-uri host)))
                     "element namespace uri")
         (check-true (or (not (element-prefix host))
                         (string? (element-prefix host)))
                     "element prefix")
         (check-true (element-is-connected? host) "element connected")
         (check-equal (element-inner-html probe) "" "element inner html default")
         (element-set-inner-html! probe "<span>ok</span>")
         (check-equal (element-inner-html probe) "<span>ok</span>" "element inner html set")
         (check-equal (element-text-content probe) "ok" "element text content")
         (element-set-text-content! probe 'done)
         (check-equal (element-text-content probe) "done" "element text content set")
         (check-equal (element-outer-html probe) "<article>done</article>" "element outer html")
         (element-append! class-box "hello")
         (element-prepend! class-box 'start)
         (check-equal (element-text-content class-box) "starthello" "element append/prepend")
         (element-insert-adjacent-html! class-box 'beforeend "<b>tail</b>")
         (element-insert-adjacent-text! class-box 'beforeend '!)
         (check-equal (element-text-content class-box) "starthello!tail" "element adjacent html/text")
         (check-true (element? (element-insert-adjacent-element! class-box 'beforeend child))
                     "element adjacent element")
         (define class-descendants (element-get-elements-by-class-name host 'sprout))
         (check-true (html-collection? class-descendants)
                     "element class-name descendants collection")
         (check-equal (html-collection-length class-descendants) 1
                      "element class-name descendants count")
         (check-true (element? (html-collection-item class-descendants 0))
                     "element class-name descendants item")
         (define tag-descendants (element-get-elements-by-tag-name host 'span))
         (check-true (html-collection? tag-descendants)
                     "element tag-name descendants collection")
         (check-equal (html-collection-length tag-descendants) 1
                      "element tag-name descendants count")
         (check-true (element? (html-collection-item tag-descendants 0))
                     "element tag-name descendants item")
         (check-true (exact-nonnegative-integer? (element-scroll-width host))
                     "element scroll width")
         (check-true (exact-nonnegative-integer? (element-scroll-height host))
                     "element scroll height")
         (check-true (exact-nonnegative-integer? (element-client-width host))
                     "element client width")
         (check-true (exact-nonnegative-integer? (element-client-height host))
                     "element client height")
         (check-true (exact-nonnegative-integer? (element-offset-width host))
                     "element offset width")
         (check-true (exact-nonnegative-integer? (element-offset-height host))
                     "element offset height")
         (define style-map (element-computed-style-map host))
         (check-true (or (not style-map) (computed-style-map? style-map))
                     "element computed style map wrapper")
         (define anim
           (element-animate host
                            (js-array/extern
                             (vector (js-object (vector (vector "opacity" "0")))
                                     (js-object (vector (vector "opacity" "1")))))
                            (js-object (vector (vector "duration" 1)))))
         (check-true (animation? anim) "element animation wrapper")
         (define animations (element-get-animations host))
         (check-true (vector? animations) "element animations vector")
         (when (positive? (vector-length animations))
           (check-true (animation? (vector-ref animations 0))
                       "element animations item"))
         (check-false (element-has-pointer-capture? host 1)
                      "element pointer capture default")
         (define attr-node
           (document-create-attribute 'data-state))
         (check-true (attr? attr-node)
                     "document attribute wrapper")
         (define comment-node
           (document-create-comment 'hello))
         (check-true (node? comment-node)
                     "document comment wrapper")
         (check-true (node? (document-create-cdata-section 'hello))
                     "document cdata wrapper")
         (check-true (node? (document-create-document-fragment))
                     "document fragment wrapper")
         (check-true (node? (document-create-processing-instruction 'xml 'version=1))
                     "document processing instruction wrapper")
         (check-true (node? (document-adopt-node comment-node))
                     "document adopt node wrapper")
         (check-true (attr? (element-get-attribute-node host 'data-state))
                     "element attribute node wrapper")
         (check-true (attr? (element-set-attribute-node! host attr-node))
                     "element set attribute node wrapper")
         (define ns-attr-node
           (document-create-attribute-ns 'http://example.invalid/ns 'data-temp))
         (check-true (attr? ns-attr-node)
                     "document namespaced attribute wrapper")
         (define ns-replaced
           (element-set-attribute-node-ns! host ns-attr-node))
         (check-true (or (not ns-replaced) (attr? ns-replaced))
                     "element set attribute node ns wrapper")
         (check-true (attr? (element-get-attribute-node-ns host 'http://example.invalid/ns 'data-temp))
                     "element namespaced attribute node wrapper")
         (element-set-attribute-ns! host 'http://example.invalid/ns 'data-temp 'ns-value)
         (check-equal (element-get-attribute-ns host 'http://example.invalid/ns 'data-temp)
                      "ns-value"
                      "element get attribute ns")
         (check-true (attr? (element-remove-attribute-node! host attr-node))
                     "element remove attribute node")
         (element-set-scroll-top! host 10.0)
         (element-set-scroll-left! host 12.0)
         (check-equal (element-scroll-top host) 10 "element scroll top")
         (check-equal (element-scroll-left host) 12 "element scroll left")
         (check-true (void? (element-set-pointer-capture! host 1))
                     "element set pointer capture")
         (check-true (void? (element-release-pointer-capture! host 1))
                     "element release pointer capture")
         (check-true (expect-contract-error (lambda () (element-has-pointer-capture? host 'x)))
                     "element pointer capture validation")
         (check-true (expect-contract-error (lambda () (element-set-pointer-capture! host 'x)))
                     "element set pointer capture validation")
         (check-true (expect-contract-error (lambda () (element-release-pointer-capture! host 'x)))
                     "element release pointer capture validation")
         (check-true (element-toggle-attribute! host 'data-flag) "element toggle on")
         (check-false (element-toggle-attribute! host (lambda () #f)) "element toggle off")
         (element-replace-children! host (document-create-text-node 'updated))
         (check-equal (js-ref host "textContent") "updated" "element replace-children")
         (check-true (expect-contract-error (lambda () (document-create-element 1))) "document create-element validation")
         (check-true (document? (document-open)) "document open wrapper")
         (check-true (expect-contract-error (lambda () (element-set-attribute! host 1 "value"))) "element set-attribute validation")
         #t)))
