#lang racket/base

;; Primitive database.
;; Names were extracted from the phase-0 value bindings in the `webracket` namespace.
;; Arities come from `priminfo.rkt`, with fallback to reflected `procedure-arity`.
;; Properties are currently conservative.
;; Many entries still use `(ordered)` until they have been audited.
;; The letrec pass derives its motion class from these properties.
;;
;; Property meanings:
;;
;;   `pure`
;;   A `pure` primitive does not allocate and does not have effects that matter
;;   for letrec lowering.  Calls to a primitive that is only `pure` are the
;;   easiest ones to move or classify as simple.  The letrec classifier uses
;;   `pure` to recognize primitive applications that may be treated as simple
;;   pure RHSs.
;;
;;   `restricted`
;;   A `restricted` primitive may still be effect-free in the ordinary sense,
;;   but it must not be moved freely by letrec lowering.  Typical examples are
;;   selectors like `car` or `vector-ref`, which can fail if moved ahead of a
;;   needed check or initialization.  The letrec classifier therefore treats
;;   `restricted` as a veto on free reordering: a primitive that is both `pure`
;;   and `restricted` is not considered a freely movable simple pure RHS.
;;
;;   `allocates`
;;   An `allocates` primitive creates fresh data, like `cons`, `box`, or
;;   `vector`.  These primitives are still simple enough for special letrec
;;   handling, but they are kept separate from `pure` primitives because
;;   allocation can matter for ordering and optimization.  The letrec
;;   classifier uses `allocates` to recognize simple allocating RHSs, provided
;;   the primitive is not also marked `restricted`.
;;
;;   `ordered`
;;   `ordered` is the conservative fallback for primitives that have not yet
;;   been audited into the more precise categories above.  In practice it means
;;   “do not treat this primitive application as a freely movable simple case”
;;   during letrec lowering.  If a primitive is only `ordered`, the compiler
;;   should leave it on the general sequential path instead of trying to fold
;;   it into the simple pure or simple allocating cases.
;;
;;   `foldable`
;;   A `foldable` primitive is safe to evaluate at compile time when all
;;   arguments are compile-time constants and the primitive returns a single
;;   value. This property is intended for early local simplification and is
;;   separate from motion-oriented properties like `pure` or `restricted`.

(provide primitive-db
         define-primitive
         (struct-out primitive-info))

(struct primitive-info (name arity properties) #:transparent)

(define primitive-db '())

(define-syntax-rule (define-primitive name arity properties)
  (set! primitive-db
        (cons (primitive-info 'name 'arity 'properties)
              primitive-db)))

(define-primitive *                                         at-least-0          (pure foldable))
(define-primitive +                                         at-least-0          (pure foldable))
(define-primitive -                                         at-least-1          (pure foldable))
(define-primitive ->fl                                      1                   (pure))
(define-primitive /                                         at-least-1          (pure foldable))
(define-primitive <                                         at-least-1          (pure foldable))
(define-primitive <=                                        at-least-1          (pure foldable))
(define-primitive =                                         at-least-1          (pure foldable))
(define-primitive >                                         at-least-1          (pure foldable))
(define-primitive >=                                        at-least-1          (pure foldable))
(define-primitive abs                                       1                   (pure))
(define-primitive absolute-path?                            1                   (pure))
(define-primitive acos                                      1                   (pure))
(define-primitive acosh                                     1                   (pure))
(define-primitive add-between                               2                   (ordered))
(define-primitive add1                                      1                   (pure))
(define-primitive andmap                                    at-least-2          (ordered))
(define-primitive append                                    at-least-0          (ordered))
(define-primitive append*                                   at-least-1          (ordered))
(define-primitive append-map                                at-least-2          (ordered))
(define-primitive apply                                     at-least-1          (ordered))
(define-primitive argmax                                    2                   (pure))
(define-primitive argmin                                    2                   (pure))
(define-primitive arithmetic-shift                          2                   (pure))
(define-primitive arity-at-least-value                      1                   (pure))
(define-primitive arity-at-least?                           1                   (pure))
(define-primitive asin                                      1                   (pure))
(define-primitive asinh                                     1                   (pure))
(define-primitive assf                                      2                   (pure restricted))
(define-primitive assoc                                     [2 3]               (pure restricted))
(define-primitive assq                                      2                   (pure restricted))
(define-primitive assv                                      2                   (pure restricted))
(define-primitive assw                                      2                   (pure restricted))
(define-primitive atan                                      [1 2]               (pure))
(define-primitive atanh                                     1                   (pure))
(define-primitive bitwise-and                               at-least-0          (pure))
(define-primitive bitwise-bit-field                         3                   (pure))
(define-primitive bitwise-bit-set?                          2                   (pure))
(define-primitive bitwise-first-bit-set                     1                   (pure))
(define-primitive bitwise-ior                               at-least-0          (pure))
(define-primitive bitwise-not                               1                   (pure))
(define-primitive bitwise-xor                               at-least-0          (pure))
(define-primitive boolean=?                                 2                   (pure foldable))
(define-primitive boolean?                                  1                   (pure foldable))
(define-primitive box                                       1                   (allocates))
(define-primitive box-immutable                             1                   (allocates))
(define-primitive box?                                      1                   (pure foldable))
(define-primitive build-list                                2                   (ordered))
(define-primitive build-path                                at-least-1          (ordered))
(define-primitive build-path/convention-type                at-least-2          (ordered))
(define-primitive build-string                              2                   (ordered))
(define-primitive build-vector                              2                   (ordered))
(define-primitive byte-ready?                               [0 1]               (ordered))
(define-primitive byte?                                     1                   (pure))
(define-primitive bytes                                     at-least-0          (allocates))
(define-primitive bytes->immutable-bytes                    1                   (allocates))
(define-primitive bytes->list                               1                   (allocates))
(define-primitive bytes->path                               [1 2]               (allocates))
(define-primitive bytes->path-element                       [1 2 3]             (allocates))
(define-primitive bytes->string/latin-1                     [1 2 3 4]           (allocates))
(define-primitive bytes->string/utf-8                       [1 2 3 4]           (allocates))
(define-primitive bytes-append                              at-least-0          (allocates))
(define-primitive bytes-append*                             at-least-1          (allocates))
(define-primitive bytes-copy                                1                   (allocates))
(define-primitive bytes-copy!                               [3 4 5]             (ordered))
(define-primitive bytes-fill!                               2                   (ordered))
(define-primitive bytes-join                                2                   (ordered))
(define-primitive bytes-length                              1                   (pure))
(define-primitive bytes-ref                                 2                   (pure restricted))
(define-primitive bytes-set!                                3                   (ordered))
(define-primitive bytes-utf-8-length                        [1 2 3 4]           (ordered))
(define-primitive bytes<?                                   at-least-1          (pure))
(define-primitive bytes=?                                   at-least-1          (pure))
(define-primitive bytes>?                                   at-least-1          (pure))
(define-primitive bytes?                                    1                   (pure))
(define-primitive caaaar                                    1                   (ordered))
(define-primitive caaadr                                    1                   (ordered))
(define-primitive caaar                                     1                   (ordered))
(define-primitive caadar                                    1                   (ordered))
(define-primitive caaddr                                    1                   (ordered))
(define-primitive caadr                                     1                   (ordered))
(define-primitive caar                                      1                   (ordered))
(define-primitive cadaar                                    1                   (ordered))
(define-primitive cadadr                                    1                   (ordered))
(define-primitive cadar                                     1                   (ordered))
(define-primitive caddar                                    1                   (ordered))
(define-primitive cadddr                                    1                   (ordered))
(define-primitive caddr                                     1                   (ordered))
(define-primitive cadr                                      1                   (ordered))
(define-primitive call-with-exception-handler               2                   (ordered))
(define-primitive call-with-input-file                      [2 3]               (ordered))
(define-primitive call-with-input-file*                     [2 3]               (ordered))
(define-primitive call-with-output-file                     [2 3 4]             (ordered))
(define-primitive call-with-output-file*                    [2 3 4]             (ordered))
(define-primitive call-with-output-string                   1                   (ordered))
(define-primitive call-with-values                          2                   (ordered))
(define-primitive car                                       1                   (pure restricted))
(define-primitive cartesian-product                         at-least-0          (ordered))
(define-primitive catch                                     3                   (ordered))
(define-primitive catch*                                    3                   (ordered))
(define-primitive cdaaar                                    1                   (ordered))
(define-primitive cdaadr                                    1                   (ordered))
(define-primitive cdaar                                     1                   (ordered))
(define-primitive cdadar                                    1                   (ordered))
(define-primitive cdaddr                                    1                   (ordered))
(define-primitive cdadr                                     1                   (ordered))
(define-primitive cdar                                      1                   (ordered))
(define-primitive cddaar                                    1                   (ordered))
(define-primitive cddadr                                    1                   (ordered))
(define-primitive cddar                                     1                   (ordered))
(define-primitive cdddar                                    1                   (ordered))
(define-primitive cddddr                                    1                   (ordered))
(define-primitive cdddr                                     1                   (ordered))
(define-primitive cddr                                      1                   (ordered))
(define-primitive cdr                                       1                   (pure restricted))
(define-primitive ceiling                                   1                   (ordered))
(define-primitive char->integer                             1                   (pure))
(define-primitive char-alphabetic?                          1                   (pure))
(define-primitive char-blank?                               1                   (pure))
(define-primitive char-ci<=?                                at-least-1          (pure))
(define-primitive char-ci<?                                 at-least-1          (pure))
(define-primitive char-ci=?                                 at-least-1          (pure))
(define-primitive char-ci>=?                                at-least-1          (pure))
(define-primitive char-ci>?                                 at-least-1          (pure))
(define-primitive char-downcase                             1                   (pure))
(define-primitive char-extended-pictographic?               1                   (pure))
(define-primitive char-foldcase                             1                   (pure))
(define-primitive char-general-category                     1                   (pure))
(define-primitive char-grapheme-break-property              1                   (pure))
(define-primitive char-grapheme-step                        2                   (pure))
(define-primitive char-graphic?                             1                   (pure))
(define-primitive char-iso-control?                         1                   (pure))
(define-primitive char-lower-case?                          1                   (pure))
(define-primitive char-numeric?                             1                   (pure))
(define-primitive char-punctuation?                         1                   (pure))
(define-primitive char-ready?                               [0 1]               (ordered))
(define-primitive char-symbolic?                            1                   (pure))
(define-primitive char-title-case?                          1                   (pure))
(define-primitive char-titlecase                            1                   (pure))
(define-primitive char-upcase                               1                   (pure))
(define-primitive char-upper-case?                          1                   (pure))
(define-primitive char-utf-8-length                         1                   (pure))
(define-primitive char-whitespace?                          1                   (pure))
(define-primitive char<=?                                   at-least-1          (pure))
(define-primitive char<?                                    at-least-1          (pure))
(define-primitive char=?                                    at-least-1          (pure))
(define-primitive char>=?                                   at-least-1          (pure))
(define-primitive char>?                                    at-least-1          (pure))
(define-primitive char?                                     1                   (pure foldable))
(define-primitive check-list                                1                   (ordered))
(define-primitive check-mlist                               1                   (ordered))
(define-primitive check-naturals                            1                   (ordered))
(define-primitive check-range                               3                   (ordered))
(define-primitive check-range-generic                       4                   (ordered))
(define-primitive check-string                              1                   (ordered))
(define-primitive check-vector                              1                   (ordered))
(define-primitive cleanse-path                              1                   (ordered))
(define-primitive close-input-port                          1                   (ordered))
(define-primitive close-output-port                         1                   (ordered))
(define-primitive complete-path?                            1                   (pure))
(define-primitive compose                                   at-least-0          (ordered))
(define-primitive compose1                                  at-least-0          (ordered))
(define-primitive cons                                      2                   (allocates))
(define-primitive cons?                                     1                   (pure))
(define-primitive copy-directory/files                      [2 3 4]             (ordered))
(define-primitive copy-file                                 [2 3]               (ordered))
(define-primitive correlated->datum                         1                   (pure))
(define-primitive correlated-column                         1                   (pure))
(define-primitive correlated-e                              1                   (pure))
(define-primitive correlated-line                           1                   (pure))
(define-primitive correlated-position                       1                   (pure))
(define-primitive correlated-property                       [2 3]               (ordered))
(define-primitive correlated-property-symbol-keys           1                   (pure))
(define-primitive correlated-source                         1                   (pure))
(define-primitive correlated-span                           1                   (pure))
(define-primitive correlated?                               1                   (pure))
(define-primitive cos                                       1                   (pure))
(define-primitive cosh                                      1                   (pure))
(define-primitive count                                     at-least-2          (ordered))
(define-primitive current-continuation-marks                [0 1]               (ordered))
(define-primitive current-directory                         [0 1]               (ordered))
(define-primitive current-directory-for-user                [0 1]               (ordered))
(define-primitive current-drive                             0                   (ordered))
(define-primitive current-error-port                        [0 1]               (ordered))
(define-primitive current-input-port                        [0 1]               (ordered))
(define-primitive current-inspector                         [0 1]               (ordered))
(define-primitive current-output-port                       [0 1]               (ordered))
(define-primitive custom-write-accessor                     [1 2]               (ordered))
(define-primitive custom-write?                             1                   (pure))
(define-primitive datum->correlated                         [1 2 3]             (ordered))
(define-primitive datum->syntax                             [2 3 4 5]           (ordered))
(define-primitive degrees->radians                          1                   (ordered))
(define-primitive delete-directory                          1                   (ordered))
(define-primitive delete-directory/files                    [1 2]               (ordered))
(define-primitive delete-file                               1                   (ordered))
(define-primitive directory-exists?                         1                   (pure))
(define-primitive directory-list                            [0 1 2]             (ordered))
(define-primitive display-lines-to-file                     [2 3 4 5]           (ordered))
(define-primitive display-to-file                           [2 3 4]             (ordered))
(define-primitive double-flonum?                            1                   (pure))
(define-primitive drop                                      2                   (ordered))
(define-primitive drop-common-prefix                        [2 3]               (ordered))
(define-primitive drop-right                                2                   (ordered))
(define-primitive dropf                                     2                   (ordered))
(define-primitive dropf-right                               2                   (ordered))
(define-primitive eighth                                    1                   (pure restricted))
(define-primitive eleventh                                  1                   (pure restricted))
(define-primitive empty?                                    1                   (pure))
(define-primitive eof-object?                               1                   (pure))
(define-primitive eq-hash-code                              1                   (ordered))
(define-primitive eq?                                       2                   (pure foldable))
(define-primitive equal-always?                             2                   (pure))
(define-primitive equal-hash-code                           1                   (ordered))
(define-primitive equal?                                    2                   (pure foldable))
(define-primitive eqv-hash-code                             1                   (ordered))
(define-primitive eqv?                                      2                   (pure foldable))
(define-primitive even?                                     1                   (pure))
(define-primitive exact->inexact                            1                   (pure))
(define-primitive exact-ceiling                             1                   (ordered))
(define-primitive exact-floor                               1                   (ordered))
(define-primitive exact-integer?                            1                   (pure))
(define-primitive exact-nonnegative-integer?                1                   (pure))
(define-primitive exact-positive-integer?                   1                   (pure))
(define-primitive exact-round                               1                   (ordered))
(define-primitive exact-truncate                            1                   (ordered))
(define-primitive exact?                                    1                   (pure foldable))
(define-primitive exn-continuation-marks                    1                   (pure))
(define-primitive exn-message                               1                   (pure))
(define-primitive exn:fail:contract:arity?                  1                   (pure))
(define-primitive exn:fail:contract:divide-by-zero?         1                   (pure))
(define-primitive exn:fail:contract:non-fixnum-result?      1                   (pure))
(define-primitive exn:fail:contract:variable-id             1                   (ordered))
(define-primitive exn:fail:contract:variable?               1                   (pure))
(define-primitive exn:fail:contract?                        1                   (pure))
(define-primitive exn:fail:filesystem?                      1                   (pure))
(define-primitive exn:fail:read-srclocs                     1                   (ordered))
(define-primitive exn:fail:read:eof?                        1                   (pure))
(define-primitive exn:fail:read:non-char?                   1                   (pure))
(define-primitive exn:fail:read?                            1                   (pure))
(define-primitive exn:fail:syntax-exprs                     1                   (ordered))
(define-primitive exn:fail:syntax:missing-module-path       1                   (ordered))
(define-primitive exn:fail:syntax:missing-module?           1                   (pure))
(define-primitive exn:fail:syntax:unbound?                  1                   (pure))
(define-primitive exn:fail:syntax?                          1                   (pure))
(define-primitive exn:fail?                                 1                   (pure))
(define-primitive exn?                                      1                   (pure))
(define-primitive exp                                       1                   (pure))
(define-primitive explode-path                              1                   (ordered))
(define-primitive expt                                      2                   (pure))
(define-primitive external-number->flonum                   1                   (ordered))
(define-primitive external-string->string                   1                   (ordered))
(define-primitive external?                                 1                   (pure))
(define-primitive false?                                    1                   (pure))
(define-primitive fasl->s-exp                               1                   (ordered))
(define-primitive fifteenth                                 1                   (pure restricted))
(define-primitive fifth                                     1                   (pure restricted))
(define-primitive file->bytes                               [1 2]               (ordered))
(define-primitive file->bytes-lines                         [1 2 3]             (ordered))
(define-primitive file->lines                               [1 2 3]             (ordered))
(define-primitive file->string                              [1 2]               (ordered))
(define-primitive file-exists?                              1                   (pure))
(define-primitive file-name-from-path                       1                   (ordered))
(define-primitive file-or-directory-identity                [1 2]               (ordered))
(define-primitive file-or-directory-modify-seconds          [1 2]               (ordered))
(define-primitive file-or-directory-permissions             [1 2]               (ordered))
(define-primitive file-or-directory-stat                    [1 2]               (ordered))
(define-primitive file-or-directory-type                    [1 2]               (pure))
(define-primitive file-size                                 1                   (pure))
(define-primitive filename-extension                        1                   (ordered))
(define-primitive filesystem-root-list                      0                   (ordered))
(define-primitive filter                                    2                   (ordered))
(define-primitive filter-map                                at-least-2          (ordered))
(define-primitive filter-not                                2                   (ordered))
(define-primitive find-relative-path                        [2 3 4 5]           (ordered))
(define-primitive find-system-path                          1                   (ordered))
(define-primitive findf                                     2                   (pure))
(define-primitive first                                     1                   (pure restricted))
(define-primitive fixnum-for-every-system?                  1                   (pure))
(define-primitive fixnum?                                   1                   (pure foldable))
(define-primitive fl*                                       at-least-0          (pure))
(define-primitive fl+                                       at-least-0          (pure))
(define-primitive fl-                                       at-least-1          (pure))
(define-primitive fl->exact-integer                         1                   (pure))
(define-primitive fl->fx                                    1                   (pure))
(define-primitive fl/                                       at-least-1          (pure))
(define-primitive fl<                                       at-least-1          (pure))
(define-primitive fl<=                                      at-least-1          (pure))
(define-primitive fl=                                       at-least-1          (pure))
(define-primitive fl>                                       at-least-1          (pure))
(define-primitive fl>=                                      at-least-1          (pure))
(define-primitive flabs                                     1                   (pure))
(define-primitive flacos                                    1                   (pure))
(define-primitive flacosh                                   1                   (pure))
(define-primitive flasin                                    1                   (pure))
(define-primitive flasinh                                   1                   (pure))
(define-primitive flatan                                    1                   (pure))
(define-primitive flatanh                                   1                   (pure))
(define-primitive flatten                                   1                   (ordered))
(define-primitive flbit-field                               3                   (pure))
(define-primitive flceiling                                 1                   (pure))
(define-primitive flcos                                     1                   (pure))
(define-primitive flcosh                                    1                   (pure))
(define-primitive flexp                                     1                   (pure))
(define-primitive flexpt                                    2                   (pure))
(define-primitive flfloor                                   1                   (pure))
(define-primitive fllog                                     1                   (pure))
(define-primitive flmax                                     at-least-1          (pure))
(define-primitive flmin                                     at-least-1          (pure))
(define-primitive floating-point-bytes->real                [1 2 3 4]           (ordered))
(define-primitive flonum?                                   1                   (pure foldable))
(define-primitive floor                                     1                   (ordered))
(define-primitive flrandom                                  [0 1]               (ordered))
(define-primitive flround                                   1                   (pure))
(define-primitive flsin                                     1                   (pure))
(define-primitive flsingle                                  1                   (pure))
(define-primitive flsinh                                    1                   (pure))
(define-primitive flsqrt                                    1                   (pure))
(define-primitive fltan                                     1                   (pure))
(define-primitive fltanh                                    1                   (pure))
(define-primitive fltruncate                                1                   (pure))
(define-primitive flush-output                              [0 1]               (ordered))
(define-primitive foldl                                     at-least-3          (ordered))
(define-primitive foldr                                     at-least-3          (ordered))
(define-primitive for-each                                  at-least-2          (ordered))
(define-primitive fourteenth                                1                   (pure restricted))
(define-primitive fourth                                    1                   (pure restricted))
(define-primitive fx*                                       at-least-0          (pure))
(define-primitive fx*/wraparound                            2                   (pure))
(define-primitive fx+                                       at-least-0          (pure))
(define-primitive fx+/wraparound                            2                   (pure))
(define-primitive fx-                                       at-least-1          (pure))
(define-primitive fx-/wraparound                            2                   (pure))
(define-primitive fx->fl                                    1                   (pure))
(define-primitive fx<                                       at-least-1          (pure))
(define-primitive fx<=                                      at-least-1          (pure))
(define-primitive fx=                                       at-least-1          (pure))
(define-primitive fx>                                       at-least-1          (pure))
(define-primitive fx>=                                      at-least-1          (pure))
(define-primitive fxabs                                     1                   (pure))
(define-primitive fxand                                     at-least-0          (pure))
(define-primitive fxior                                     at-least-0          (pure))
(define-primitive fxlshift                                  2                   (pure))
(define-primitive fxlshift/wraparound                       2                   (pure))
(define-primitive fxmax                                     at-least-1          (pure))
(define-primitive fxmin                                     at-least-1          (pure))
(define-primitive fxmodulo                                  2                   (pure))
(define-primitive fxnot                                     1                   (pure))
(define-primitive fxpopcount                                1                   (pure))
(define-primitive fxpopcount16                              1                   (pure))
(define-primitive fxpopcount32                              1                   (pure))
(define-primitive fxquotient                                2                   (pure))
(define-primitive fxremainder                               2                   (pure))
(define-primitive fxrshift                                  2                   (pure))
(define-primitive fxrshift/logical                          2                   (pure))
(define-primitive fxxor                                     at-least-0          (pure))
(define-primitive fxzero?                                   1                   (pure))
(define-primitive gcd                                       at-least-0          (ordered))
(define-primitive gensym                                    [0 1]               (ordered))
(define-primitive get-output-bytes                          [1 2 3 4]           (ordered))
(define-primitive get-output-string                         1                   (ordered))
(define-primitive group-by                                  [2 3]               (ordered))
(define-primitive hash->linklet-bundle                      1                   (ordered))
(define-primitive hash->linklet-directory                   1                   (ordered))
(define-primitive hash->list                                [1 2]               (ordered))
(define-primitive hash-clear!                               1                   (ordered))
(define-primitive hash-count                                1                   (pure))
(define-primitive hash-empty?                               1                   (pure))
(define-primitive hash-eq?                                  1                   (pure))
(define-primitive hash-equal-always?                        1                   (pure))
(define-primitive hash-equal?                               1                   (pure))
(define-primitive hash-eqv?                                 1                   (pure))
(define-primitive hash-filter                               2                   (ordered))
(define-primitive hash-filter-keys                          2                   (ordered))
(define-primitive hash-filter-values                        2                   (ordered))
(define-primitive hash-for-each                             [2 3]               (ordered))
(define-primitive hash-has-key?                             2                   (pure))
(define-primitive hash-keys                                 [1 2]               (ordered))
(define-primitive hash-map                                  [2 3]               (ordered))
(define-primitive hash-map/copy                             [2 3]               (ordered))
(define-primitive hash-ref                                  [2 3]               (ordered))
(define-primitive hash-ref!                                 3                   (ordered))
(define-primitive hash-remove!                              2                   (ordered))
(define-primitive hash-set!                                 3                   (ordered))
(define-primitive hash-update!                              [3 4]               (ordered))
(define-primitive hash-values                               [1 2]               (ordered))
(define-primitive hash?                                     1                   (pure))
(define-primitive identifier?                               1                   (pure))
(define-primitive immutable-box?                            1                   (pure))
(define-primitive immutable-bytes?                          1                   (pure))
(define-primitive immutable-hash?                           1                   (pure))
(define-primitive immutable-string?                         1                   (pure))
(define-primitive immutable-vector?                         1                   (pure))
(define-primitive immutable?                                1                   (pure))
(define-primitive inclusive-range-proc                      [2 3]               (ordered))
(define-primitive index-of                                  [2 3]               (ordered))
(define-primitive index-where                               2                   (ordered))
(define-primitive indexes-of                                [2 3]               (ordered))
(define-primitive indexes-where                             2                   (ordered))
(define-primitive inexact->exact                            1                   (pure))
(define-primitive inexact-real?                             1                   (pure))
(define-primitive inexact?                                  1                   (pure foldable))
(define-primitive infinite?                                 1                   (pure))
(define-primitive input-port?                               1                   (pure))
(define-primitive instance-data                             1                   (ordered))
(define-primitive instance-name                             1                   (ordered))
(define-primitive instance-set-variable-value!              [3 4]               (ordered))
(define-primitive instance-unset-variable!                  2                   (ordered))
(define-primitive instance-variable-box                     3                   (ordered))
(define-primitive instance-variable-names                   1                   (ordered))
(define-primitive instance-variable-value                   [2 3]               (ordered))
(define-primitive instance?                                 1                   (pure))
(define-primitive instantiate-linklet                       [2 3 4]             (ordered))
(define-primitive integer->char                             1                   (pure))
(define-primitive integer-length                            1                   (pure))
(define-primitive integer-sqrt                              1                   (pure))
(define-primitive integer-sqrt/remainder                    1                   (pure))
(define-primitive integer?                                  1                   (pure foldable))
(define-primitive js-log                                    1                   (ordered))
(define-primitive keyword->immutable-string                 1                   (allocates))
(define-primitive keyword->string                           1                   (allocates))
(define-primitive keyword<?                                 at-least-1          (pure))
(define-primitive keyword?                                  1                   (pure))
(define-primitive last                                      1                   (pure restricted))
(define-primitive last-pair                                 1                   (pure restricted))
(define-primitive lcm                                       at-least-0          (ordered))
(define-primitive length                                    1                   (pure restricted))
(define-primitive link-exists?                              1                   (pure))
(define-primitive linklet-body-reserved-symbol?             1                   (pure))
(define-primitive linklet-bundle->hash                      1                   (ordered))
(define-primitive linklet-bundle?                           1                   (pure))
(define-primitive linklet-directory->hash                   1                   (ordered))
(define-primitive linklet-directory?                        1                   (pure))
(define-primitive linklet-export-variables                  1                   (ordered))
(define-primitive linklet-import-variables                  1                   (ordered))
(define-primitive linklet-name                              1                   (ordered))
(define-primitive linklet?                                  1                   (pure))
(define-primitive list                                      at-least-0          (allocates))
(define-primitive list*                                     at-least-1          (allocates))
(define-primitive list->bytes                               1                   (allocates))
(define-primitive list->string                              1                   (allocates))
(define-primitive list->vector                              1                   (allocates))
(define-primitive list-prefix?                              [2 3]               (pure restricted))
(define-primitive list-ref                                  2                   (pure restricted))
(define-primitive list-set                                  3                   (ordered))
(define-primitive list-tail                                 2                   (pure restricted))
(define-primitive list-update                               3                   (ordered))
(define-primitive list?                                     1                   (pure))
(define-primitive log                                       [1 2]               (pure))
(define-primitive make-arity-at-least                       1                   (allocates))
(define-primitive make-bytes                                [1 2]               (allocates))
(define-primitive make-compiled-linklet                     4                   (ordered))
(define-primitive make-directory                            [1 2]               (ordered))
(define-primitive make-directory*                           1                   (ordered))
(define-primitive make-empty-hash                           0                   (allocates))
(define-primitive make-empty-hashalw                        0                   (allocates))
(define-primitive make-empty-hasheq                         0                   (allocates))
(define-primitive make-empty-hasheqv                        0                   (allocates))
(define-primitive make-empty-namespace                      0                   (ordered))
(define-primitive make-exn                                  2                   (allocates))
(define-primitive make-exn:fail                             2                   (allocates))
(define-primitive make-exn:fail:contract                    2                   (allocates))
(define-primitive make-exn:fail:contract:arity              2                   (allocates))
(define-primitive make-exn:fail:contract:divide-by-zero     2                   (allocates))
(define-primitive make-exn:fail:contract:non-fixnum-result  2                   (allocates))
(define-primitive make-exn:fail:contract:variable           3                   (allocates))
(define-primitive make-exn:fail:filesystem                  2                   (allocates))
(define-primitive make-exn:fail:read                        3                   (allocates))
(define-primitive make-exn:fail:read:eof                    3                   (allocates))
(define-primitive make-exn:fail:read:non-char               3                   (allocates))
(define-primitive make-exn:fail:syntax                      3                   (allocates))
(define-primitive make-exn:fail:syntax:missing-module       4                   (allocates))
(define-primitive make-exn:fail:syntax:unbound              3                   (allocates))
(define-primitive make-hash                                 [0 1]               (allocates))
(define-primitive make-hashalw                              [0 1]               (allocates))
(define-primitive make-hasheq                               [0 1]               (allocates))
(define-primitive make-hasheqv                              [0 1]               (allocates))
(define-primitive make-input-port                           [4 5 6 7 8 9 10]    (ordered))
(define-primitive make-instance                             at-least-1          (ordered))
(define-primitive make-list                                 2                   (allocates))
(define-primitive make-parent-directory*                    1                   (ordered))
(define-primitive make-srcloc                               5                   (allocates))
(define-primitive make-string                               [1 2]               (allocates))
(define-primitive make-struct-field-accessor                [2 3 4 5]           (ordered))
(define-primitive make-struct-field-mutator                 [2 3 4 5]           (ordered))
(define-primitive make-struct-type                          [4 5 6 7 8 9 10 11] (ordered))
(define-primitive make-struct-type-property                 [1 2 3 4 5 6 7]     (ordered))
(define-primitive make-temporary-directory                  [0 1 2]             (ordered))
(define-primitive make-temporary-directory*                 [2 3]               (ordered))
(define-primitive make-temporary-file                       [0 1 2 3]           (ordered))
(define-primitive make-temporary-file*                      [2 3 4]             (ordered))
(define-primitive make-vector                               [1 2]               (allocates))
(define-primitive make-void                                 0                   (pure))
(define-primitive make-weak-hash                            [0 1]               (allocates))
(define-primitive make-weak-hashalw                         [0 1]               (allocates))
(define-primitive make-weak-hasheq                          [0 1]               (allocates))
(define-primitive make-weak-hasheqv                         [0 1]               (allocates))
(define-primitive map                                       at-least-2          (ordered))
(define-primitive match:error                               3                   (ordered))
(define-primitive max                                       at-least-1          (pure))
(define-primitive mcar                                      1                   (ordered))
(define-primitive mcdr                                      1                   (ordered))
(define-primitive mcons                                     2                   (allocates))
(define-primitive member                                    [2 3]               (pure restricted))
(define-primitive memf                                      2                   (pure restricted))
(define-primitive memq                                      2                   (pure restricted))
(define-primitive memv                                      2                   (pure restricted))
(define-primitive memw                                      2                   (pure restricted))
(define-primitive min                                       at-least-1          (pure))
(define-primitive modulo                                    2                   (ordered))
(define-primitive most-negative-fixnum                      0                   (ordered))
(define-primitive most-positive-fixnum                      0                   (ordered))
(define-primitive mpair?                                    1                   (pure))
(define-primitive mutable-box?                              1                   (pure))
(define-primitive mutable-bytes?                            1                   (pure))
(define-primitive mutable-hash-iterate-first                1                   (ordered))
(define-primitive mutable-hash-iterate-key                  [2 3]               (ordered))
(define-primitive mutable-hash-iterate-key+value            [2 3]               (ordered))
(define-primitive mutable-hash-iterate-next                 2                   (ordered))
(define-primitive mutable-hash-iterate-pair                 [2 3]               (ordered))
(define-primitive mutable-hash-iterate-value                [2 3]               (ordered))
(define-primitive mutable-hash?                             1                   (pure))
(define-primitive mutable-string?                           1                   (pure))
(define-primitive mutable-vector?                           1                   (pure))
(define-primitive namespace-set-variable-value!             [2 3 4 5]           (ordered))
(define-primitive namespace-undefine-variable!              [1 2]               (ordered))
(define-primitive namespace-variable-value-simple           2                   (ordered))
(define-primitive namespace?                                1                   (pure))
(define-primitive nan?                                      1                   (pure))
(define-primitive natural?                                  1                   (pure))
(define-primitive negative-integer?                         1                   (pure))
(define-primitive negative?                                 1                   (pure foldable))
(define-primitive newline                                   [0 1]               (ordered))
(define-primitive ninth                                     1                   (pure restricted))
(define-primitive nonnegative-integer?                      1                   (pure))
(define-primitive nonpositive-integer?                      1                   (pure))
(define-primitive normal-case-path                          1                   (ordered))
(define-primitive normalize-path                            [1 2]               (ordered))
(define-primitive not                                       1                   (pure foldable))
(define-primitive null?                                     1                   (pure foldable))
(define-primitive number->string                            [1 2]               (pure))
(define-primitive number?                                   1                   (pure foldable))
(define-primitive object-name                               1                   (pure))
(define-primitive odd?                                      1                   (pure))
(define-primitive open-input-bytes                          [1 2]               (ordered))
(define-primitive open-input-file                           [1 2 3]             (ordered))
(define-primitive open-input-string                         [1 2]               (ordered))
(define-primitive open-output-bytes                         [0 1]               (ordered))
(define-primitive open-output-file                          [1 2 3]             (ordered))
(define-primitive open-output-string                        [0 1]               (ordered))
(define-primitive order-of-magnitude                        1                   (ordered))
(define-primitive ormap                                     at-least-2          (ordered))
(define-primitive output-port?                              1                   (pure))
(define-primitive pair?                                     1                   (pure foldable))
(define-primitive partition                                 2                   (ordered))
(define-primitive path->bytes                               1                   (allocates))
(define-primitive path->complete-path                       [1 2]               (ordered))
(define-primitive path->directory-path                      1                   (ordered))
(define-primitive path->string                              1                   (allocates))
(define-primitive path-add-extension                        [2 3]               (ordered))
(define-primitive path-add-suffix                           2                   (ordered))
(define-primitive path-convention-type                      1                   (ordered))
(define-primitive path-element->bytes                       1                   (allocates))
(define-primitive path-element->string                      1                   (allocates))
(define-primitive path-element?                             1                   (pure))
(define-primitive path-for-some-system?                     1                   (pure))
(define-primitive path-get-extension                        1                   (ordered))
(define-primitive path-has-extension?                       2                   (pure))
(define-primitive path-only                                 1                   (ordered))
(define-primitive path-replace-extension                    2                   (ordered))
(define-primitive path-replace-suffix                       2                   (ordered))
(define-primitive path-string?                              1                   (pure))
(define-primitive path<?                                    at-least-1          (pure))
(define-primitive path?                                     1                   (pure))
(define-primitive peek-byte                                 [0 1 2]             (ordered))
(define-primitive peek-bytes                                [2 3]               (ordered))
(define-primitive peek-bytes!                               [2 3 4 5]           (ordered))
(define-primitive peek-bytes-avail!                         [2 3 4 5 6]         (ordered))
(define-primitive peek-bytes-avail!*                        [2 3 4 5 6]         (ordered))
(define-primitive peek-char                                 [0 1 2]             (ordered))
(define-primitive peek-string                               [2 3]               (ordered))
(define-primitive peek-string!                              [2 3 4 5]           (ordered))
(define-primitive permutations                              1                   (ordered))
(define-primitive port-closed?                              1                   (pure))
(define-primitive port-count-lines!                         1                   (ordered))
(define-primitive port-counts-lines?                        1                   (pure))
(define-primitive port-next-location                        1                   (ordered))
(define-primitive port?                                     1                   (pure))
(define-primitive positive-integer?                         1                   (pure))
(define-primitive positive?                                 1                   (pure foldable))
(define-primitive primitive-closure?                        1                   (pure))
(define-primitive primitive-result-arity                    1                   (pure))
(define-primitive primitive?                                1                   (pure))
(define-primitive procedure->external                       1                   (ordered))
(define-primitive procedure-arity                           1                   (pure))
(define-primitive procedure-arity-includes?                 [2 3]               (pure))
(define-primitive procedure-arity-mask                      1                   (ordered))
(define-primitive procedure-reduce-arity                    [2 3 4]             (ordered))
(define-primitive procedure-rename                          [2 3]               (ordered))
(define-primitive procedure?                                1                   (pure foldable))
(define-primitive progress-evt?                             [1 2]               (pure))
(define-primitive quotient                                  2                   (ordered))
(define-primitive quotient/remainder                        2                   (ordered))
(define-primitive radians->degrees                          1                   (ordered))
(define-primitive raise                                     [1 2]               (ordered))
(define-primitive raise-read-eof-error                      [6 7]               (ordered))
(define-primitive raise-read-error                          [6 7]               (ordered))
(define-primitive random                                    [0 1 2]             (ordered))
(define-primitive range                                     [1 2 3]             (ordered))
(define-primitive range-proc                                [1 2 3]             (ordered))
(define-primitive read-byte                                 [0 1]               (ordered))
(define-primitive read-bytes                                [1 2]               (ordered))
(define-primitive read-bytes!                               [1 2 3 4]           (ordered))
(define-primitive read-bytes-avail!                         [1 2 3 4]           (ordered))
(define-primitive read-bytes-avail!*                        [1 2 3 4]           (ordered))
(define-primitive read-char                                 [0 1]               (ordered))
(define-primitive read-line                                 [0 1 2]             (ordered))
(define-primitive read-string                               [1 2]               (ordered))
(define-primitive read-string!                              [1 2 3 4]           (ordered))
(define-primitive real->double-flonum                       1                   (pure))
(define-primitive real->floating-point-bytes                [2 3 4 5]           (ordered))
(define-primitive real?                                     1                   (pure foldable))
(define-primitive relative-path?                            1                   (pure))
(define-primitive remainder                                 2                   (ordered))
(define-primitive remf                                      2                   (ordered))
(define-primitive remf*                                     2                   (ordered))
(define-primitive remove                                    [2 3]               (ordered))
(define-primitive remove*                                   [2 3]               (ordered))
(define-primitive remq                                      2                   (ordered))
(define-primitive remq*                                     2                   (ordered))
(define-primitive remv                                      2                   (ordered))
(define-primitive remv*                                     2                   (ordered))
(define-primitive remw                                      2                   (ordered))
(define-primitive remw*                                     2                   (ordered))
(define-primitive rename-file-or-directory                  [2 3]               (ordered))
(define-primitive reroot-path                               2                   (ordered))
(define-primitive reset-current-error-port!                 0                   (ordered))
(define-primitive reset-current-input-port!                 0                   (ordered))
(define-primitive reset-current-output-port!                0                   (ordered))
(define-primitive resolve-path                              1                   (ordered))
(define-primitive rest                                      1                   (pure restricted))
(define-primitive reverse                                   1                   (ordered))
(define-primitive round                                     1                   (ordered))
(define-primitive s-exp->fasl                               [1 2]               (ordered))
(define-primitive second                                    1                   (pure restricted))
(define-primitive set-box!                                  2                   (ordered))
(define-primitive set-mcar!                                 2                   (ordered))
(define-primitive set-mcdr!                                 2                   (ordered))
(define-primitive seventh                                   1                   (pure restricted))
(define-primitive sgn                                       1                   (ordered))
(define-primitive shrink-path-wrt                           2                   (ordered))
(define-primitive shuffle                                   1                   (ordered))
(define-primitive simple-form-path                          1                   (ordered))
(define-primitive simplify-path                             [1 2]               (ordered))
(define-primitive sin                                       1                   (pure))
(define-primitive single-flonum-available?                  0                   (pure))
(define-primitive single-flonum?                            1                   (pure))
(define-primitive sinh                                      1                   (pure))
(define-primitive sixth                                     1                   (pure restricted))
(define-primitive some-system-path->string                  1                   (ordered))
(define-primitive sort                                      2                   (ordered))
(define-primitive split-at                                  2                   (ordered))
(define-primitive split-at-right                            2                   (ordered))
(define-primitive split-common-prefix                       [2 3]               (ordered))
(define-primitive split-path                                1                   (ordered))
(define-primitive splitf-at                                 2                   (ordered))
(define-primitive splitf-at-right                           2                   (ordered))
(define-primitive sqr                                       1                   (pure))
(define-primitive sqrt                                      1                   (pure))
(define-primitive srcloc                                    5                   (ordered))
(define-primitive srcloc->string                            1                   (ordered))
(define-primitive srcloc-column                             1                   (pure))
(define-primitive srcloc-line                               1                   (pure))
(define-primitive srcloc-position                           1                   (pure))
(define-primitive srcloc-source                             1                   (pure))
(define-primitive srcloc-span                               1                   (pure))
(define-primitive srcloc?                                   1                   (pure))
(define-primitive string                                    at-least-0          (allocates))
(define-primitive string->bytes/utf-8                       [1 2 3 4]           (allocates))
(define-primitive string->immutable-string                  1                   (pure))
(define-primitive string->keyword                           1                   (allocates))
(define-primitive string->list                              1                   (allocates))
(define-primitive string->number                            [1 2 3 4 5]         (pure))
(define-primitive string->path                              1                   (allocates))
(define-primitive string->path-element                      [1 2]               (allocates))
(define-primitive string->some-system-path                  2                   (ordered))
(define-primitive string->symbol                            1                   (allocates))
(define-primitive string->uninterned-symbol                 1                   (allocates))
(define-primitive string-append                             at-least-0          (allocates))
(define-primitive string-append*                            at-least-1          (allocates))
(define-primitive string-append-immutable                   at-least-0          (allocates))
(define-primitive string-ci<=?                              at-least-1          (pure))
(define-primitive string-ci<?                               at-least-1          (pure))
(define-primitive string-ci=?                               at-least-1          (pure))
(define-primitive string-ci>=?                              at-least-1          (pure))
(define-primitive string-ci>?                               at-least-1          (pure))
(define-primitive string-contains?                          2                   (pure))
(define-primitive string-copy                               1                   (allocates))
(define-primitive string-copy!                              [3 4 5]             (ordered))
(define-primitive string-downcase                           1                   (ordered))
(define-primitive string-drop                               2                   (ordered))
(define-primitive string-drop-right                         2                   (ordered))
(define-primitive string-fill!                              2                   (ordered))
(define-primitive string-find                               2                   (ordered))
(define-primitive string-foldcase                           1                   (ordered))
(define-primitive string-join                               [1 2]               (ordered))
(define-primitive string-length                             1                   (pure))
(define-primitive string-port?                              1                   (pure))
(define-primitive string-prefix?                            2                   (pure))
(define-primitive string-ref                                2                   (pure restricted))
(define-primitive string-replace                            [3 4]               (ordered))
(define-primitive string-set!                               3                   (ordered))
(define-primitive string-split                              [1 2 3 4]           (ordered))
(define-primitive string-suffix?                            2                   (pure))
(define-primitive string-take                               2                   (ordered))
(define-primitive string-take-right                         2                   (ordered))
(define-primitive string-titlecase                          1                   (ordered))
(define-primitive string-trim                               [1 2 3 4 5]         (ordered))
(define-primitive string-trim-left                          2                   (ordered))
(define-primitive string-trim-right                         2                   (ordered))
(define-primitive string-upcase                             1                   (ordered))
(define-primitive string-utf-8-length                       [1 2 3]             (ordered))
(define-primitive string<=?                                 at-least-1          (pure foldable))
(define-primitive string<?                                  at-least-1          (pure foldable))
(define-primitive string=?                                  at-least-1          (pure foldable))
(define-primitive string>=?                                 at-least-1          (pure foldable))
(define-primitive string>?                                  at-least-1          (pure foldable))
(define-primitive string?                                   1                   (pure foldable))
(define-primitive struct->list                              [1 2]               (ordered))
(define-primitive struct->vector                            [1 2]               (ordered))
(define-primitive struct-accessor-procedure?                1                   (pure))
(define-primitive struct-constructor-procedure?             1                   (pure))
(define-primitive struct-mutator-procedure?                 1                   (pure))
(define-primitive struct-predicate-procedure?               1                   (pure))
(define-primitive struct-type-authentic?                    1                   (pure))
(define-primitive struct-type-property-accessor-procedure?  1                   (pure))
(define-primitive struct-type-property-predicate-procedure? [1 2]               (pure))
(define-primitive struct-type-property?                     1                   (pure))
(define-primitive struct-type?                              1                   (pure))
(define-primitive struct?                                   1                   (pure))
(define-primitive sub1                                      1                   (pure))
(define-primitive subbytes                                  [2 3]               (allocates))
(define-primitive substring                                 [2 3]               (allocates))
(define-primitive symbol->immutable-string                  1                   (allocates))
(define-primitive symbol->string                            1                   (allocates))
(define-primitive symbol-interned?                          1                   (pure))
(define-primitive symbol<?                                  at-least-1          (pure))
(define-primitive symbol=?                                  2                   (pure foldable))
(define-primitive symbol?                                   1                   (pure foldable))
(define-primitive syntax->datum                             1                   (ordered))
(define-primitive syntax->list                              1                   (ordered))
(define-primitive syntax-column                             1                   (pure))
(define-primitive syntax-e                                  1                   (pure))
(define-primitive syntax-line                               1                   (pure))
(define-primitive syntax-position                           1                   (pure))
(define-primitive syntax-source                             1                   (pure))
(define-primitive syntax-span                               1                   (pure))
(define-primitive syntax-srcloc                             1                   (ordered))
(define-primitive syntax-srclocs                            1                   (ordered))
(define-primitive syntax?                                   1                   (pure))
(define-primitive system-big-endian?                        0                   (pure))
(define-primitive system-path-convention-type               0                   (ordered))
(define-primitive take                                      2                   (ordered))
(define-primitive take-common-prefix                        [2 3]               (ordered))
(define-primitive take-right                                2                   (ordered))
(define-primitive takef                                     2                   (ordered))
(define-primitive takef-right                               2                   (ordered))
(define-primitive tan                                       1                   (pure))
(define-primitive tanh                                      1                   (pure))
(define-primitive tenth                                     1                   (pure restricted))
(define-primitive third                                     1                   (pure restricted))
(define-primitive thirteenth                                1                   (pure restricted))
(define-primitive truncate                                  1                   (ordered))
(define-primitive twelfth                                   1                   (pure restricted))
(define-primitive unbox                                     1                   (pure restricted))
(define-primitive unquoted-printing-string                  1                   (ordered))
(define-primitive unquoted-printing-string-value            1                   (ordered))
(define-primitive unquoted-printing-string?                 1                   (pure))
(define-primitive unsafe-bytes-length                       1                   (pure restricted))
(define-primitive unsafe-bytes-ref                          2                   (pure restricted))
(define-primitive unsafe-bytes-set!                         3                   (ordered))
(define-primitive unsafe-car                                1                   (pure restricted))
(define-primitive unsafe-cdr                                1                   (pure restricted))
(define-primitive unsafe-fl/                                at-least-1          (ordered))
(define-primitive unsafe-flabs                              1                   (ordered))
(define-primitive unsafe-flacos                             1                   (ordered))
(define-primitive unsafe-flacosh                            1                   (ordered))
(define-primitive unsafe-flasin                             1                   (ordered))
(define-primitive unsafe-flasinh                            1                   (ordered))
(define-primitive unsafe-flatan                             1                   (ordered))
(define-primitive unsafe-flatanh                            1                   (ordered))
(define-primitive unsafe-flceiling                          1                   (ordered))
(define-primitive unsafe-flcos                              1                   (ordered))
(define-primitive unsafe-flcosh                             1                   (ordered))
(define-primitive unsafe-flexp                              1                   (ordered))
(define-primitive unsafe-flexpt                             2                   (ordered))
(define-primitive unsafe-flfloor                            1                   (ordered))
(define-primitive unsafe-fllog                              1                   (ordered))
(define-primitive unsafe-flmax                              at-least-1          (ordered))
(define-primitive unsafe-flmin                              at-least-1          (ordered))
(define-primitive unsafe-flrandom                           [0 1]               (ordered))
(define-primitive unsafe-flround                            1                   (ordered))
(define-primitive unsafe-flsin                              1                   (ordered))
(define-primitive unsafe-flsingle                           1                   (ordered))
(define-primitive unsafe-flsinh                             1                   (ordered))
(define-primitive unsafe-flsqrt                             1                   (ordered))
(define-primitive unsafe-fltan                              1                   (ordered))
(define-primitive unsafe-fltanh                             1                   (ordered))
(define-primitive unsafe-fltruncate                         1                   (ordered))
(define-primitive unsafe-fx*                                at-least-0          (ordered))
(define-primitive unsafe-fx*/wraparound                     2                   (ordered))
(define-primitive unsafe-fx+                                at-least-0          (ordered))
(define-primitive unsafe-fx+/wraparound                     2                   (ordered))
(define-primitive unsafe-fx-                                at-least-1          (ordered))
(define-primitive unsafe-fx-/wraparound                     2                   (ordered))
(define-primitive unsafe-fx<                                at-least-1          (ordered))
(define-primitive unsafe-fx<=                               at-least-1          (ordered))
(define-primitive unsafe-fx=                                at-least-1          (ordered))
(define-primitive unsafe-fx>                                at-least-1          (ordered))
(define-primitive unsafe-fx>=                               at-least-1          (ordered))
(define-primitive unsafe-fxabs                              1                   (ordered))
(define-primitive unsafe-fxand                              at-least-0          (ordered))
(define-primitive unsafe-fxior                              at-least-0          (ordered))
(define-primitive unsafe-fxlshift                           2                   (ordered))
(define-primitive unsafe-fxlshift/wraparound                2                   (ordered))
(define-primitive unsafe-fxmax                              at-least-1          (ordered))
(define-primitive unsafe-fxmin                              at-least-1          (ordered))
(define-primitive unsafe-fxmodulo                           2                   (ordered))
(define-primitive unsafe-fxnot                              1                   (ordered))
(define-primitive unsafe-fxpopcount                         1                   (ordered))
(define-primitive unsafe-fxpopcount16                       1                   (ordered))
(define-primitive unsafe-fxpopcount32                       1                   (ordered))
(define-primitive unsafe-fxquotient                         2                   (pure))
(define-primitive unsafe-fxremainder                        2                   (ordered))
(define-primitive unsafe-fxrshift                           2                   (ordered))
(define-primitive unsafe-fxrshift/logical                   2                   (ordered))
(define-primitive unsafe-fxxor                              at-least-0          (ordered))
(define-primitive unsafe-string-length                      1                   (pure restricted))
(define-primitive unsafe-struct-ref                         2                   (ordered))
(define-primitive unsafe-struct-set!                        3                   (ordered))
(define-primitive unsafe-vector*-length                     1                   (ordered))
(define-primitive unsafe-vector*-ref                        2                   (ordered))
(define-primitive unsafe-vector*-set!                       3                   (ordered))
(define-primitive unsafe-vector-length                      1                   (pure))
(define-primitive unsafe-vector-ref                         2                   (pure restricted))
(define-primitive unsafe-vector-set!                        3                   (ordered))
(define-primitive values                                    at-least-0          (pure))
(define-primitive variable-reference-constant?              1                   (pure))
(define-primitive variable-reference-from-unsafe?           1                   (pure))
(define-primitive vector                                    at-least-0          (allocates))
(define-primitive vector->immutable-vector                  1                   (allocates))
(define-primitive vector->list                              1                   (allocates))
(define-primitive vector->values                            [1 2 3]             (ordered))
(define-primitive vector-append                             at-least-0          (allocates))
(define-primitive vector-argmax                             2                   (ordered))
(define-primitive vector-argmin                             2                   (ordered))
(define-primitive vector-copy                               [1 2 3]             (allocates))
(define-primitive vector-copy!                              [3 4 5]             (ordered))
(define-primitive vector-count                              at-least-2          (ordered))
(define-primitive vector-drop                               2                   (ordered))
(define-primitive vector-drop-right                         2                   (ordered))
(define-primitive vector-empty?                             1                   (pure))
(define-primitive vector-extend                             [2 3]               (ordered))
(define-primitive vector-fill!                              2                   (ordered))
(define-primitive vector-filter                             2                   (ordered))
(define-primitive vector-filter-not                         2                   (ordered))
(define-primitive vector-immutable                          at-least-0          (ordered))
(define-primitive vector-length                             1                   (pure))
(define-primitive vector-map                                at-least-2          (ordered))
(define-primitive vector-map!                               at-least-2          (ordered))
(define-primitive vector-member                             [2 3]               (ordered))
(define-primitive vector-memq                               2                   (ordered))
(define-primitive vector-memv                               2                   (ordered))
(define-primitive vector-ref                                2                   (pure restricted))
(define-primitive vector-set!                               3                   (ordered))
(define-primitive vector-set/copy                           3                   (ordered))
(define-primitive vector-sort                               [2 3 4]             (ordered))
(define-primitive vector-sort!                              [2 3 4]             (ordered))
(define-primitive vector-split-at                           2                   (ordered))
(define-primitive vector-split-at-right                     2                   (ordered))
(define-primitive vector-take                               2                   (ordered))
(define-primitive vector-take-right                         2                   (ordered))
(define-primitive vector?                                   1                   (pure foldable))
(define-primitive void                                      at-least-0          (ordered))
(define-primitive void?                                     1                   (ordered))
(define-primitive webracket-vfs-write-file                  2                   (ordered))
(define-primitive with-input-from-file                      [2 3]               (ordered))
(define-primitive with-output-to-file                       [2 3 4]             (ordered))
(define-primitive write-byte                                [1 2]               (ordered))
(define-primitive write-bytes                               [1 2 3 4]           (ordered))
(define-primitive write-char                                [1 2]               (ordered))
(define-primitive write-string                              [1 2 3 4]           (ordered))
(define-primitive xor                                       2                   (pure))
(define-primitive zero?                                     1                   (pure foldable))

(set! primitive-db (reverse primitive-db))
