// Generated by "assembler.rkt".
import fs from 'node:fs/promises';

const wasmBuffer = await fs.readFile("out.wasm");

var memory = new WebAssembly.Memory({initial:1024});

var output_string = [];

function read_u32(arr, i) {
  return ((arr[i] << 24) | (arr[i + 1] << 16) |
          (arr[i + 2] << 8)  | arr[i + 3]) >>> 0;
}

function fasl_to_js_value(arr, i = 0) {

  const tag = arr[i++];

  function u32() {
    const v = read_u32(arr, i);
    i += 4;
    return v;
  }

  function read_bytes() {
    const len = u32();
    const b = arr.slice(i, i + len);
    i += len;
    return b;
  }

  function read_string() {
    const b = read_bytes();
    return new TextDecoder().decode(b);
  }

  switch(tag) {
    case 0: {
      const raw = u32();
      // Sign-extend the 30-bit payload so negative fixnums decode correctly.
      return [(raw << 2) >> 2, i];
    }
    case 1:
      return [String.fromCodePoint(u32()), i];
    case 2:
      return [Symbol.for(read_string()), i];
    case 3:
      return [read_string(), i];
    case 4:
      return [read_bytes(), i];
    case 5:
      return [arr[i++] !== 0, i];
    case 6:
      return [null, i];
    case 7: {
      let car, cdr;
      [car, i] = fasl_to_js_value(arr, i);
      [cdr, i] = fasl_to_js_value(arr, i);
      return [{tag:'pair', car, cdr}, i];
    }
    case 8: {
      const n = u32();
      const vec = new Array(n);
      for(let j = 0; j < n; j++) {
        [vec[j], i] = fasl_to_js_value(arr, i);
      }
      return [vec, i];
    }
    case 9: {
      const hi = u32();
      const lo = u32();
      const dv = new DataView(new ArrayBuffer(8));
      dv.setUint32(0, hi);
      dv.setUint32(4, lo);
      return [dv.getFloat64(0), i];
    }
    case 10:
      return [undefined, i];
    case 11:
      return ['<eof>', i];
    default:
      throw new Error('bad FASL tag ' + tag);
  }
}

function js_value_to_fasl(v) {
  const out = [];
  const enc = new TextEncoder();

  // --- low-level writers (big-endian) ---
  function writeByte(b) {
    out.push(b & 0xFF);
  }
  function writeU32(u) {
    out.push((u >>> 24) & 0xFF, (u >>> 16) & 0xFF, (u >>> 8) & 0xFF, u & 0xFF);
  }
  function writeBytes(u8) {
    writeU32(u8.length >>> 0);
    for (let i = 0; i < u8.length; i++) out.push(u8[i] & 0xFF);
  }
  function writeString(s) {
    const u8 = enc.encode(s);
    writeBytes(u8);
  }
  function writeF64(x) {
    const dv = new DataView(new ArrayBuffer(8));
    // Big-endian
    dv.setFloat64(0, x, false);
    const hi = dv.getUint32(0, false);
    const lo = dv.getUint32(4, false);
    writeU32(hi);
    writeU32(lo);
  }

  // --- tagged writers ---
  function writeFixnum(n) {
    // 30-bit signed two's complement payload; range: [-2^29, 2^29-1]
    if (!Number.isInteger(n) || n < -(1 << 29) || n > ((1 << 29) - 1)) {
      throw new RangeError("fixnum out of 30-bit range");
    }
    writeByte(0);
    const raw30 = n & 0x3FFFFFFF; // 30-bit two's complement payload
    writeU32(raw30 >>> 0);
  }
  function writeFlonum(x) {
    writeByte(9);
    writeF64(x);
  }
  function writeCharacter(cp) {
    // cp = Unicode scalar value (number)
    writeByte(1);
    writeU32(cp >>> 0);
  }
  function writeSymbol(name) {
    writeByte(2);
    writeString(name);
  }
  function writeStringVal(s) {
    writeByte(3);
    writeString(s);
  }
  function writeBytesVal(u8) {
    writeByte(4);
    writeBytes(u8);
  }
  function writeBoolean(b) {
    writeByte(5);
    writeByte(b ? 1 : 0);
  }
  function writeNull() {
    writeByte(6);
  }
  function writeVoid() {
    writeByte(10);
  }
  function writeEof() {
    writeByte(11);
  }
  function writePair(car, cdr) {
    writeByte(7);
    writeAny(car);
    writeAny(cdr);
  }
  function writeVector(arr) {
    writeByte(8);
    writeU32(arr.length >>> 0);
    for (let i = 0; i < arr.length; i++) writeAny(arr[i]);
  }

  // --- main dispatcher (mirrors fasl_to_js_value mapping) ---
  function writeAny(x) {
    // Fast paths by JS type
    if (typeof x === "number") {
      if (Number.isInteger(x) && x >= -(1 << 29) && x <= ((1 << 29) - 1)) {
        writeFixnum(x);
      } else {
        writeFlonum(x);
      }
      return;
    }
    if (typeof x === "boolean") {
      writeBoolean(x);
      return;
    }
    if (x === null) {
      writeNull();
      return;
    }
    if (x === undefined) {
      writeVoid();
      return;
    }
    // EoF sentinel (match your decoder's '<eof>' convention)
    if (x === "<eof>" || (x && x.tag === "eof")) {
      writeEof();
      return;
    }
    // Character (two accepted forms)
    //   { tag: 'char', cp: <codepoint> }  or  { tag: 'char', ch: 'A' }
    if (x && x.tag === "char") {
      const cp = typeof x.cp === "number" ? x.cp
               : (typeof x.ch === "string" ? x.ch.codePointAt(0) : undefined);
      if (cp === undefined) throw new TypeError("bad char object");
      writeCharacter(cp >>> 0);
      return;
    }
    // Pair (your decoder uses {tag:'pair', car, cdr})
    if (x && x.tag === "pair") {
      writePair(x.car, x.cdr);
      return;
    }
    // Bytes: prefer Uint8Array
    if (x instanceof Uint8Array) {
      writeBytesVal(x);
      return;
    }
    // Accept raw byte arrays too
    if (Array.isArray(x) && x.every(n => Number.isInteger(n) && n >= 0 && n <= 255)) {
      writeBytesVal(Uint8Array.from(x));
      return;
    }
    // Vector: plain JS Array (distinct from bytes above)
    if (Array.isArray(x)) {
      writeVector(x);
      return;
    }
    // Symbol
    if (typeof x === "symbol") {
      const name = Symbol.keyFor(x) ?? x.description ?? "";
      writeSymbol(name);
      return;
    }
    // String
    if (typeof x === "string") {
      writeStringVal(x);
      return;
    }
    throw new TypeError("unsupported value for FASL encoding: " + String(x));
  }
  writeAny(v);
  return Uint8Array.from(out);
}

function testsuite(js_value_to_fasl, fasl_to_js_value, { log = true } = {}) {
  // --- helpers -------------------------------------------------------------
  function charToString(v) {
    if (typeof v === 'string' && v.length === 1) return v;
    if (v && typeof v === 'object' && v.tag === 'char' && typeof v.cp === 'number') {
      try { return String.fromCodePoint(v.cp); } catch { /* fall through */ }
    }
    return null;
  }

  function deepEq(a, b) {
    // Treat "char-wrappers" and 1-char strings as equal
    const ac = charToString(a), bc = charToString(b);
    if (ac !== null || bc !== null) return ac === bc;
    // numbers (handle NaN, -0)
    if (typeof a === 'number' || typeof b === 'number') return Object.is(a, b);
    // Uint8Array (bytes)
    if (a instanceof Uint8Array && b instanceof Uint8Array) {
      if (a.length !== b.length) return false;
      for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false;
      return true;
    }
    // Symbols (use registry key or description)
    if (typeof a === 'symbol' && typeof b === 'symbol') {
      const ka = Symbol.keyFor(a) ?? a.description ?? '';
      const kb = Symbol.keyFor(b) ?? b.description ?? '';
      return ka === kb;
    }
    // Pairs
    if (a && b && a.tag === 'pair' && b.tag === 'pair') {
      return deepEq(a.car, b.car) && deepEq(a.cdr, b.cdr);
    }
    // Arrays (vectors)
    if (Array.isArray(a) && Array.isArray(b)) {
      if (a.length !== b.length) return false;
      for (let i = 0; i < a.length; i++) if (!deepEq(a[i], b[i])) return false;
      return true;
    }
    // Strings, booleans, null, undefined, "<eof>"
    return a === b;
  }
  function roundtrip(v) {
    const bytes = js_value_to_fasl(v);
    const [v2] = fasl_to_js_value(bytes);
    const ok = deepEq(v2, v);
    if (!ok && log) {
      console.error('Roundtrip mismatch:', v, '->', v2, 'bytes=', bytes);
    }
    return ok;
  }
  function test(name, v) {
    const ok = roundtrip(v);
    results.push({ name, ok });
    if (log) console.log(`${ok ? '✓' : '✗'} ${name}`);
    if (ok) pass++; else fail++;
  }

  // --- run tests -----------------------------------------------------------
  const results = [];
  let pass = 0, fail = 0;

  // Fixnums (30-bit)
  test('fixnum 0', 0);
  test('fixnum 123', 123);
  test('fixnum -5', -5);
  // Flonums
  test('flonum 1.5', 1.5);
  test('flonum -0.0', -0.0);
  test('flonum NaN', NaN);
  test('flonum +Inf', Infinity);
  test('flonum -Inf', -Infinity);
  // Booleans / null / void / eof
  test('boolean true', true);
  test('boolean false', false);
  test('null', null);
  test('void/undefined', undefined);
  test('eof sentinel', '<eof>');
  // Characters (encode via wrapper; decoder yields 1-char string)
  test('char A', { tag: 'char', cp: 'A'.codePointAt(0) });
  test('char snowman', { tag: 'char', cp: '☃'.codePointAt(0) });
  // Symbols
  test('symbol foo', Symbol.for('foo'));
  // Bytes (Uint8Array)
  test('bytes', new Uint8Array([0, 1, 2, 255]));
  // Pairs
  test('pair (1 . null)', { tag: 'pair', car: 1, cdr: null });
  test('list (1 2)',
       { tag: 'pair', car: 1, cdr: { tag: 'pair', car: 2, cdr: null } });
  // Vectors (arrays)
  test('vector mixed',
       [ 1, 2.5, { tag: 'pair', car: 'x', cdr: null }, true ]);
  // Strings
  test('string ascii', 'hello');
  test('string utf8', 'héllø 🌍');

  return { pass, fail, total: pass + fail, results };
}

// Uncomment to run the testsuite for fasl.
// Currently the only failing test is the one for -0.0 which after the round trip becomes 0.0.
// This is not fixabable as long as we convert integers to fixnums.

// const summary = testsuite(js_value_to_fasl, fasl_to_js_value, { log: true });
// console.log(`\nPassed: ${summary.pass}/${summary.total}`);
// if (summary.fail) {
//   console.log('Failures:');
//    for (const r of summary.results.filter(r => !r.ok)) {
//    console.log('  -', r.name);
//  }
// }

// hasDOM gives us a way of determining whether the host is a browser or Node
const hasDOM = typeof document !== 'undefined' && typeof document.createTextNode === 'function';

function from_fasl(index) {
    return fasl_to_js_value(new Uint8Array(memory.buffer), index)[0]
}

var imports = {
    'env': {
        'memory': memory
    },
    'primitives': {
      'console_log': ((x)   => console.log(x)),
      'add':         ((x,y) => x+y),
      'js_output':   ((x)   => output_string.push(x)),
      'js_print_fasl': ((start, len) => {
        const bytes = new Uint8Array(memory.buffer).slice(start, start + len);
        const [v] = fasl_to_js_value(bytes);
        console.log(v);
      }),
      'char_upcase': ((cp) => {
        const s = String.fromCodePoint(cp).toUpperCase();
        const arr = Array.from(s);
        return (arr.length === 1) ? arr[0].codePointAt(0) : cp;
      }),
      'char_downcase': ((cp) => {
        const s = String.fromCodePoint(cp).toLowerCase();
        const arr = Array.from(s);
        return (arr.length === 1) ? arr[0].codePointAt(0) : cp;
      }),
      'char_titlecase': ((cp) => {
        const lower = String.fromCodePoint(cp).toLocaleLowerCase();
        const title = lower.charAt(0).toLocaleUpperCase() + lower.slice(1);
        const arr = Array.from(title);
        return (arr.length === 1) ? arr[0].codePointAt(0) : cp;
      }),
      'char_foldcase': ((cp) => {
        // Note: JavaScript doesn't have builtin unicode aware fold case (year 2025).
        //       For now, we will just use lowercase.
        const s = String.fromCodePoint(cp).toLowerCase();
        const arr = Array.from(s);
        return (arr.length === 1) ? arr[0].codePointAt(0) : cp;
      })
    },
    'standard': {
      'global-this':               (() => globalThis),
      'infinity':                  (() => Infinity),
      'nan':                       (() => NaN),
      'undefined':                 (() => undefined),
      'eval':                      ((code) => eval(from_fasl(code))),
      'is-finite':                 ((x) => isFinite(x) ? 1 : 0),
      'is-nan':                    ((x) => isNaN(x) ? 1 : 0),
      'parse-float':               ((s) => parseFloat(from_fasl(s))),
      'parse-int':                 ((s) => parseInt(from_fasl(s))),
      'decode-uri':                ((s) => decodeURI(from_fasl(s))),
      'decode-uri-component':      ((s) => decodeURIComponent(from_fasl(s))),
      'encode-uri':                ((s) => encodeURI(from_fasl(s))),
      'encode-uri-component':      ((s) => encodeURIComponent(from_fasl(s))),
      'escape':                    ((s) => escape(from_fasl(s))),
      'unescape':                  ((s) => unescape(from_fasl(s))),
      'object':                    (() => Object),
      'function':                  (() => Function),
      'boolean':                   (() => Boolean),
      'symbol':                    (() => Symbol),
      'error':                     (() => Error),
      'aggregate-error':           (() => (typeof AggregateError === 'undefined' ? undefined : AggregateError)),
      'eval-error':                (() => EvalError),
      'range-error':               (() => RangeError),
      'reference-error':           (() => ReferenceError),
      'suppressed-error':          (() => (typeof SuppressedError === 'undefined' ? undefined : SuppressedError)),
      'syntax-error':              (() => SyntaxError),
      'type-error':                (() => TypeError),
      'uri-error':                 (() => URIError),
      'internal-error':            (() => (typeof InternalError === 'undefined' ? undefined : InternalError)),
      'number':                    (() => Number),
      'bigint':                    (() => BigInt),
      'math':                      (() => Math),
      'date':                      (() => Date),
      'temporal':                  (() => (typeof Temporal === 'undefined' ? undefined : Temporal)),
      'string':                    (() => String),
      'reg-exp':                   (() => RegExp),
      'array':                     (() => Array),
      'typed-array':               (() => (typeof TypedArray === 'undefined' ? undefined : TypedArray)),
      'int8-array':                (() => Int8Array),
      'uint8-array':               (() => Uint8Array),
      'uint8-clamped-array':       (() => Uint8ClampedArray),
      'int16-array':               (() => Int16Array),
      'uint16-array':              (() => Uint16Array),
      'int32-array':               (() => Int32Array),
      'uint32-array':              (() => Uint32Array),
      'bigint64-array':            (() => (typeof BigInt64Array === 'undefined' ? undefined : BigInt64Array)),
      'biguint64-array':           (() => (typeof BigUint64Array === 'undefined' ? undefined : BigUint64Array)),
      'float16-array':             (() => (typeof Float16Array === 'undefined' ? undefined : Float16Array)),
      'float32-array':             (() => Float32Array),
      'float64-array':             (() => Float64Array),
      'map':                       (() => Map),
      'set':                       (() => Set),
      'weak-map':                  (() => WeakMap),
      'weak-set':                  (() => WeakSet),
      'array-buffer':              (() => ArrayBuffer),
      'shared-array-buffer':       (() => (typeof SharedArrayBuffer === 'undefined' ? undefined : SharedArrayBuffer)),
      'data-view':                 (() => DataView),
      'atomics':                   (() => (typeof Atomics === 'undefined' ? undefined : Atomics)),
      'json':                      (() => JSON),
      'weak-ref':                  (() => (typeof WeakRef === 'undefined' ? undefined : WeakRef)),
      'finalization-registry':     (() => (typeof FinalizationRegistry === 'undefined' ? undefined : FinalizationRegistry)),
      'iterator':                  (() => (typeof Iterator === 'undefined' ? undefined : Iterator)),
      'async-iterator':            (() => (typeof AsyncIterator === 'undefined' ? undefined : AsyncIterator)),
      'promise':                   (() => Promise),
      'generator-function':        (() => (typeof GeneratorFunction === 'undefined' ? undefined : GeneratorFunction)),
      'async-generator-function':  (() => (typeof AsyncGeneratorFunction === 'undefined' ? undefined : AsyncGeneratorFunction)),
      'generator':                 (() => (typeof Generator === 'undefined' ? undefined : Generator)),
      'async-generator':           (() => (typeof AsyncGenerator === 'undefined' ? undefined : AsyncGenerator)),
      'async-function':            (() => (typeof AsyncFunction === 'undefined' ? undefined : AsyncFunction)),
      'disposable-stack':          (() => (typeof DisposableStack === 'undefined' ? undefined : DisposableStack)),
      'async-disposable-stack':    (() => (typeof AsyncDisposableStack === 'undefined' ? undefined : AsyncDisposableStack)),
      'reflect':                   (() => Reflect),
      'proxy':                     (() => Proxy),
      'intl':                      (() => Intl),
      'intl-collator':             (() => ('Collator' in Intl ? Intl.Collator : undefined)),
      'intl-date-time-format':     (() => ('DateTimeFormat' in Intl ? Intl.DateTimeFormat : undefined)),
      'intl-display-names':        (() => ('DisplayNames' in Intl ? Intl.DisplayNames : undefined)),
      'intl-duration-format':      (() => ('DurationFormat' in Intl ? Intl.DurationFormat : undefined)),
      'intl-list-format':          (() => ('ListFormat' in Intl ? Intl.ListFormat : undefined)),
      'intl-locale':               (() => ('Locale' in Intl ? Intl.Locale : undefined)),
      'intl-number-format':        (() => ('NumberFormat' in Intl ? Intl.NumberFormat : undefined)),
      'intl-plural-rules':         (() => ('PluralRules' in Intl ? Intl.PluralRules : undefined)),
      'intl-relative-time-format': (() => ('RelativeTimeFormat' in Intl ? Intl.RelativeTimeFormat : undefined)),
      'intl-segmenter':            (() => ('Segmenter' in Intl ? Intl.Segmenter : undefined))
    },
    'math': {
        'abs':    ((x)       => Math.abs(x)),
        'acos':   ((x)       => Math.acos(x)),
        'acosh':  ((x)       => Math.acosh(x)),
        'asin':   ((x)       => Math.asin(x)),
        'asinh':  ((x)       => Math.asinh(x)),
        'atan':   ((x)       => Math.atan(x)),
        'atan2':  ((y, x)    => Math.atan2(y, x)),
        'atanh':  ((x)       => Math.atanh(x)),
        'cbrt':   ((x)       => Math.cbrt(x)),
        'ceil':   ((x)       => Math.ceil(x)),
        'clz32':  ((x)       => Math.clz32(x)),
        'cos':    ((x)       => Math.cos(x)),
        'cosh':   ((x)       => Math.cosh(x)),
        'exp':    ((x)       => Math.exp(x)),
        'expm1':  ((x)       => Math.expm1(x)),
        'floor':  ((x)       => Math.floor(x)),
        'fround': ((x)       => Math.fround(x)),
        'hypot':  ((x, y)    => Math.hypot(x, y)),
        'imul':   ((a, b)    => Math.imul(a, b)),
        'log':    ((x)       => Math.log(x)),
        'log10':  ((x)       => Math.log10(x)),
        'log1p':  ((x)       => Math.log1p(x)),
        'log2':   ((x)       => Math.log2(x)),
        'max':    ((x, y)    => Math.max(x, y)),
        'min':    ((x, y)    => Math.min(x, y)),
        'pow':    ((x, y)    => Math.pow(x, y)),
        'random': (()         => Math.random()),
        'round':  ((x)       => Math.round(x)),
        'sign':   ((x)       => Math.sign(x)),
        'sin':    ((x)       => Math.sin(x)),
        'sinh':   ((x)       => Math.sinh(x)),
        'sqrt':   ((x)       => Math.sqrt(x)),
        'tan':    ((x)       => Math.tan(x)),
        'tanh':   ((x)       => Math.tanh(x)),
        'trunc':  ((x)       => Math.trunc(x))
    },
    // Document
    'document': hasDOM ? {
        'body':                     (()                               => document.body),
        'create-element':           ((local_name)                     => document.createElement(from_fasl(local_name))),
        'create-text-node':         ((fasl_start)                     => document.createTextNode(from_fasl(fasl_start))),
        'adopt-node':               ((node)                           => document.adoptNode(node)),
        'caret-range-from-point':   ((x, y)                           => document.caretRangeFromPoint(x, y)),
        'capture-events':           (()                               => document.captureEvents()),
        'clear':                    (()                               => document.clear()),
        'close':                    (()                               => document.close()),
        'create-attribute':         ((name)                           => document.createAttribute(from_fasl(name))),
        'create-attribute-ns':      ((ns, name)                      => document.createAttributeNS(from_fasl(ns), from_fasl(name))),
        'create-cdata-section':     ((data)                           => document.createCDATASection(from_fasl(data))),
        'create-comment':           ((data)                           => document.createComment(from_fasl(data))),
        'create-document-fragment': (()                               => document.createDocumentFragment()),
        'create-element-ns':        ((ns, name)                       => document.createElementNS(from_fasl(ns), from_fasl(name))),
        'create-event':             ((type)                           => document.createEvent(from_fasl(type))),
        'create-expression':        ((expr, resolver)                 => document.createExpression(from_fasl(expr), resolver)),
        'create-ns-resolver':       ((node)                           => document.createNSResolver(node)),
        'create-node-iterator':     ((root, what, filter)             => document.createNodeIterator(root, what, filter)),
        'create-processing-instruction': ((target, data)             => document.createProcessingInstruction(from_fasl(target), from_fasl(data))),
        'create-range':             (()                               => document.createRange()),
        'create-tree-walker':       ((root, what, filter)             => document.createTreeWalker(root, what, filter)),
        'element-from-point':       ((x, y)                           => document.elementFromPoint(x, y)),
        'elements-from-point':      ((x, y)                           => document.elementsFromPoint(x, y)),
        'enable-style-sheets-for-set': ((name)                        => document.enableStyleSheetsForSet(from_fasl(name))),
        'evaluate':                 ((expr, ctx, resolver, type, result) => document.evaluate(from_fasl(expr), ctx, resolver, type, result)),
        'exec-command':             ((cmd, show_ui, value)            => document.execCommand(from_fasl(cmd), !!show_ui, from_fasl(value)) ? 1 : 0),
        'exit-fullscreen':          (()                               => document.exitFullscreen()),
        'exit-picture-in-picture':  (()                               => document.exitPictureInPicture()),
        'exit-pointer-lock':        (()                               => document.exitPointerLock()),
        'get-element-by-id':        ((id)                             => document.getElementById(from_fasl(id))),
        'get-elements-by-class-name': ((class_name)                   => document.getElementsByClassName(from_fasl(class_name))),
        'get-elements-by-name':     ((name)                           => document.getElementsByName(from_fasl(name))),
        'get-elements-by-tag-name': ((name)                           => document.getElementsByTagName(from_fasl(name))),
        'get-elements-by-tag-name-ns': ((ns, name)                    => document.getElementsByTagNameNS(from_fasl(ns), from_fasl(name))),
        'get-selection':            (()                               => document.getSelection()),
        'has-focus':                (()                               => document.hasFocus() ? 1 : 0),
        'import-node':              ((node, deep)                     => document.importNode(node, !!deep)),
        'open':                     (()                               => document.open()),
        // Deprecated:
        // 'query-command-enabled':    ((cmd)                            => document.queryCommandEnabled(from_fasl(cmd)) ? 1 : 0),
        // 'query-command-indeterm':   ((cmd)                            => document.queryCommandIndeterm(from_fasl(cmd)) ? 1 : 0),
        // 'query-command-state':      ((cmd)                            => document.queryCommandState(from_fasl(cmd)) ? 1 : 0),
        // 'query-command-supported':  ((cmd)                            => document.queryCommandSupported(from_fasl(cmd)) ? 1 : 0),
        // 'query-command-value':      ((cmd)                            => document.queryCommandValue(from_fasl(cmd))),
        'query-selector':           ((sel)                            => document.querySelector(from_fasl(sel))),
        'query-selector-all':       ((sel)                            => document.querySelectorAll(from_fasl(sel))),
        'release-events':           (()                               => document.releaseEvents()),
        // Deprecated
        // 'write':                    ((text)                           => document.write(from_fasl(text))),
        // 'writeln':                  ((text)                           => document.writeln(from_fasl(text))),
    }
    : { // Node
        'body'()                     { throw new Error('DOM not available in this environment'); },
        'create-element'()           { throw new Error('DOM not available in this environment'); },
        'create-text-node'()         { throw new Error('DOM not available in this environment'); },
        'adopt-node'()               { throw new Error('DOM not available in this environment'); },
        'caret-range-from-point'()   { throw new Error('DOM not available in this environment'); },
        'capture-events'()           { throw new Error('DOM not available in this environment'); },
        'clear'()                    { throw new Error('DOM not available in this environment'); },
        'close'()                    { throw new Error('DOM not available in this environment'); },
        'create-attribute'()         { throw new Error('DOM not available in this environment'); },
        'create-attribute-ns'()      { throw new Error('DOM not available in this environment'); },
        'create-cdata-section'()     { throw new Error('DOM not available in this environment'); },
        'create-comment'()           { throw new Error('DOM not available in this environment'); },
        'create-document-fragment'() { throw new Error('DOM not available in this environment'); },
        'create-element-ns'()        { throw new Error('DOM not available in this environment'); },
        'create-event'()             { throw new Error('DOM not available in this environment'); },
        'create-expression'()        { throw new Error('DOM not available in this environment'); },
        'create-ns-resolver'()       { throw new Error('DOM not available in this environment'); },
        'create-node-iterator'()     { throw new Error('DOM not available in this environment'); },
        'create-processing-instruction'() { throw new Error('DOM not available in this environment'); },
        'create-range'()             { throw new Error('DOM not available in this environment'); },
        'create-tree-walker'()       { throw new Error('DOM not available in this environment'); },
        'element-from-point'()       { throw new Error('DOM not available in this environment'); },
        'elements-from-point'()      { throw new Error('DOM not available in this environment'); },
        'enable-style-sheets-for-set'() { throw new Error('DOM not available in this environment'); },
        'evaluate'()                 { throw new Error('DOM not available in this environment'); },
        'exec-command'()             { throw new Error('DOM not available in this environment'); },
        'exit-fullscreen'()          { throw new Error('DOM not available in this environment'); },
        'exit-picture-in-picture'()  { throw new Error('DOM not available in this environment'); },
        'exit-pointer-lock'()        { throw new Error('DOM not available in this environment'); },
        'get-element-by-id'()        { throw new Error('DOM not available in this environment'); },
        'get-elements-by-class-name'() { throw new Error('DOM not available in this environment'); },
        'get-elements-by-name'()     { throw new Error('DOM not available in this environment'); },
        'get-elements-by-tag-name'() { throw new Error('DOM not available in this environment'); },
        'get-elements-by-tag-name-ns'() { throw new Error('DOM not available in this environment'); },
        'get-selection'()            { throw new Error('DOM not available in this environment'); },
        'has-focus'()                { throw new Error('DOM not available in this environment'); },
        'import-node'()              { throw new Error('DOM not available in this environment'); },
        'open'()                     { throw new Error('DOM not available in this environment'); },
        'query-command-enabled'()    { throw new Error('DOM not available in this environment'); },
        'query-command-indeterm'()   { throw new Error('DOM not available in this environment'); },
        'query-command-state'()      { throw new Error('DOM not available in this environment'); },
        'query-command-supported'()  { throw new Error('DOM not available in this environment'); },
        'query-command-value'()      { throw new Error('DOM not available in this environment'); },
        'query-selector'()           { throw new Error('DOM not available in this environment'); },
        'query-selector-all'()       { throw new Error('DOM not available in this environment'); },
        'release-events'()           { throw new Error('DOM not available in this environment'); },
        'write'()                    { throw new Error('DOM not available in this environment'); },
        'writeln'()                  { throw new Error('DOM not available in this environment'); },
    },
    // Element
    'element': hasDOM ? {
        'append-child!':           ((parent, child)          => parent.appendChild(child)),
        'set-attribute!':          ((elem, name, value)      => elem.setAttribute(from_fasl(name), from_fasl(value))),
        'after!':                  ((elem, node)            => elem.after(node)),
        'animate':                 ((elem, keyframes, opts) => elem.animate(keyframes, opts)),
        'append!':                 ((elem, node)            => elem.append(node)),
        'attach-shadow!':          ((elem, init)            => elem.attachShadow(init)),
        'before!':                 ((elem, node)            => elem.before(node)),
        'closest':                 ((elem, sel)             => elem.closest(from_fasl(sel))),
        'computed-style-map':      ((elem)                  => elem.computedStyleMap()),
        'get-animations':          ((elem)                  => elem.getAnimations()),
        'get-attribute':           ((elem, name)            => elem.getAttribute(from_fasl(name))),
        'get-attribute-ns':        ((elem, ns, name)       => elem.getAttributeNS(from_fasl(ns), from_fasl(name))),
        'get-attribute-names':     ((elem)                  => elem.getAttributeNames()),
        'get-attribute-node':      ((elem, name)            => elem.getAttributeNode(from_fasl(name))),
        'get-attribute-node-ns':   ((elem, ns, name)       => elem.getAttributeNodeNS(from_fasl(ns), from_fasl(name))),
        'get-bounding-client-rect':((elem)                  => elem.getBoundingClientRect()),
        'get-client-rects':        ((elem)                  => elem.getClientRects()),
        'get-elements-by-class-name': ((elem, class_name)   => elem.getElementsByClassName(from_fasl(class_name))),
        'get-elements-by-tag-name':  ((elem, name)          => elem.getElementsByTagName(from_fasl(name))),
        'get-elements-by-tag-name-ns': ((elem, ns, name)    => elem.getElementsByTagNameNS(from_fasl(ns), from_fasl(name))),
        'has-attribute':           ((elem, name)            => elem.hasAttribute(from_fasl(name)) ? 1 : 0),
        'has-attribute-ns':        ((elem, ns, name)       => elem.hasAttributeNS(from_fasl(ns), from_fasl(name)) ? 1 : 0),
        'has-attributes':          ((elem)                  => elem.hasAttributes() ? 1 : 0),
        'has-pointer-capture':     ((elem, id)             => elem.hasPointerCapture(id) ? 1 : 0),
        'insert-adjacent-element!':((elem, pos, newElem)   => elem.insertAdjacentElement(from_fasl(pos), newElem)),
        'insert-adjacent-html!':   ((elem, pos, data)      => elem.insertAdjacentHTML(from_fasl(pos), from_fasl(data))),
        'insert-adjacent-text!':   ((elem, pos, data)      => elem.insertAdjacentText(from_fasl(pos), from_fasl(data))),
        'matches':                 ((elem, sel)            => elem.matches(from_fasl(sel)) ? 1 : 0),
        'prepend!':                ((elem, node)           => elem.prepend(node)),
        'query-selector':          ((elem, sel)            => elem.querySelector(from_fasl(sel))),
        'query-selector-all':      ((elem, sel)            => elem.querySelectorAll(from_fasl(sel))),
        'release-pointer-capture!':((elem, id)             => elem.releasePointerCapture(id)),
        'remove!':                 ((elem)                  => elem.remove()),
        'remove-attribute!':       ((elem, name)            => elem.removeAttribute(from_fasl(name))),
        'remove-attribute-ns!':    ((elem, ns, name)       => elem.removeAttributeNS(from_fasl(ns), from_fasl(name))),
        'remove-attribute-node!':  ((elem, attr)           => elem.removeAttributeNode(attr)),
        'replace-children!':       ((elem, node)           => elem.replaceChildren(node)),
        'replace-with!':           ((elem, node)           => elem.replaceWith(node)),
        'request-fullscreen':      ((elem)                  => elem.requestFullscreen()),
        'request-pointer-lock':    ((elem)                  => elem.requestPointerLock()),
        'scroll!':                 ((elem, x, y)           => elem.scroll(x, y)),
        'scroll-by!':              ((elem, x, y)           => elem.scrollBy(x, y)),
        'scroll-into-view!':       ((elem, b)              => elem.scrollIntoView(!!b)),
        'scroll-to!':              ((elem, x, y)           => elem.scrollTo(x, y)),
        'set-attribute-ns!':       ((elem, ns, name, value)=> elem.setAttributeNS(from_fasl(ns), from_fasl(name), from_fasl(value))),
        'set-attribute-node!':     ((elem, attr)           => elem.setAttributeNode(attr)),
        'set-attribute-node-ns!':  ((elem, attr)           => elem.setAttributeNodeNS(attr)),
        'set-pointer-capture!':    ((elem, id)             => elem.setPointerCapture(id)),
        'toggle-attribute!':       ((elem, name, force)    => elem.toggleAttribute(from_fasl(name), !!force) ? 1 : 0),
    } : {
        'append-child!'()             { throw new Error('DOM not available in this environment'); },
        'set-attribute!'()            { throw new Error('DOM not available in this environment'); },
        'after!'()                    { throw new Error('DOM not available in this environment'); },
        'animate'()                   { throw new Error('DOM not available in this environment'); },
        'append!'()                   { throw new Error('DOM not available in this environment'); },
        'attach-shadow!'()            { throw new Error('DOM not available in this environment'); },
        'before!'()                   { throw new Error('DOM not available in this environment'); },
        'closest'()                   { throw new Error('DOM not available in this environment'); },
        'computed-style-map'()        { throw new Error('DOM not available in this environment'); },
        'get-animations'()            { throw new Error('DOM not available in this environment'); },
        'get-attribute'()             { throw new Error('DOM not available in this environment'); },
        'get-attribute-ns'()          { throw new Error('DOM not available in this environment'); },
        'get-attribute-names'()       { throw new Error('DOM not available in this environment'); },
        'get-attribute-node'()        { throw new Error('DOM not available in this environment'); },
        'get-attribute-node-ns'()     { throw new Error('DOM not available in this environment'); },
        'get-bounding-client-rect'()  { throw new Error('DOM not available in this environment'); },
        'get-client-rects'()          { throw new Error('DOM not available in this environment'); },
        'get-elements-by-class-name'(){ throw new Error('DOM not available in this environment'); },
        'get-elements-by-tag-name'()  { throw new Error('DOM not available in this environment'); },
        'get-elements-by-tag-name-ns'(){ throw new Error('DOM not available in this environment'); },
        'has-attribute'()             { throw new Error('DOM not available in this environment'); },
        'has-attribute-ns'()          { throw new Error('DOM not available in this environment'); },
        'has-attributes'()            { throw new Error('DOM not available in this environment'); },
        'has-pointer-capture'()       { throw new Error('DOM not available in this environment'); },
        'insert-adjacent-element!'()  { throw new Error('DOM not available in this environment'); },
        'insert-adjacent-html!'()     { throw new Error('DOM not available in this environment'); },
        'insert-adjacent-text!'()     { throw new Error('DOM not available in this environment'); },
        'matches'()                   { throw new Error('DOM not available in this environment'); },
        'prepend!'()                  { throw new Error('DOM not available in this environment'); },
        'query-selector'()            { throw new Error('DOM not available in this environment'); },
        'query-selector-all'()        { throw new Error('DOM not available in this environment'); },
        'release-pointer-capture!'()  { throw new Error('DOM not available in this environment'); },
        'remove!'()                   { throw new Error('DOM not available in this environment'); },
        'remove-attribute!'()         { throw new Error('DOM not available in this environment'); },
        'remove-attribute-ns!'()      { throw new Error('DOM not available in this environment'); },
        'remove-attribute-node!'()    { throw new Error('DOM not available in this environment'); },
        'replace-children!'()         { throw new Error('DOM not available in this environment'); },
        'replace-with!'()             { throw new Error('DOM not available in this environment'); },
        'request-fullscreen'()        { throw new Error('DOM not available in this environment'); },
        'request-pointer-lock'()      { throw new Error('DOM not available in this environment'); },
        'scroll!'()                   { throw new Error('DOM not available in this environment'); },
        'scroll-by!'()                { throw new Error('DOM not available in this environment'); },
        'scroll-into-view!'()         { throw new Error('DOM not available in this environment'); },
        'scroll-to!'()                { throw new Error('DOM not available in this environment'); },
        'set-attribute-ns!'()         { throw new Error('DOM not available in this environment'); },
        'set-attribute-node!'()       { throw new Error('DOM not available in this environment'); },
        'set-attribute-node-ns!'()    { throw new Error('DOM not available in this environment'); },
        'set-pointer-capture!'()      { throw new Error('DOM not available in this environment'); },
        'toggle-attribute!'()         { throw new Error('DOM not available in this environment'); },
    }
};

const wasmModule
      = await WebAssembly
      .instantiate(wasmBuffer, imports)
      .then(results  => { const { entry, get_bytes, copy_bytes_to_memory } = results.instance.exports;
                          var result = entry();
                          // console.log( "Output:")
                          // console.log( output_string );
                          // console.log( "Result:")
                          // console.log( result );

                          // console.log( "Result bytes:" )
                          const bytes  = new Uint8Array(memory.buffer, 0, result);
                          console.log(new TextDecoder().decode(bytes));
                        });





