#!/bin/bash
STAMP=$(date +%s)
cat > examples/minischeme/build-id.rkt <<EOF
;; Auto-generated by web-site/src/build.sh
(define minischeme-build-id "${STAMP}")
EOF

echo "-- Compiling web-site.rkt --"
racket ../../webracket.rkt --browser --ffi xtermjs --ffi dom --ffi standard --stdlib web-site.rkt

perl -0777 -i -pe "s/web-site\\.wasm\"/web-site.wasm?v=${STAMP}\"/g" web-site.html

ROUTE_ALIASES=(
  community
  documentation
  documentation-compiler-overview
  documentation-js-ffi
  examples
  formula1
  implementation-status
  installation
  mathjax
  matrix-rain
  minischeme
  quick-start
  space-invaders
  xtermjs-demo
)

for page in "${ROUTE_ALIASES[@]}"; do
  cp web-site.html "${page}.html"
done

echo "-- Copying Assets --"
cp web-site.wasm ../public
cp web-site.html ../public/index.html
cp web-site.html ../public/web-site.html
cp favicon.ico ../public

for page in "${ROUTE_ALIASES[@]}"; do
  cp web-site.html "../public/${page}.html"
done

echo "-- Done --"
if [[ "$(uname)" == "Darwin" ]]; then
  afplay /System/Library/Sounds/Glass.aiff
fi
