#!/bin/bash
set -euo pipefail

STAMP=$(date +%s)
OUT_DIR="../local"

format_generated_output() {
  sed -E 's#^Generated (.+) and (.+) \((.+ docs)\)\.$#Generated\n  \1\n  \2 \n  (\3).#'
}

echo "-- Generating FFI doc pages --"
if [[ "${SKIP_FFI_DOC_GEN:-0}" != "1" ]]; then
  racket generate-ffi-doc-pages.rkt | format_generated_output
  racket generate-ffi-doc-pages-structured.rkt | format_generated_output
else
  echo "Skipping FFI doc page generation (SKIP_FFI_DOC_GEN=1)"
fi

cat > examples/minischeme/build-id.rkt <<EOF
;; Auto-generated by web-site/src/build.sh
(define minischeme-build-id "${STAMP}")
EOF

echo "-- Compiling web-site.rkt --"
racket ../../webracket.rkt --browser --ffi xtermjs --ffi dom --ffi standard web-site.rkt

perl -0777 -i -pe "s/web-site\\.wasm\"/web-site.wasm?v=${STAMP}\"/g" web-site.html
# Keep `lang="en"` in the static HTML shell for baseline accessibility before
# WebRacket/Wasm initializes the page content.
perl -0777 -i -pe 's@<html>@<html lang="en">@s' web-site.html
# Keep a base style in the static HTML shell so first paint is close to the
# runtime theme before WebRacket/Wasm injects the full CSS.
perl -0777 -i -pe 's@<head>.*?</head>@<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><style>:root{--bg:#0C0D1A;--text:#E6E8F2;}html,body{margin:0;min-height:100%;background:radial-gradient(circle at top, rgba(101,79,240,0.25), transparent 55%), var(--bg);color:var(--text);}body{line-height:1.6;font-family:Inter,\"Fira Code\",system-ui,sans-serif;}</style></head>@s' web-site.html

ROUTE_ALIASES=(
  community
  documentation
  documentation-webracket-glance
  documentation-compiler-overview
  documentation-js-ffi
  documentation-ffi-standard
  documentation-ffi-dom
  documentation-ffi-js
  documentation-ffi-math
  documentation-ffi-jsxgraph
  documentation-ffi-xtermjs
  documentation-extended-example-jsxgraph-board-points
  documentation-extended-example-jsxgraph-geometry-constructors
  examples
  canvas-hexagons
  formula1
  implementation-status
  installation
  mathjax
  matrix-rain
  minischeme
  quick-start
  space-invaders
  xtermjs-demo
)

for page in "${ROUTE_ALIASES[@]}"; do
  cp web-site.html "${page}.html"
done

echo "-- Copying Assets --"
mkdir -p "${OUT_DIR}"
# Preserve mirrored new-site output under local/new when building old site only.
find "${OUT_DIR}" -mindepth 1 -maxdepth 1 ! -name new -exec rm -rf {} +
mkdir -p "${OUT_DIR}/assets/favicon"
mkdir -p "${OUT_DIR}/assets/examples/screenshots"
mkdir -p "${OUT_DIR}/assets/vendor/jsxgraph"

cp web-site.wasm "${OUT_DIR}"
cp web-site.html "${OUT_DIR}/index.html"
cp web-site.html "${OUT_DIR}/web-site.html"
cp assets/favicon/* "${OUT_DIR}/assets/favicon/"
cp assets/favicon/favicon.ico "${OUT_DIR}/favicon.ico"
cp assets/hex-racket-wasm-logo.svg "${OUT_DIR}/assets/hex-racket-wasm-logo.svg"
cp ../../assets/screenshots/examples/* "${OUT_DIR}/assets/examples/screenshots/"
cp ../../extras/jsxgraph/docs/static/jsxgraphcore.js "${OUT_DIR}/assets/vendor/jsxgraph/jsxgraphcore.js"
cp ../../extras/jsxgraph/docs/static/jsxgraph.css "${OUT_DIR}/assets/vendor/jsxgraph/jsxgraph.css"

for page in "${ROUTE_ALIASES[@]}"; do
  cp web-site.html "${OUT_DIR}/${page}.html"
done

echo "-- Done --"
if [[ "${SKIP_SOUND:-0}" != "1" && "$(uname)" == "Darwin" ]]; then
  afplay /System/Library/Sounds/Glass.aiff || true
fi
