#lang racket/base

(require racket/contract/base)

;; Docs-only fake bindings for raw FFI Scribble links.
;; This file is generated by scribblings/generate-ffi-labels.rkt.
;; To refresh it, run:
;;   racket scribblings/generate-ffi-labels.rkt <input.ffi> <output-labels.rkt>
;;
;; Scribble requires these identifiers so that @racket[...] and
;; @racketblock examples can link to the low-level FFI entries.
(provide
  js-performance-event-counts
  js-performance-interaction-count
  js-performance-memory
  js-performance-time-origin
  js-performance-now
  js-performance-clear-marks
  js-performance-clear-measures
  js-performance-clear-resource-timings
  js-performance-get-entries
  js-performance-get-entries-by-name
  js-performance-get-entries-by-type
  js-performance-mark
  js-performance-measure
  js-performance-measure-user-agent-specific-memory
  js-performance-set-resource-timing-buffer-size
  js-performance-to-json
  (for-label (all-defined-out)))

(define js-performance-event-counts any/c)
(define js-performance-interaction-count any/c)
(define js-performance-memory any/c)
(define js-performance-time-origin any/c)
(define js-performance-now any/c)
(define js-performance-clear-marks any/c)
(define js-performance-clear-measures any/c)
(define js-performance-clear-resource-timings any/c)
(define js-performance-get-entries any/c)
(define js-performance-get-entries-by-name any/c)
(define js-performance-get-entries-by-type any/c)
(define js-performance-mark any/c)
(define js-performance-measure any/c)
(define js-performance-measure-user-agent-specific-memory any/c)
(define js-performance-set-resource-timing-buffer-size any/c)
(define js-performance-to-json any/c)
