#lang racket/base

(require racket/contract/base)

;; Docs-only fake bindings for raw FFI Scribble links.
;; This file is generated by scribblings/generate-ffi-labels.rkt.
;; To refresh it, run:
;;   racket scribblings/generate-ffi-labels.rkt <input.ffi> <output-labels.rkt>
;;
;; Scribble requires these identifiers so that @racket[...] and
;; @racketblock examples can link to the low-level FFI entries.
(provide
  js-dom-rect-left
  js-dom-rect-top
  js-dom-rect-width
  js-dom-rect-height
  (for-label (all-defined-out)))

(define js-dom-rect-left any/c)
(define js-dom-rect-top any/c)
(define js-dom-rect-width any/c)
(define js-dom-rect-height any/c)
