#lang racket/base

(require racket/contract/base)

;; Docs-only fake bindings for raw FFI Scribble links.
;; This file is generated by scribblings/generate-ffi-labels.rkt.
;; To refresh it, run:
;;   racket scribblings/generate-ffi-labels.rkt <input.ffi> <output-labels.rkt>
;;
;; Scribble requires these identifiers so that @racket[...] and
;; @racketblock examples can link to the low-level FFI entries.
(provide
  js-websocket-new
  js-websocket-send
  js-websocket-close
  js-websocket-url
  js-websocket-ready-state
  js-websocket-buffered-amount
  js-websocket-protocol
  js-websocket-extensions
  (for-label (all-defined-out)))

(define js-websocket-new any/c)
(define js-websocket-send any/c)
(define js-websocket-close any/c)
(define js-websocket-url any/c)
(define js-websocket-ready-state any/c)
(define js-websocket-buffered-amount any/c)
(define js-websocket-protocol any/c)
(define js-websocket-extensions any/c)
