#lang racket/base

(require racket/contract/base)

;; Docs-only fake bindings for raw FFI Scribble links.
;; This file is generated by scribblings/generate-ffi-labels.rkt.
;; To refresh it, run:
;;   racket scribblings/generate-ffi-labels.rkt <input.ffi> <output-labels.rkt>
;;
;; Scribble requires these identifiers so that @racket[...] and
;; @racketblock examples can link to the low-level FFI entries.
(provide
  js-add-event-listener!
  js-event-new
  js-event?
  js-event-type
  js-event-target
  js-event-current-target
  js-event-event-phase
  js-event-bubbles
  js-event-cancelable
  js-event-default-prevented
  js-event-composed
  js-event-is-trusted
  js-event-time-stamp
  js-event-composed-path
  js-event-prevent-default
  js-event-stop-propagation
  js-event-stop-immediate-propagation
  js-mouse-event?
  js-mouse-event-offset-x
  js-mouse-event-offset-y
  js-mouse-event-client-x
  js-mouse-event-client-y
  js-mouse-event-page-x
  js-mouse-event-page-y
  js-mouse-event-screen-x
  js-mouse-event-screen-y
  js-mouse-event-button
  js-mouse-event-buttons
  js-mouse-event-alt-key
  js-mouse-event-ctrl-key
  js-mouse-event-meta-key
  js-mouse-event-shift-key
  js-keyboard-event?
  js-keyboard-event-key
  js-keyboard-event-code
  js-keyboard-event-alt-key
  js-keyboard-event-ctrl-key
  js-keyboard-event-meta-key
  js-keyboard-event-shift-key
  js-keyboard-event-repeat
  js-pointer-event?
  js-focus-event?
  js-input-event?
  js-submit-event?
  js-wheel-event?
  js-touch-event?
  js-touch-event-touches
  js-touch-event-target-touches
  js-touch-event-changed-touches
  js-touch-list?
  js-touch-list-length
  js-touch-list-ref
  js-touch?
  js-touch-identifier
  js-touch-client-x
  js-touch-client-y
  js-touch-page-x
  js-touch-page-y
  js-touch-screen-x
  js-touch-screen-y
  (for-label (all-defined-out)))

(define js-add-event-listener! any/c)
(define js-event-new any/c)
(define js-event? any/c)
(define js-event-type any/c)
(define js-event-target any/c)
(define js-event-current-target any/c)
(define js-event-event-phase any/c)
(define js-event-bubbles any/c)
(define js-event-cancelable any/c)
(define js-event-default-prevented any/c)
(define js-event-composed any/c)
(define js-event-is-trusted any/c)
(define js-event-time-stamp any/c)
(define js-event-composed-path any/c)
(define js-event-prevent-default any/c)
(define js-event-stop-propagation any/c)
(define js-event-stop-immediate-propagation any/c)
(define js-mouse-event? any/c)
(define js-mouse-event-offset-x any/c)
(define js-mouse-event-offset-y any/c)
(define js-mouse-event-client-x any/c)
(define js-mouse-event-client-y any/c)
(define js-mouse-event-page-x any/c)
(define js-mouse-event-page-y any/c)
(define js-mouse-event-screen-x any/c)
(define js-mouse-event-screen-y any/c)
(define js-mouse-event-button any/c)
(define js-mouse-event-buttons any/c)
(define js-mouse-event-alt-key any/c)
(define js-mouse-event-ctrl-key any/c)
(define js-mouse-event-meta-key any/c)
(define js-mouse-event-shift-key any/c)
(define js-keyboard-event? any/c)
(define js-keyboard-event-key any/c)
(define js-keyboard-event-code any/c)
(define js-keyboard-event-alt-key any/c)
(define js-keyboard-event-ctrl-key any/c)
(define js-keyboard-event-meta-key any/c)
(define js-keyboard-event-shift-key any/c)
(define js-keyboard-event-repeat any/c)
(define js-pointer-event? any/c)
(define js-focus-event? any/c)
(define js-input-event? any/c)
(define js-submit-event? any/c)
(define js-wheel-event? any/c)
(define js-touch-event? any/c)
(define js-touch-event-touches any/c)
(define js-touch-event-target-touches any/c)
(define js-touch-event-changed-touches any/c)
(define js-touch-list? any/c)
(define js-touch-list-length any/c)
(define js-touch-list-ref any/c)
(define js-touch? any/c)
(define js-touch-identifier any/c)
(define js-touch-client-x any/c)
(define js-touch-client-y any/c)
(define js-touch-page-x any/c)
(define js-touch-page-y any/c)
(define js-touch-screen-x any/c)
(define js-touch-screen-y any/c)
