#lang racket/base

(require racket/contract/base)

;; Docs-only fake bindings for raw FFI Scribble links.
;; This file is generated by scribblings/generate-ffi-labels.rkt.
;; To refresh it, run:
;;   racket scribblings/generate-ffi-labels.rkt <input.ffi> <output-labels.rkt>
;;
;; Scribble requires these identifiers so that @racket[...] and
;; @racketblock examples can link to the low-level FFI entries.
(provide
  js-audio-context-new
  js-audio-context-close
  js-audio-context-resume
  js-audio-context-suspend
  js-audio-context-state
  js-audio-context-current-time
  js-audio-context-sample-rate
  js-audio-context-base-latency
  js-audio-context-output-latency
  js-audio-context-destination
  js-audio-context-listener
  js-audio-context-create-gain
  js-audio-context-create-oscillator
  js-audio-context-create-buffer-source
  js-audio-context-create-analyser
  js-audio-context-create-biquad-filter
  js-audio-context-create-constant-source
  js-audio-context-create-channel-splitter
  js-audio-context-create-channel-merger
  js-audio-context-create-dynamics-compressor
  js-audio-context-create-panner
  js-audio-context-create-stereo-panner
  js-audio-context-create-buffer
  js-audio-context-decode-audio-data
  js-audio-node-context
  js-audio-node-connect
  js-audio-node-disconnect
  js-audio-param-value
  js-audio-param-set-value!
  js-audio-param-set-value-at-time!
  js-audio-param-linear-ramp-to-value-at-time!
  js-audio-param-exponential-ramp-to-value-at-time!
  js-audio-param-set-target-at-time!
  js-audio-param-set-value-curve-at-time!
  js-audio-param-cancel-scheduled-values!
  js-audio-param-cancel-and-hold-at-time!
  js-audio-buffer-length
  js-audio-buffer-duration
  js-audio-buffer-sample-rate
  js-audio-buffer-number-of-channels
  js-audio-buffer-get-channel-data
  js-audio-gain-node-gain
  js-audio-oscillator-node-type
  js-audio-oscillator-node-set-type!
  js-audio-oscillator-node-frequency
  js-audio-oscillator-node-detune
  js-audio-oscillator-node-start!
  js-audio-oscillator-node-stop!
  js-audio-oscillator-node-set-periodic-wave!
  js-audio-audio-buffer-source-node-buffer
  js-audio-audio-buffer-source-node-set-buffer!
  js-audio-audio-buffer-source-node-playback-rate
  js-audio-audio-buffer-source-node-detune
  js-audio-audio-buffer-source-node-loop
  js-audio-audio-buffer-source-node-set-loop!
  js-audio-audio-buffer-source-node-loop-start
  js-audio-audio-buffer-source-node-set-loop-start!
  js-audio-audio-buffer-source-node-loop-end
  js-audio-audio-buffer-source-node-set-loop-end!
  js-audio-audio-buffer-source-node-start!
  js-audio-audio-buffer-source-node-stop!
  js-audio-analyser-node-fft-size
  js-audio-analyser-node-set-fft-size!
  js-audio-analyser-node-frequency-bin-count
  js-audio-analyser-node-min-decibels
  js-audio-analyser-node-set-min-decibels!
  js-audio-analyser-node-max-decibels
  js-audio-analyser-node-set-max-decibels!
  js-audio-analyser-node-smoothing-time-constant
  js-audio-analyser-node-set-smoothing-time-constant!
  js-audio-analyser-node-get-byte-frequency-data!
  js-audio-analyser-node-get-byte-time-domain-data!
  js-audio-analyser-node-get-float-frequency-data!
  js-audio-analyser-node-get-float-time-domain-data!
  js-audio-biquad-filter-node-type
  js-audio-biquad-filter-node-set-type!
  js-audio-biquad-filter-node-frequency
  js-audio-biquad-filter-node-detune
  js-audio-biquad-filter-node-q
  js-audio-biquad-filter-node-gain
  js-audio-constant-source-node-offset
  js-audio-constant-source-node-start!
  js-audio-constant-source-node-stop!
  js-audio-dynamics-compressor-node-threshold
  js-audio-dynamics-compressor-node-knee
  js-audio-dynamics-compressor-node-ratio
  js-audio-dynamics-compressor-node-reduction
  js-audio-dynamics-compressor-node-attack
  js-audio-dynamics-compressor-node-release
  js-audio-panner-node-panning-model
  js-audio-panner-node-set-panning-model!
  js-audio-panner-node-distance-model
  js-audio-panner-node-set-distance-model!
  js-audio-panner-node-position-x
  js-audio-panner-node-position-y
  js-audio-panner-node-position-z
  js-audio-panner-node-orientation-x
  js-audio-panner-node-orientation-y
  js-audio-panner-node-orientation-z
  js-audio-panner-node-ref-distance
  js-audio-panner-node-set-ref-distance!
  js-audio-panner-node-max-distance
  js-audio-panner-node-set-max-distance!
  js-audio-panner-node-rolloff-factor
  js-audio-panner-node-set-rolloff-factor!
  js-audio-panner-node-cone-inner-angle
  js-audio-panner-node-set-cone-inner-angle!
  js-audio-panner-node-cone-outer-angle
  js-audio-panner-node-set-cone-outer-angle!
  js-audio-panner-node-cone-outer-gain
  js-audio-panner-node-set-cone-outer-gain!
  js-audio-stereo-panner-node-pan
  (for-label (all-defined-out)))

(define js-audio-context-new any/c)
(define js-audio-context-close any/c)
(define js-audio-context-resume any/c)
(define js-audio-context-suspend any/c)
(define js-audio-context-state any/c)
(define js-audio-context-current-time any/c)
(define js-audio-context-sample-rate any/c)
(define js-audio-context-base-latency any/c)
(define js-audio-context-output-latency any/c)
(define js-audio-context-destination any/c)
(define js-audio-context-listener any/c)
(define js-audio-context-create-gain any/c)
(define js-audio-context-create-oscillator any/c)
(define js-audio-context-create-buffer-source any/c)
(define js-audio-context-create-analyser any/c)
(define js-audio-context-create-biquad-filter any/c)
(define js-audio-context-create-constant-source any/c)
(define js-audio-context-create-channel-splitter any/c)
(define js-audio-context-create-channel-merger any/c)
(define js-audio-context-create-dynamics-compressor any/c)
(define js-audio-context-create-panner any/c)
(define js-audio-context-create-stereo-panner any/c)
(define js-audio-context-create-buffer any/c)
(define js-audio-context-decode-audio-data any/c)
(define js-audio-node-context any/c)
(define js-audio-node-connect any/c)
(define js-audio-node-disconnect any/c)
(define js-audio-param-value any/c)
(define js-audio-param-set-value! any/c)
(define js-audio-param-set-value-at-time! any/c)
(define js-audio-param-linear-ramp-to-value-at-time! any/c)
(define js-audio-param-exponential-ramp-to-value-at-time! any/c)
(define js-audio-param-set-target-at-time! any/c)
(define js-audio-param-set-value-curve-at-time! any/c)
(define js-audio-param-cancel-scheduled-values! any/c)
(define js-audio-param-cancel-and-hold-at-time! any/c)
(define js-audio-buffer-length any/c)
(define js-audio-buffer-duration any/c)
(define js-audio-buffer-sample-rate any/c)
(define js-audio-buffer-number-of-channels any/c)
(define js-audio-buffer-get-channel-data any/c)
(define js-audio-gain-node-gain any/c)
(define js-audio-oscillator-node-type any/c)
(define js-audio-oscillator-node-set-type! any/c)
(define js-audio-oscillator-node-frequency any/c)
(define js-audio-oscillator-node-detune any/c)
(define js-audio-oscillator-node-start! any/c)
(define js-audio-oscillator-node-stop! any/c)
(define js-audio-oscillator-node-set-periodic-wave! any/c)
(define js-audio-audio-buffer-source-node-buffer any/c)
(define js-audio-audio-buffer-source-node-set-buffer! any/c)
(define js-audio-audio-buffer-source-node-playback-rate any/c)
(define js-audio-audio-buffer-source-node-detune any/c)
(define js-audio-audio-buffer-source-node-loop any/c)
(define js-audio-audio-buffer-source-node-set-loop! any/c)
(define js-audio-audio-buffer-source-node-loop-start any/c)
(define js-audio-audio-buffer-source-node-set-loop-start! any/c)
(define js-audio-audio-buffer-source-node-loop-end any/c)
(define js-audio-audio-buffer-source-node-set-loop-end! any/c)
(define js-audio-audio-buffer-source-node-start! any/c)
(define js-audio-audio-buffer-source-node-stop! any/c)
(define js-audio-analyser-node-fft-size any/c)
(define js-audio-analyser-node-set-fft-size! any/c)
(define js-audio-analyser-node-frequency-bin-count any/c)
(define js-audio-analyser-node-min-decibels any/c)
(define js-audio-analyser-node-set-min-decibels! any/c)
(define js-audio-analyser-node-max-decibels any/c)
(define js-audio-analyser-node-set-max-decibels! any/c)
(define js-audio-analyser-node-smoothing-time-constant any/c)
(define js-audio-analyser-node-set-smoothing-time-constant! any/c)
(define js-audio-analyser-node-get-byte-frequency-data! any/c)
(define js-audio-analyser-node-get-byte-time-domain-data! any/c)
(define js-audio-analyser-node-get-float-frequency-data! any/c)
(define js-audio-analyser-node-get-float-time-domain-data! any/c)
(define js-audio-biquad-filter-node-type any/c)
(define js-audio-biquad-filter-node-set-type! any/c)
(define js-audio-biquad-filter-node-frequency any/c)
(define js-audio-biquad-filter-node-detune any/c)
(define js-audio-biquad-filter-node-q any/c)
(define js-audio-biquad-filter-node-gain any/c)
(define js-audio-constant-source-node-offset any/c)
(define js-audio-constant-source-node-start! any/c)
(define js-audio-constant-source-node-stop! any/c)
(define js-audio-dynamics-compressor-node-threshold any/c)
(define js-audio-dynamics-compressor-node-knee any/c)
(define js-audio-dynamics-compressor-node-ratio any/c)
(define js-audio-dynamics-compressor-node-reduction any/c)
(define js-audio-dynamics-compressor-node-attack any/c)
(define js-audio-dynamics-compressor-node-release any/c)
(define js-audio-panner-node-panning-model any/c)
(define js-audio-panner-node-set-panning-model! any/c)
(define js-audio-panner-node-distance-model any/c)
(define js-audio-panner-node-set-distance-model! any/c)
(define js-audio-panner-node-position-x any/c)
(define js-audio-panner-node-position-y any/c)
(define js-audio-panner-node-position-z any/c)
(define js-audio-panner-node-orientation-x any/c)
(define js-audio-panner-node-orientation-y any/c)
(define js-audio-panner-node-orientation-z any/c)
(define js-audio-panner-node-ref-distance any/c)
(define js-audio-panner-node-set-ref-distance! any/c)
(define js-audio-panner-node-max-distance any/c)
(define js-audio-panner-node-set-max-distance! any/c)
(define js-audio-panner-node-rolloff-factor any/c)
(define js-audio-panner-node-set-rolloff-factor! any/c)
(define js-audio-panner-node-cone-inner-angle any/c)
(define js-audio-panner-node-set-cone-inner-angle! any/c)
(define js-audio-panner-node-cone-outer-angle any/c)
(define js-audio-panner-node-set-cone-outer-angle! any/c)
(define js-audio-panner-node-cone-outer-gain any/c)
(define js-audio-panner-node-set-cone-outer-gain! any/c)
(define js-audio-stereo-panner-node-pan any/c)
