#lang racket/base

(require racket/contract/base)

;; Docs-only fake bindings for raw FFI Scribble links.
;; This file is generated by scribblings/generate-ffi-labels.rkt.
;; To refresh it, run:
;;   racket scribblings/generate-ffi-labels.rkt <input.ffi> <output-labels.rkt>
;;
;; Scribble requires these identifiers so that @racket[...] and
;; @racketblock examples can link to the low-level FFI entries.
(provide
  js-jsx-init-board
  js-jsx-board-create
  js-jsx-board-create-point
  js-jsx-board-create-line
  js-jsx-board-create-segment
  js-jsx-board-create-circle
  js-jsx-board-create-intersection
  js-jsx-board-create-text
  js-jsx-board-update!
  js-jsx-board-full-update!
  js-jsx-board-remove-object!
  js-jsx-board-suspend-update!
  js-jsx-board-unsuspend-update!
  js-jsx-point?
  js-jsx-point-attractor-distance
  js-jsx-set-point-attractor-distance!
  js-jsx-point-attractors
  js-jsx-set-point-attractors!
  js-jsx-point-attractor-unit
  js-jsx-set-point-attractor-unit!
  js-jsx-point-attract-to-grid
  js-jsx-set-point-attract-to-grid!
  js-jsx-point-face
  js-jsx-set-point-face!
  js-jsx-point-ignored-snap-to-points
  js-jsx-set-point-ignored-snap-to-points!
  js-jsx-point-infobox-digits
  js-jsx-set-point-infobox-digits!
  js-jsx-point-show-infobox
  js-jsx-set-point-show-infobox!
  js-jsx-point-size
  js-jsx-set-point-size!
  js-jsx-point-size-unit
  js-jsx-set-point-size-unit!
  js-jsx-point-snap-size-x
  js-jsx-set-point-snap-size-x!
  js-jsx-point-snap-size-y
  js-jsx-set-point-snap-size-y!
  js-jsx-point-snap-to-grid
  js-jsx-set-point-snap-to-grid!
  js-jsx-point-snap-to-points
  js-jsx-set-point-snap-to-points!
  js-jsx-point-snatch-distance
  js-jsx-set-point-snatch-distance!
  js-jsx-point-style
  js-jsx-set-point-style!
  js-jsx-point-x
  js-jsx-point-y
  js-jsx-point-zoom
  js-jsx-set-point-zoom!
  js-jsx-point-has-point
  js-jsx-point-is-on
  js-jsx-point-make-intersection!
  js-jsx-point-normalize-face
  js-jsx-point-set-style!
  js-jsx-point-update!
  js-jsx-point-update-renderer!
  js-jsx-point-update-transform!
  (for-label (all-defined-out)))

(define js-jsx-init-board any/c)
(define js-jsx-board-create any/c)
(define js-jsx-board-create-point any/c)
(define js-jsx-board-create-line any/c)
(define js-jsx-board-create-segment any/c)
(define js-jsx-board-create-circle any/c)
(define js-jsx-board-create-intersection any/c)
(define js-jsx-board-create-text any/c)
(define js-jsx-board-update! any/c)
(define js-jsx-board-full-update! any/c)
(define js-jsx-board-remove-object! any/c)
(define js-jsx-board-suspend-update! any/c)
(define js-jsx-board-unsuspend-update! any/c)
(define js-jsx-point? any/c)
(define js-jsx-point-attractor-distance any/c)
(define js-jsx-set-point-attractor-distance! any/c)
(define js-jsx-point-attractors any/c)
(define js-jsx-set-point-attractors! any/c)
(define js-jsx-point-attractor-unit any/c)
(define js-jsx-set-point-attractor-unit! any/c)
(define js-jsx-point-attract-to-grid any/c)
(define js-jsx-set-point-attract-to-grid! any/c)
(define js-jsx-point-face any/c)
(define js-jsx-set-point-face! any/c)
(define js-jsx-point-ignored-snap-to-points any/c)
(define js-jsx-set-point-ignored-snap-to-points! any/c)
(define js-jsx-point-infobox-digits any/c)
(define js-jsx-set-point-infobox-digits! any/c)
(define js-jsx-point-show-infobox any/c)
(define js-jsx-set-point-show-infobox! any/c)
(define js-jsx-point-size any/c)
(define js-jsx-set-point-size! any/c)
(define js-jsx-point-size-unit any/c)
(define js-jsx-set-point-size-unit! any/c)
(define js-jsx-point-snap-size-x any/c)
(define js-jsx-set-point-snap-size-x! any/c)
(define js-jsx-point-snap-size-y any/c)
(define js-jsx-set-point-snap-size-y! any/c)
(define js-jsx-point-snap-to-grid any/c)
(define js-jsx-set-point-snap-to-grid! any/c)
(define js-jsx-point-snap-to-points any/c)
(define js-jsx-set-point-snap-to-points! any/c)
(define js-jsx-point-snatch-distance any/c)
(define js-jsx-set-point-snatch-distance! any/c)
(define js-jsx-point-style any/c)
(define js-jsx-set-point-style! any/c)
(define js-jsx-point-x any/c)
(define js-jsx-point-y any/c)
(define js-jsx-point-zoom any/c)
(define js-jsx-set-point-zoom! any/c)
(define js-jsx-point-has-point any/c)
(define js-jsx-point-is-on any/c)
(define js-jsx-point-make-intersection! any/c)
(define js-jsx-point-normalize-face any/c)
(define js-jsx-point-set-style! any/c)
(define js-jsx-point-update! any/c)
(define js-jsx-point-update-renderer! any/c)
(define js-jsx-point-update-transform! any/c)
