#lang racket/base

(require racket/contract/base)

;; Docs-only fake bindings for raw FFI Scribble links.
;; This file is generated by scribblings/generate-ffi-labels.rkt.
;; To refresh it, run:
;;   racket scribblings/generate-ffi-labels.rkt <input.ffi> <output-labels.rkt>
;;
;; Scribble requires these identifiers so that @racket[...] and
;; @racketblock examples can link to the low-level FFI entries.
(provide
  js-image-new
  js-image-alt
  js-set-image-alt!
  js-image-src
  js-set-image-src!
  js-image-srcset
  js-set-image-srcset!
  js-image-sizes
  js-set-image-sizes!
  js-image-cross-origin
  js-set-image-cross-origin!
  js-image-use-map
  js-set-image-use-map!
  js-image-is-map
  js-set-image-is-map!
  js-image-width
  js-set-image-width!
  js-image-height
  js-set-image-height!
  js-image-natural-width
  js-image-natural-height
  js-image-complete
  js-image-current-src
  js-image-decoding
  js-set-image-decoding!
  js-image-fetch-priority
  js-set-image-fetch-priority!
  js-image-loading
  js-set-image-loading!
  js-image-referrer-policy
  js-set-image-referrer-policy!
  js-image-name
  js-set-image-name!
  js-image-x
  js-image-y
  js-image-decode
  (for-label (all-defined-out)))

(define js-image-new any/c)
(define js-image-alt any/c)
(define js-set-image-alt! any/c)
(define js-image-src any/c)
(define js-set-image-src! any/c)
(define js-image-srcset any/c)
(define js-set-image-srcset! any/c)
(define js-image-sizes any/c)
(define js-set-image-sizes! any/c)
(define js-image-cross-origin any/c)
(define js-set-image-cross-origin! any/c)
(define js-image-use-map any/c)
(define js-set-image-use-map! any/c)
(define js-image-is-map any/c)
(define js-set-image-is-map! any/c)
(define js-image-width any/c)
(define js-set-image-width! any/c)
(define js-image-height any/c)
(define js-set-image-height! any/c)
(define js-image-natural-width any/c)
(define js-image-natural-height any/c)
(define js-image-complete any/c)
(define js-image-current-src any/c)
(define js-image-decoding any/c)
(define js-set-image-decoding! any/c)
(define js-image-fetch-priority any/c)
(define js-set-image-fetch-priority! any/c)
(define js-image-loading any/c)
(define js-set-image-loading! any/c)
(define js-image-referrer-policy any/c)
(define js-set-image-referrer-policy! any/c)
(define js-image-name any/c)
(define js-set-image-name! any/c)
(define js-image-x any/c)
(define js-image-y any/c)
(define js-image-decode any/c)
