#lang racket/base

(require racket/contract/base)

;; Docs-only fake bindings for raw FFI Scribble links.
;; This file is generated by scribblings/generate-ffi-labels.rkt.
;; To refresh it, run:
;;   racket scribblings/generate-ffi-labels.rkt <input.ffi> <output-labels.rkt>
;;
;; Scribble requires these identifiers so that @racket[...] and
;; @racketblock examples can link to the low-level FFI entries.
(provide
  js-window-window
  js-window-self
  js-window-document
  js-window-name
  js-set-window-name!
  js-window-location
  js-set-window-location!
  js-window-custom-elements
  js-window-history
  js-window-locationbar
  js-window-menubar
  js-window-personalbar
  js-window-scrollbars
  js-window-statusbar
  js-window-toolbar
  js-window-closed
  js-window-frames
  js-window-length
  js-window-opener
  js-set-window-opener!
  js-window-parent
  js-window-top
  js-window-visual-viewport
  js-window-navigator
  js-window-origin
  js-window-crypto
  js-window-device-pixel-ratio
  js-window-frame-element
  js-window-inner-height
  js-window-inner-width
  js-window-outer-height
  js-window-outer-width
  js-window-screen-x
  js-window-screen-y
  js-window-screen-left
  js-window-screen-top
  js-window-page-x-offset
  js-window-page-y-offset
  js-window-scroll-x
  js-window-scroll-y
  js-window-screen
  js-window-local-storage
  js-window-session-storage
  js-window-performance
  js-window-indexed-db
  js-window-is-secure-context
  js-window-cross-origin-isolated
  js-window-caches
  js-window-speech-synthesis
  js-window-style-media
  js-window-alert
  js-window-atob
  js-window-btoa
  js-window-cancel-animation-frame
  js-window-cancel-idle-callback
  js-window-clear-interval
  js-window-clear-timeout
  js-window-close
  js-window-confirm
  js-window-create-image-bitmap
  js-window-fetch
  js-window-focus
  js-window-get-computed-style
  js-window-get-selection
  js-window-match-media
  js-window-move-by
  js-window-move-to
  js-window-open
  js-window-post-message
  js-window-print
  js-window-prompt
  js-window-request-animation-frame
  js-window-request-idle-callback
  js-window-resize-by
  js-window-resize-to
  js-window-scroll
  js-window-scroll-by
  js-window-scroll-to
  js-window-set-interval
  js-window-set-timeout
  js-window-set-timeout/delay
  js-window-stop
  js-window-structured-clone
  js-window-queue-microtask
  js-window-report-error
  (for-label (all-defined-out)))

(define js-window-window any/c)
(define js-window-self any/c)
(define js-window-document any/c)
(define js-window-name any/c)
(define js-set-window-name! any/c)
(define js-window-location any/c)
(define js-set-window-location! any/c)
(define js-window-custom-elements any/c)
(define js-window-history any/c)
(define js-window-locationbar any/c)
(define js-window-menubar any/c)
(define js-window-personalbar any/c)
(define js-window-scrollbars any/c)
(define js-window-statusbar any/c)
(define js-window-toolbar any/c)
(define js-window-closed any/c)
(define js-window-frames any/c)
(define js-window-length any/c)
(define js-window-opener any/c)
(define js-set-window-opener! any/c)
(define js-window-parent any/c)
(define js-window-top any/c)
(define js-window-visual-viewport any/c)
(define js-window-navigator any/c)
(define js-window-origin any/c)
(define js-window-crypto any/c)
(define js-window-device-pixel-ratio any/c)
(define js-window-frame-element any/c)
(define js-window-inner-height any/c)
(define js-window-inner-width any/c)
(define js-window-outer-height any/c)
(define js-window-outer-width any/c)
(define js-window-screen-x any/c)
(define js-window-screen-y any/c)
(define js-window-screen-left any/c)
(define js-window-screen-top any/c)
(define js-window-page-x-offset any/c)
(define js-window-page-y-offset any/c)
(define js-window-scroll-x any/c)
(define js-window-scroll-y any/c)
(define js-window-screen any/c)
(define js-window-local-storage any/c)
(define js-window-session-storage any/c)
(define js-window-performance any/c)
(define js-window-indexed-db any/c)
(define js-window-is-secure-context any/c)
(define js-window-cross-origin-isolated any/c)
(define js-window-caches any/c)
(define js-window-speech-synthesis any/c)
(define js-window-style-media any/c)
(define js-window-alert any/c)
(define js-window-atob any/c)
(define js-window-btoa any/c)
(define js-window-cancel-animation-frame any/c)
(define js-window-cancel-idle-callback any/c)
(define js-window-clear-interval any/c)
(define js-window-clear-timeout any/c)
(define js-window-close any/c)
(define js-window-confirm any/c)
(define js-window-create-image-bitmap any/c)
(define js-window-fetch any/c)
(define js-window-focus any/c)
(define js-window-get-computed-style any/c)
(define js-window-get-selection any/c)
(define js-window-match-media any/c)
(define js-window-move-by any/c)
(define js-window-move-to any/c)
(define js-window-open any/c)
(define js-window-post-message any/c)
(define js-window-print any/c)
(define js-window-prompt any/c)
(define js-window-request-animation-frame any/c)
(define js-window-request-idle-callback any/c)
(define js-window-resize-by any/c)
(define js-window-resize-to any/c)
(define js-window-scroll any/c)
(define js-window-scroll-by any/c)
(define js-window-scroll-to any/c)
(define js-window-set-interval any/c)
(define js-window-set-timeout any/c)
(define js-window-set-timeout/delay any/c)
(define js-window-stop any/c)
(define js-window-structured-clone any/c)
(define js-window-queue-microtask any/c)
(define js-window-report-error any/c)
