#lang racket/base

(require racket/contract/base)

;; Docs-only fake bindings for raw FFI Scribble links.
;; This file is generated by scribblings/generate-ffi-labels.rkt.
;; To refresh it, run:
;;   racket scribblings/generate-ffi-labels.rkt <input.ffi> <output-labels.rkt>
;;
;; Scribble requires these identifiers so that @racket[...] and
;; @racketblock examples can link to the low-level FFI entries.
(provide
  js-media-audio-tracks
  js-media-autoplay
  js-set-media-autoplay!
  js-media-buffered
  js-media-controls
  js-set-media-controls!
  js-media-controls-list
  js-media-cross-origin
  js-set-media-cross-origin!
  js-media-current-src
  js-media-current-time
  js-set-media-current-time!
  js-media-default-muted
  js-set-media-default-muted!
  js-media-default-playback-rate
  js-set-media-default-playback-rate!
  js-media-disable-remote-playback
  js-set-media-disable-remote-playback!
  js-media-duration
  js-media-ended
  js-media-error
  js-media-loop
  js-set-media-loop!
  js-media-media-keys
  js-media-media-group
  js-set-media-media-group!
  js-media-muted
  js-set-media-muted!
  js-media-network-state
  js-media-paused
  js-media-playback-rate
  js-set-media-playback-rate!
  js-media-played
  js-media-preload
  js-set-media-preload!
  js-media-preserves-pitch
  js-set-media-preserves-pitch!
  js-media-ready-state
  js-media-seekable
  js-media-seeking
  js-media-sink-id
  js-media-src
  js-set-media-src!
  js-media-src-object
  js-set-media-src-object!
  js-media-text-tracks
  js-media-video-tracks
  js-media-volume
  js-set-media-volume!
  js-media-add-text-track!
  js-media-can-play-type
  js-media-capture-stream
  js-media-fast-seek!
  js-media-load!
  js-media-pause
  js-media-play
  js-media-set-media-keys!
  js-media-set-sink-id!
  (for-label (all-defined-out)))

(define js-media-audio-tracks any/c)
(define js-media-autoplay any/c)
(define js-set-media-autoplay! any/c)
(define js-media-buffered any/c)
(define js-media-controls any/c)
(define js-set-media-controls! any/c)
(define js-media-controls-list any/c)
(define js-media-cross-origin any/c)
(define js-set-media-cross-origin! any/c)
(define js-media-current-src any/c)
(define js-media-current-time any/c)
(define js-set-media-current-time! any/c)
(define js-media-default-muted any/c)
(define js-set-media-default-muted! any/c)
(define js-media-default-playback-rate any/c)
(define js-set-media-default-playback-rate! any/c)
(define js-media-disable-remote-playback any/c)
(define js-set-media-disable-remote-playback! any/c)
(define js-media-duration any/c)
(define js-media-ended any/c)
(define js-media-error any/c)
(define js-media-loop any/c)
(define js-set-media-loop! any/c)
(define js-media-media-keys any/c)
(define js-media-media-group any/c)
(define js-set-media-media-group! any/c)
(define js-media-muted any/c)
(define js-set-media-muted! any/c)
(define js-media-network-state any/c)
(define js-media-paused any/c)
(define js-media-playback-rate any/c)
(define js-set-media-playback-rate! any/c)
(define js-media-played any/c)
(define js-media-preload any/c)
(define js-set-media-preload! any/c)
(define js-media-preserves-pitch any/c)
(define js-set-media-preserves-pitch! any/c)
(define js-media-ready-state any/c)
(define js-media-seekable any/c)
(define js-media-seeking any/c)
(define js-media-sink-id any/c)
(define js-media-src any/c)
(define js-set-media-src! any/c)
(define js-media-src-object any/c)
(define js-set-media-src-object! any/c)
(define js-media-text-tracks any/c)
(define js-media-video-tracks any/c)
(define js-media-volume any/c)
(define js-set-media-volume! any/c)
(define js-media-add-text-track! any/c)
(define js-media-can-play-type any/c)
(define js-media-capture-stream any/c)
(define js-media-fast-seek! any/c)
(define js-media-load! any/c)
(define js-media-pause any/c)
(define js-media-play any/c)
(define js-media-set-media-keys! any/c)
(define js-media-set-sink-id! any/c)
