#lang racket/base

(require racket/contract/base)

;; Docs-only fake bindings for raw FFI Scribble links.
;; This file is generated by scribblings/generate-ffi-labels.rkt.
;; To refresh it, run:
;;   racket scribblings/generate-ffi-labels.rkt <input.ffi> <output-labels.rkt>
;;
;; Scribble requires these identifiers so that @racket[...] and
;; @racketblock examples can link to the low-level FFI entries.
(provide
  js-canvas-capture-stream
  js-canvas-get-context
  js-canvas-height
  js-set-canvas-height!
  js-canvas-to-blob
  js-canvas-to-data-url
  js-canvas-transfer-control-to-offscreen
  js-canvas-width
  js-set-canvas-width!
  js-canvas2d-canvas
  js-canvas2d-direction
  js-set-canvas2d-direction!
  js-canvas2d-fill-style
  js-set-canvas2d-fill-style!
  js-canvas2d-filter
  js-set-canvas2d-filter!
  js-canvas2d-font
  js-set-canvas2d-font!
  js-canvas2d-global-alpha
  js-set-canvas2d-global-alpha!
  js-canvas2d-global-composite-operation
  js-set-canvas2d-global-composite-operation!
  js-canvas2d-image-smoothing-enabled
  js-set-canvas2d-image-smoothing-enabled!
  js-canvas2d-image-smoothing-quality
  js-set-canvas2d-image-smoothing-quality!
  js-canvas2d-line-cap
  js-set-canvas2d-line-cap!
  js-canvas2d-line-dash-offset
  js-set-canvas2d-line-dash-offset!
  js-canvas2d-line-join
  js-set-canvas2d-line-join!
  js-canvas2d-line-width
  js-set-canvas2d-line-width!
  js-canvas2d-miter-limit
  js-set-canvas2d-miter-limit!
  js-canvas2d-shadow-blur
  js-set-canvas2d-shadow-blur!
  js-canvas2d-shadow-color
  js-set-canvas2d-shadow-color!
  js-canvas2d-shadow-offset-x
  js-set-canvas2d-shadow-offset-x!
  js-canvas2d-shadow-offset-y
  js-set-canvas2d-shadow-offset-y!
  js-canvas2d-stroke-style
  js-set-canvas2d-stroke-style!
  js-canvas2d-text-align
  js-set-canvas2d-text-align!
  js-canvas2d-text-baseline
  js-set-canvas2d-text-baseline!
  js-canvas2d-text-rendering
  js-set-canvas2d-text-rendering!
  js-canvas2d-font-kerning
  js-set-canvas2d-font-kerning!
  js-canvas2d-font-stretch
  js-set-canvas2d-font-stretch!
  js-canvas2d-font-variant-caps
  js-set-canvas2d-font-variant-caps!
  js-canvas2d-font-variant-ligatures
  js-set-canvas2d-font-variant-ligatures!
  js-canvas2d-font-variant-numeric
  js-set-canvas2d-font-variant-numeric!
  js-canvas2d-letter-spacing
  js-set-canvas2d-letter-spacing!
  js-canvas2d-word-spacing
  js-set-canvas2d-word-spacing!
  js-canvas2d-arc
  js-canvas2d-arc-to
  js-canvas2d-begin-path
  js-canvas2d-bezier-curve-to
  js-canvas2d-clear-rect
  js-canvas2d-clip
  js-canvas2d-close-path
  js-canvas2d-create-image-data
  js-canvas2d-create-image-data-from
  js-canvas2d-create-linear-gradient
  js-canvas2d-create-pattern
  js-canvas2d-create-radial-gradient
  js-canvas2d-create-conic-gradient
  js-canvas2d-draw-focus-if-needed!
  js-canvas2d-draw-focus-if-needed-path!
  js-canvas2d-draw-image
  js-canvas2d-draw-image-5
  js-canvas2d-draw-image-9
  js-canvas2d-ellipse
  js-canvas2d-fill
  js-canvas2d-fill-rect
  js-canvas2d-fill-text
  js-canvas2d-get-image-data
  js-canvas2d-get-line-dash
  js-canvas2d-get-transform
  js-canvas2d-is-point-in-path
  js-canvas2d-is-point-in-stroke
  js-canvas2d-line-to
  js-canvas2d-measure-text
  js-canvas2d-move-to
  js-canvas2d-put-image-data
  js-canvas2d-quadratic-curve-to
  js-canvas2d-rect
  js-canvas2d-reset
  js-canvas2d-reset-transform
  js-canvas2d-restore
  js-canvas2d-rotate
  js-canvas2d-round-rect
  js-canvas2d-save
  js-canvas2d-scale
  js-canvas2d-set-line-dash
  js-canvas2d-set-transform!
  js-canvas2d-set-transform-matrix!
  js-canvas2d-stroke
  js-canvas2d-stroke-rect
  js-canvas2d-stroke-text
  js-canvas2d-transform
  js-canvas2d-translate
  (for-label (all-defined-out)))

(define js-canvas-capture-stream any/c)
(define js-canvas-get-context any/c)
(define js-canvas-height any/c)
(define js-set-canvas-height! any/c)
(define js-canvas-to-blob any/c)
(define js-canvas-to-data-url any/c)
(define js-canvas-transfer-control-to-offscreen any/c)
(define js-canvas-width any/c)
(define js-set-canvas-width! any/c)
(define js-canvas2d-canvas any/c)
(define js-canvas2d-direction any/c)
(define js-set-canvas2d-direction! any/c)
(define js-canvas2d-fill-style any/c)
(define js-set-canvas2d-fill-style! any/c)
(define js-canvas2d-filter any/c)
(define js-set-canvas2d-filter! any/c)
(define js-canvas2d-font any/c)
(define js-set-canvas2d-font! any/c)
(define js-canvas2d-global-alpha any/c)
(define js-set-canvas2d-global-alpha! any/c)
(define js-canvas2d-global-composite-operation any/c)
(define js-set-canvas2d-global-composite-operation! any/c)
(define js-canvas2d-image-smoothing-enabled any/c)
(define js-set-canvas2d-image-smoothing-enabled! any/c)
(define js-canvas2d-image-smoothing-quality any/c)
(define js-set-canvas2d-image-smoothing-quality! any/c)
(define js-canvas2d-line-cap any/c)
(define js-set-canvas2d-line-cap! any/c)
(define js-canvas2d-line-dash-offset any/c)
(define js-set-canvas2d-line-dash-offset! any/c)
(define js-canvas2d-line-join any/c)
(define js-set-canvas2d-line-join! any/c)
(define js-canvas2d-line-width any/c)
(define js-set-canvas2d-line-width! any/c)
(define js-canvas2d-miter-limit any/c)
(define js-set-canvas2d-miter-limit! any/c)
(define js-canvas2d-shadow-blur any/c)
(define js-set-canvas2d-shadow-blur! any/c)
(define js-canvas2d-shadow-color any/c)
(define js-set-canvas2d-shadow-color! any/c)
(define js-canvas2d-shadow-offset-x any/c)
(define js-set-canvas2d-shadow-offset-x! any/c)
(define js-canvas2d-shadow-offset-y any/c)
(define js-set-canvas2d-shadow-offset-y! any/c)
(define js-canvas2d-stroke-style any/c)
(define js-set-canvas2d-stroke-style! any/c)
(define js-canvas2d-text-align any/c)
(define js-set-canvas2d-text-align! any/c)
(define js-canvas2d-text-baseline any/c)
(define js-set-canvas2d-text-baseline! any/c)
(define js-canvas2d-text-rendering any/c)
(define js-set-canvas2d-text-rendering! any/c)
(define js-canvas2d-font-kerning any/c)
(define js-set-canvas2d-font-kerning! any/c)
(define js-canvas2d-font-stretch any/c)
(define js-set-canvas2d-font-stretch! any/c)
(define js-canvas2d-font-variant-caps any/c)
(define js-set-canvas2d-font-variant-caps! any/c)
(define js-canvas2d-font-variant-ligatures any/c)
(define js-set-canvas2d-font-variant-ligatures! any/c)
(define js-canvas2d-font-variant-numeric any/c)
(define js-set-canvas2d-font-variant-numeric! any/c)
(define js-canvas2d-letter-spacing any/c)
(define js-set-canvas2d-letter-spacing! any/c)
(define js-canvas2d-word-spacing any/c)
(define js-set-canvas2d-word-spacing! any/c)
(define js-canvas2d-arc any/c)
(define js-canvas2d-arc-to any/c)
(define js-canvas2d-begin-path any/c)
(define js-canvas2d-bezier-curve-to any/c)
(define js-canvas2d-clear-rect any/c)
(define js-canvas2d-clip any/c)
(define js-canvas2d-close-path any/c)
(define js-canvas2d-create-image-data any/c)
(define js-canvas2d-create-image-data-from any/c)
(define js-canvas2d-create-linear-gradient any/c)
(define js-canvas2d-create-pattern any/c)
(define js-canvas2d-create-radial-gradient any/c)
(define js-canvas2d-create-conic-gradient any/c)
(define js-canvas2d-draw-focus-if-needed! any/c)
(define js-canvas2d-draw-focus-if-needed-path! any/c)
(define js-canvas2d-draw-image any/c)
(define js-canvas2d-draw-image-5 any/c)
(define js-canvas2d-draw-image-9 any/c)
(define js-canvas2d-ellipse any/c)
(define js-canvas2d-fill any/c)
(define js-canvas2d-fill-rect any/c)
(define js-canvas2d-fill-text any/c)
(define js-canvas2d-get-image-data any/c)
(define js-canvas2d-get-line-dash any/c)
(define js-canvas2d-get-transform any/c)
(define js-canvas2d-is-point-in-path any/c)
(define js-canvas2d-is-point-in-stroke any/c)
(define js-canvas2d-line-to any/c)
(define js-canvas2d-measure-text any/c)
(define js-canvas2d-move-to any/c)
(define js-canvas2d-put-image-data any/c)
(define js-canvas2d-quadratic-curve-to any/c)
(define js-canvas2d-rect any/c)
(define js-canvas2d-reset any/c)
(define js-canvas2d-reset-transform any/c)
(define js-canvas2d-restore any/c)
(define js-canvas2d-rotate any/c)
(define js-canvas2d-round-rect any/c)
(define js-canvas2d-save any/c)
(define js-canvas2d-scale any/c)
(define js-canvas2d-set-line-dash any/c)
(define js-canvas2d-set-transform! any/c)
(define js-canvas2d-set-transform-matrix! any/c)
(define js-canvas2d-stroke any/c)
(define js-canvas2d-stroke-rect any/c)
(define js-canvas2d-stroke-text any/c)
(define js-canvas2d-transform any/c)
(define js-canvas2d-translate any/c)
