#lang racket/base

(require racket/contract/base)

;; Docs-only fake bindings for raw FFI Scribble links.
;; This file is generated by scribblings/generate-ffi-labels.rkt.
;; To refresh it, run:
;;   racket scribblings/generate-ffi-labels.rkt <input.ffi> <output-labels.rkt>
;;
;; Scribble requires these identifiers so that @racket[...] and
;; @racketblock examples can link to the low-level FFI entries.
(provide
  js-append-child!
  js-set-attribute!
  js-after!
  js-animate
  js-append!
  js-attach-shadow!
  js-before!
  js-closest
  js-computed-style-map
  js-get-animations
  js-get-attribute
  js-get-attribute-ns
  js-get-attribute-names
  js-get-attribute-node
  js-get-attribute-node-ns
  js-get-bounding-client-rect
  js-get-client-rects
  js-element-get-elements-by-class-name
  js-element-get-elements-by-tag-name
  js-element-get-elements-by-tag-name-ns
  js-has-attribute
  js-has-attribute-ns
  js-has-attributes
  js-has-pointer-capture
  js-insert-adjacent-element!
  js-insert-adjacent-html!
  js-insert-adjacent-text!
  js-matches
  js-prepend!
  js-element-query-selector
  js-element-query-selector-all
  js-release-pointer-capture!
  js-remove!
  js-remove-attribute!
  js-remove-attribute-ns!
  js-remove-attribute-node!
  js-replace-children!
  js-replace-with!
  js-request-fullscreen
  js-request-pointer-lock
  js-scroll!
  js-scroll-by!
  js-scroll-into-view!
  js-scroll-to!
  js-set-attribute-ns!
  js-set-attribute-node!
  js-set-attribute-node-ns!
  js-set-pointer-capture!
  js-toggle-attribute!
  (for-label (all-defined-out)))

(define js-append-child! any/c)
(define js-set-attribute! any/c)
(define js-after! any/c)
(define js-animate any/c)
(define js-append! any/c)
(define js-attach-shadow! any/c)
(define js-before! any/c)
(define js-closest any/c)
(define js-computed-style-map any/c)
(define js-get-animations any/c)
(define js-get-attribute any/c)
(define js-get-attribute-ns any/c)
(define js-get-attribute-names any/c)
(define js-get-attribute-node any/c)
(define js-get-attribute-node-ns any/c)
(define js-get-bounding-client-rect any/c)
(define js-get-client-rects any/c)
(define js-element-get-elements-by-class-name any/c)
(define js-element-get-elements-by-tag-name any/c)
(define js-element-get-elements-by-tag-name-ns any/c)
(define js-has-attribute any/c)
(define js-has-attribute-ns any/c)
(define js-has-attributes any/c)
(define js-has-pointer-capture any/c)
(define js-insert-adjacent-element! any/c)
(define js-insert-adjacent-html! any/c)
(define js-insert-adjacent-text! any/c)
(define js-matches any/c)
(define js-prepend! any/c)
(define js-element-query-selector any/c)
(define js-element-query-selector-all any/c)
(define js-release-pointer-capture! any/c)
(define js-remove! any/c)
(define js-remove-attribute! any/c)
(define js-remove-attribute-ns! any/c)
(define js-remove-attribute-node! any/c)
(define js-replace-children! any/c)
(define js-replace-with! any/c)
(define js-request-fullscreen any/c)
(define js-request-pointer-lock any/c)
(define js-scroll! any/c)
(define js-scroll-by! any/c)
(define js-scroll-into-view! any/c)
(define js-scroll-to! any/c)
(define js-set-attribute-ns! any/c)
(define js-set-attribute-node! any/c)
(define js-set-attribute-node-ns! any/c)
(define js-set-pointer-capture! any/c)
(define js-toggle-attribute! any/c)
