#lang racket/base

(require racket/file
         racket/list
         racket/path
         racket/port
         racket/string)

;; generate-web-easy-labels.rkt : -> void
;;   Generate docs-only fake bindings for identifiers documented in web-easy.scrbl.

(define here
  (or (current-load-relative-directory)
      (let ([rf (find-system-path 'run-file)])
        (and (path? rf) (path-only rf)))
      (current-directory)))
(define scrbl-path (build-path here "web-easy.scrbl"))
(define labels-path (build-path here "web-easy-labels.rkt"))

(define (unique-preserving-order xs)
  (for/fold ([seen (hash)]
             [out  '()]
             #:result (reverse out))
            ([x (in-list xs)])
    (if (hash-has-key? seen x)
        (values seen out)
        (values (hash-set seen x #t) (cons x out)))))

(define (extract-defproc-ids txt)
  (regexp-match* #px"@defproc\\[(?:#:[^\\]]+\\s+)*\\(([^][()\\s]+)"
                 txt
                 #:match-select cadr))

(define (extract-defthing-ids txt)
  (regexp-match* #px"@defthing\\[(?:#:[^\\]]+\\s+)*([^][()\\s]+)"
                 txt
                 #:match-select cadr))

(define (extract-defproc*-ids txt)
  (define blocks
    (regexp-match* #px"@defproc\\*\\[(?s:(.*?))\\]\\{"
                   txt
                   #:match-select cadr))
  (append-map
   (lambda (block)
     (regexp-match* #px"\\[\\(([^][()\\s]+)"
                    block
                    #:match-select cadr))
   blocks))

(define (id-string->symbol s)
  (string->symbol s))

(define (generate-labels-file! ids)
  (define out
    (call-with-output-string
      (lambda (port)
        (fprintf port "#lang racket/base\n\n")
        (fprintf port "(require racket/contract/base)\n\n")
        (fprintf port ";; This module provides docs-only fake bindings for Scribble linking.\n")
        (fprintf port ";; web-easy is written in #lang webracket, so its source bindings are not\n")
        (fprintf port ";; available to Scribble as ordinary Racket for-label bindings.\n")
        (fprintf port ";;\n")
        (fprintf port ";; This file is generated by scribblings/generate-web-easy-labels.rkt.\n")
        (fprintf port ";; To refresh it, run:\n")
        (fprintf port ";;   racket scribblings/generate-web-easy-labels.rkt\n")
        (fprintf port ";;\n")
        (fprintf port ";; To make links resolve correctly in web-easy.scrbl:\n")
        (fprintf port ";; 1. Require this module with for-label, and\n")
        (fprintf port ";; 2. Use @declare-exporting with the exact same module path.\n")
        (fprintf port ";;\n")
        (fprintf port ";; If these paths differ, Scribble will render plain symbols or bad links.\n")
        (fprintf port "(provide\n")
        (for ([id (in-list ids)])
          (fprintf port "  ~a\n" id))
        (fprintf port "  (for-label (all-defined-out)))\n\n")
        (for ([id (in-list ids)])
          (fprintf port "(define ~a any/c)\n" id)))))
  (display-to-file out labels-path #:exists 'replace))

(define (main)
  (define txt (file->string scrbl-path))
  (define ids
    (unique-preserving-order
     (map id-string->symbol
          (append (extract-defthing-ids txt)
                  (extract-defproc-ids txt)
                  (extract-defproc*-ids txt)))))
  (generate-labels-file! ids)
  (printf "Generated ~a with ~a identifiers.\n"
          (path->string labels-path)
          (length ids)))

(module+ main
  (main))
