#lang racket/base

(require racket/file
         racket/list
         racket/path
         racket/port
         racket/string)

;; generate-ffi-labels.rkt : path-string? path-string? -> void?
;;   Generate docs-only fake bindings for raw `js-*` names from an FFI file.

(define (unique-preserving-order xs)
  (for/fold ([seen (hash)]
             [out  '()]
             #:result (reverse out))
            ([x (in-list xs)])
    (if (hash-has-key? seen x)
        (values seen out)
        (values (hash-set seen x #t) (cons x out)))))

(define (extract-define-foreign-ids txt)
  (regexp-match* #px"\\(define-foreign\\s+([^)\\s]+)"
                 txt
                 #:match-select cadr))

(define (generate-labels-file! in-path out-path)
  (define in-path* (if (path? in-path) in-path (string->path in-path)))
  (define out-path* (if (path? out-path) out-path (string->path out-path)))
  (define ids
    (unique-preserving-order
     (map string->symbol
          (extract-define-foreign-ids
           (file->string in-path*)))))
  (define out
    (call-with-output-string
     (lambda (port)
       (fprintf port "#lang racket/base\n\n")
       (fprintf port "(require racket/contract/base)\n\n")
       (fprintf port ";; Docs-only fake bindings for raw FFI Scribble links.\n")
       (fprintf port ";; This file is generated by scribblings/generate-ffi-labels.rkt.\n")
       (fprintf port ";; To refresh it, run:\n")
       (fprintf port ";;   racket scribblings/generate-ffi-labels.rkt <input.ffi> <output-labels.rkt>\n")
       (fprintf port ";;\n")
       (fprintf port ";; Scribble requires these identifiers so that @racket[...] and\n")
       (fprintf port ";; @racketblock examples can link to the low-level FFI entries.\n")
       (fprintf port "(provide\n")
       (for ([id (in-list ids)])
         (fprintf port "  ~a\n" id))
       (fprintf port "  (for-label (all-defined-out)))\n\n")
       (for ([id (in-list ids)])
         (fprintf port "(define ~a any/c)\n" id)))))
  (display-to-file out out-path* #:exists 'replace)
  (printf "Generated ~a with ~a identifiers.\n"
          (path->string out-path*)
          (length ids)))

(module+ main
  (define args (current-command-line-arguments))
  (unless (= (vector-length args) 2)
    (error 'generate-ffi-labels.rkt
           "usage: racket scribblings/generate-ffi-labels.rkt <input.ffi> <output-labels.rkt>"))
  (define in-path (vector-ref args 0))
  (define out-path (vector-ref args 1))
  (generate-labels-file! in-path out-path))
