#lang racket/base

(require racket/file
         racket/list
         racket/path
         racket/port
         racket/set
         racket/string
         racket/system)

;; generate-primitives-labels.rkt : -> void
;;   Generate docs-only fake bindings for implemented primitives.

(define here
  (or (current-load-relative-directory)
      (let ([rf (find-system-path 'run-file)])
        (and (path? rf) (path-only rf)))
      (current-directory)))

(define webracket-path (build-path here ".." "webracket.rkt"))
(define labels-path (build-path here "primitives-labels.rkt"))

(define (unique-preserving-order syms)
  (for/fold ([seen (seteq)]
             [out  '()]
             #:result (reverse out))
            ([s (in-list syms)])
    (if (set-member? seen s)
        (values seen out)
        (values (set-add seen s) (cons s out)))))

(define (implemented-primitives)
  (define racket-exe
    (or (find-executable-path "racket")
        (error 'generate-primitives-labels "could not find racket executable in PATH")))
  (define-values (proc stdout stdin stderr)
    (subprocess #f #f #f racket-exe webracket-path "--list-primitives"))
  (close-output-port stdin)
  (define out-text (port->string stdout))
  (define err-text (port->string stderr))
  (subprocess-wait proc)
  (unless (zero? (subprocess-status proc))
    (error 'generate-primitives-labels
           "failed to list primitives via CLI:\n~a"
           err-text))
  (define lines (string-split out-text "\n" #:trim? #t))
  (define names
    (for/list ([line (in-list lines)]
               #:do [(define trimmed (string-trim line))]
               #:when (not (string=? trimmed "")))
      (string->symbol trimmed)))
  (unless (pair? names)
    (error 'generate-primitives-labels "webracket --list-primitives returned no primitive names"))
  (unique-preserving-order names))

(define (emit-labels-file! syms)
  (define out
    (call-with-output-string
      (lambda (port)
        (fprintf port "#lang racket/base\n\n")
        (fprintf port "(require racket/contract/base)\n\n")
        (fprintf port ";; This module provides docs-only fake bindings for implemented primitives.\n")
        (fprintf port ";;\n")
        (fprintf port ";; It is generated by scribblings/generate-primitives-labels.rkt.\n")
        (fprintf port ";; To refresh it, run:\n")
        (fprintf port ";;   racket scribblings/generate-primitives-labels.rkt\n\n")
        (fprintf port "(define implemented-primitives\n")
        (fprintf port "  '(\n")
        (for ([s (in-list syms)])
          (fprintf port "    ~a\n" s))
        (fprintf port "    ))\n\n")
        (fprintf port "(provide\n")
        (fprintf port "  implemented-primitives\n")
        (for ([s (in-list syms)])
          (fprintf port "  ~a\n" s))
        (fprintf port "  (for-label (all-defined-out)))\n\n")
        (for ([s (in-list syms)])
          (fprintf port "(define ~a any/c)\n" s)))))
  (display-to-file out labels-path #:exists 'replace))

(module+ main
  (define syms (implemented-primitives))
  (emit-labels-file! syms)
  (printf "Generated ~a with ~a implemented primitives.\n"
          (path->string labels-path)
          (length syms)))
