#lang racket/base

(require racket/file
         racket/list
         racket/path
         racket/port
         racket/set
         racket/string)

;; generate-special-forms-index.rkt : -> void
;;   Generate an index of documented special forms for Scribble.

(define here
  (or (current-load-relative-directory)
      (let ([rf (find-system-path 'run-file)])
        (and (path? rf) (path-only rf)))
      (current-directory)))

(define core-path  (build-path here ".." "core.rkt"))
(define index-path (build-path here "special-forms-index.rkt"))

(define special-form-order
  '(if
    cond
    case
    and
    or
    when
    unless
    lambda
    λ
    case-lambda
    let
    let*
    letrec
    let-values
    let*-values
    letrec-values
    local
    define
    define-values
    begin
    begin0
    set!
    set!-values
    for
    for*
    for/list
    for*/list
    for/vector
    for*/vector
    for/sum
    for*/sum
    for/fold
    for*/fold
    for/or
    for*/or
    for/and
    for*/and
    for/first
    for*/first
    quasiquote
    unquote
    unquote-splicing
    with-handlers
    block
    require-lib
    include-lib
    #%app
    #%module-begin))

(define target-set (list->seteq special-form-order))

(define (drop-lang-line s)
  (define lines (string-split s "\n" #:trim? #f))
  (if (and (pair? lines)
           (regexp-match? #px"^#lang\\b" (car lines)))
      (string-join (cdr lines) "\n")
      s))

(define (read-all-datums text)
  (define in (open-input-string text))
  (let loop ([out '()])
    (define v (read in))
    (if (eof-object? v)
        (reverse out)
        (loop (cons v out)))))

(define (extract-provide-ids spec)
  (cond
    [(symbol? spec)
     (if (set-member? target-set spec) (list spec) '())]
    [(and (pair? spec) (eq? (car spec) 'rename-out))
     (append-map
      (lambda (entry)
        (cond
          [(and (list? entry) (= (length entry) 2) (symbol? (second entry)))
           (if (set-member? target-set (second entry))
               (list (second entry))
               '())]
          [else '()]))
      (cdr spec))]
    [else '()]))

(define (core-provided-special-forms)
  (define text (drop-lang-line (file->string core-path)))
  (define datums (read-all-datums text))
  (for/fold ([ids '()]) ([d (in-list datums)])
    (if (and (pair? d) (eq? (car d) 'provide))
        (append ids (append-map extract-provide-ids (cdr d)))
        ids)))

(define (ordered-special-forms)
  (define provided (list->seteq (core-provided-special-forms)))
  (for/list ([name (in-list special-form-order)]
             #:when (or (set-member? provided name)
                        (memq name '(if begin begin0 set! with-handlers))))
    name))

(define (emit-index-file! names)
  (define out
    (call-with-output-string
      (lambda (port)
        (fprintf port "#lang racket/base\n\n")
        (fprintf port ";; This file is generated by scribblings/generate-special-forms-index.rkt.\n")
        (fprintf port ";; To refresh it, run:\n")
        (fprintf port ";;   racket scribblings/generate-special-forms-index.rkt\n\n")
        (fprintf port "(provide documented-special-forms)\n\n")
        (fprintf port "(define documented-special-forms\n")
        (fprintf port "  '(\n")
        (for ([name (in-list names)])
          (fprintf port "    ~a\n" name))
        (fprintf port "    ))\n"))))
  (display-to-file out index-path #:exists 'replace))

(module+ main
  (define names (ordered-special-forms))
  (emit-index-file! names)
  (printf "Generated ~a with ~a special forms.\n"
          (path->string index-path)
          (length names)))
