#lang racket/base

(require racket/contract/base)

;; This module provides docs-only fake bindings for implemented primitives.
;;
;; It is generated by scribblings/generate-primitives-labels.rkt.
;; To refresh it, run:
;;   racket scribblings/generate-primitives-labels.rkt

(define implemented-primitives
  '(
    *
    +
    -
    ->fl
    /
    <
    <=
    =
    >
    >=
    abs
    acos
    acosh
    add-between
    add1
    alt-reverse
    andmap
    append
    append*
    append-map
    apply
    argmax
    argmin
    arithmetic-shift
    arity-at-least-value
    arity-at-least?
    asin
    asinh
    assf
    assoc
    assq
    assv
    assw
    atan
    atanh
    bitwise-and
    bitwise-bit-field
    bitwise-bit-set?
    bitwise-first-bit-set
    bitwise-ior
    bitwise-not
    bitwise-xor
    boolean=?
    boolean?
    box
    box-immutable
    box?
    boxed
    boxed?
    build-list
    build-string
    build-vector
    byte-ready?
    byte?
    bytes
    bytes->immutable-bytes
    bytes->list
    bytes->path
    bytes->string/latin-1
    bytes->string/utf-8
    bytes-append
    bytes-append*
    bytes-copy
    bytes-copy!
    bytes-fill!
    bytes-join
    bytes-length
    bytes-ref
    bytes-set!
    bytes-utf-8-length
    bytes<?
    bytes=?
    bytes>?
    bytes?
    caaaar
    caaadr
    caaar
    caadar
    caaddr
    caadr
    caar
    cadaar
    cadadr
    cadar
    caddar
    cadddr
    caddr
    cadr
    call-with-exception-handler
    call-with-input-file
    call-with-input-file*
    call-with-output-file
    call-with-output-file*
    call-with-output-string
    call-with-values
    car
    cartesian-product
    catch
    catch*
    cdaaar
    cdaadr
    cdaar
    cdadar
    cdaddr
    cdadr
    cdar
    cddaar
    cddadr
    cddar
    cdddar
    cddddr
    cdddr
    cddr
    cdr
    ceiling
    char->integer
    char-alphabetic?
    char-blank?
    char-ci<=?
    char-ci<?
    char-ci=?
    char-ci>=?
    char-ci>?
    char-downcase
    char-extended-pictographic?
    char-foldcase
    char-general-category
    char-grapheme-break-property
    char-grapheme-step
    char-graphic?
    char-iso-control?
    char-lower-case?
    char-numeric?
    char-punctuation?
    char-ready?
    char-symbolic?
    char-title-case?
    char-titlecase
    char-upcase
    char-upper-case?
    char-utf-8-length
    char-whitespace?
    char<=?
    char<?
    char=?
    char>=?
    char>?
    char?
    check-list
    check-mlist
    check-naturals
    check-range
    check-range-generic
    check-string
    cons
    cons?
    copy-file
    copy-directory/files
    correlated->datum
    correlated-column
    correlated-e
    correlated-line
    correlated-position
    correlated-property
    correlated-property-symbol-keys
    correlated-source
    correlated-span
    correlated?
    cos
    cosh
    count
    current-continuation-marks
    current-inspector
    custom-write-accessor
    custom-write?
    datum->correlated
    datum->syntax
    degrees->radians
    delete-directory
    delete-directory/files
    delete-file
    directory-exists?
    directory-list
    display-lines-to-file
    display-to-file
    double-flonum?
    drop
    drop-common-prefix
    drop-right
    dropf
    dropf-right
    eighth
    eleventh
    empty?
    eof-object?
    eq-hash-code
    eq?
    equal-always?
    equal-hash-code
    equal?
    eqv-hash-code
    eqv?
    even?
    exact->inexact
    exact-ceiling
    exact-floor
    exact-integer?
    exact-nonnegative-integer?
    exact-positive-integer?
    exact-round
    exact-truncate
    exact?
    exn
    exn-continuation-marks
    exn-message
    exn:fail
    exn:fail:contract
    exn:fail:contract:arity
    exn:fail:contract:arity?
    exn:fail:contract:divide-by-zero
    exn:fail:contract:divide-by-zero?
    exn:fail:contract:non-fixnum-result
    exn:fail:contract:non-fixnum-result?
    exn:fail:contract:variable
    exn:fail:contract:variable-id
    exn:fail:contract:variable?
    exn:fail:contract?
    exn:fail:read
    exn:fail:read-srclocs
    exn:fail:read:eof
    exn:fail:read:eof?
    exn:fail:read:non-char
    exn:fail:read:non-char?
    exn:fail:read?
    exn:fail:syntax
    exn:fail:syntax-exprs
    exn:fail:syntax:missing-module
    exn:fail:syntax:missing-module-path
    exn:fail:syntax:missing-module?
    exn:fail:syntax:unbound
    exn:fail:syntax:unbound?
    exn:fail:syntax?
    exn:fail?
    exn?
    exp
    expt
    external-number->flonum
    external-string->string
    external?
    false?
    fasl->s-exp
    fifteenth
    file->bytes
    file->bytes-lines
    file->lines
    file->string
    file-exists?
    file-or-directory-identity
    file-or-directory-modify-seconds
    file-or-directory-permissions
    file-or-directory-stat
    file-or-directory-type
    file-size
    fifth
    filter
    filter-map
    filter-not
    findf
    first
    fixnum-for-every-system?
    fixnum?
    fl*
    fl+
    fl-
    fl->exact-integer
    fl->fx
    fl/
    fl<
    fl<=
    fl=
    fl>
    fl>=
    flabs
    flacos
    flacosh
    flasin
    flasinh
    flatan
    flatanh
    flatten
    flbit-field
    flceiling
    flcos
    flcosh
    flexp
    flexpt
    flfloor
    fllog
    flmax
    flmin
    floating-point-bytes->real
    flonum?
    floor
    flrandom
    flround
    flsin
    flsingle
    flsinh
    flsqrt
    fltan
    fltanh
    fltruncate
    foldl
    foldr
    for-each
    fourteenth
    fourth
    fx*
    fx*/wraparound
    fx+
    fx+/wraparound
    fx-
    fx-/wraparound
    fx->fl
    fx<
    fx<=
    fx=
    fx>
    fx>=
    fxabs
    fxand
    fxior
    fxlshift
    fxlshift/wraparound
    fxmax
    fxmin
    fxmodulo
    fxnot
    fxpopcount
    fxpopcount16
    fxpopcount32
    fxquotient
    fxremainder
    fxrshift
    fxrshift/logical
    fxxor
    fxzero?
    gcd
    gensym
    get-output-bytes
    get-output-string
    group-by
    hash->list
    hash-clear!
    hash-count
    hash-empty?
    hash-eq?
    hash-equal-always?
    hash-equal?
    hash-eqv?
    hash-filter
    hash-filter-keys
    hash-filter-values
    hash-for-each
    hash-has-key?
    hash-keys
    hash-map
    hash-map/copy
    hash-ref
    hash-ref!
    hash-remove!
    hash-set!
    hash-update!
    hash-values
    hash?
    identifier?
    immutable-box?
    immutable-bytes?
    immutable-hash?
    immutable-string?
    immutable-vector?
    immutable?
    inclusive-range
    inclusive-range-proc
    index-of
    index-where
    indexes-of
    indexes-where
    inexact->exact
    inexact-real?
    inexact?
    infinite?
    input-port?
    instance-data
    instance-name
    instance-set-variable-value!
    instance-unset-variable!
    instance-variable-box
    instance-variable-names
    instance-variable-value
    instance?
    instantiate-linklet
    integer->char
    integer-length
    integer-sqrt
    integer-sqrt/remainder
    integer?
    js-log
    keyword->immutable-string
    keyword->string
    keyword<?
    keyword?
    last
    last-pair
    lcm
    length
    linklet-export-variables
    linklet-import-variables
    linklet-name
    linklet?
    list
    list*
    list->bytes
    list->string
    list->vector
    list-prefix?
    list-ref
    list-set
    list-tail
    list-update
    list?
    log
    make-bytes
    make-compiled-linklet
    make-empty-hash
    make-empty-hashalw
    make-empty-hasheq
    make-empty-hasheqv
    make-empty-namespace
    make-exn
    make-exn:fail
    make-exn:fail:contract
    make-exn:fail:contract:arity
    make-exn:fail:contract:divide-by-zero
    make-exn:fail:contract:non-fixnum-result
    make-exn:fail:contract:variable
    make-exn:fail:read
    make-exn:fail:read:eof
    make-exn:fail:read:non-char
    make-exn:fail:syntax
    make-exn:fail:syntax:missing-module
    make-exn:fail:syntax:unbound
    make-hash
    make-hashalw
    make-hasheq
    make-hasheqv
    make-input-port
    make-instance
    make-list
    make-directory
    make-directory*
    make-parent-directory*
    make-temporary-directory
    make-temporary-directory*
    make-temporary-file
    make-temporary-file*
    make-srcloc
    make-string
    make-struct-field-accessor
    make-struct-field-mutator
    make-struct-type
    make-struct-type-property
    make-vector
    make-void
    make-weak-hash
    make-weak-hashalw
    make-weak-hasheq
    make-weak-hasheqv
    map
    match:error
    max
    mcar
    mcdr
    mcons
    member
    memf
    memq
    memv
    memw
    min
    modulo
    most-negative-fixnum
    most-positive-fixnum
    mpair?
    mutable-box?
    mutable-bytes?
    mutable-hash-iterate-first
    mutable-hash-iterate-key
    mutable-hash-iterate-key+value
    mutable-hash-iterate-next
    mutable-hash-iterate-pair
    mutable-hash-iterate-value
    mutable-hash?
    mutable-string?
    mutable-vector?
    namespace-set-variable-value!
    namespace-undefine-variable!
    namespace-variable-value-simple
    namespace?
    nan?
    natural?
    negative-integer?
    negative?
    newline
    ninth
    non-empty-string?
    nonnegative-integer?
    nonpositive-integer?
    not
    null?
    number->string
    number?
    object-name
    odd?
    open-input-bytes
    open-input-file
    open-input-string
    open-output-bytes
    open-output-file
    open-output-string
    order-of-magnitude
    ormap
    output-port?
    pair?
    partition
    path->bytes
    path->string
    path-for-some-system?
    path-string?
    path?
    peek-byte
    peek-bytes
    peek-bytes!
    peek-bytes-avail!
    peek-bytes-avail!*
    peek-char
    peek-string
    peek-string!
    permutations
    port-count-lines!
    port-counts-lines?
    port-next-location
    port?
    positive-integer?
    positive?
    primitive-closure?
    primitive-result-arity
    primitive?
    procedure->external
    procedure-arity
    procedure-arity-includes?
    procedure-arity-mask
    procedure-rename
    procedure?
    progress-evt?
    quotient
    quotient/remainder
    radians->degrees
    raise
    raise-read-eof-error
    raise-read-error
    raise-unbound-variable-reference
    random
    range
    range-proc
    read-byte
    read-bytes
    read-bytes!
    read-bytes-avail!
    read-bytes-avail!*
    read-char
    read-line
    read-string
    read-string!
    real->double-flonum
    real->floating-point-bytes
    real?
    remainder
    remf
    remf*
    remove
    remove*
    remq
    remq*
    remv
    remv*
    remw
    remw*
    rename-file-or-directory
    rest
    reverse
    round
    s-exp->fasl
    second
    set-box!
    set-boxed!
    set-mcar!
    set-mcdr!
    seventh
    sgn
    shuffle
    sin
    single-flonum-available?
    single-flonum?
    sinh
    sixth
    sort
    split-at
    split-at-right
    split-common-prefix
    splitf-at
    splitf-at-right
    sqr
    sqrt
    srcloc
    srcloc->string
    srcloc-column
    srcloc-line
    srcloc-position
    srcloc-source
    srcloc-span
    srcloc?
    string
    string->bytes/utf-8
    string->immutable-string
    string->keyword
    string->list
    string->number
    string->symbol
    string->uninterned-symbol
    string-append
    string-append*
    string-append-immutable
    string-ci<=?
    string-ci<?
    string-ci=?
    string-ci>=?
    string-ci>?
    string-contains?
    string-copy
    string-copy!
    string-downcase
    string-drop
    string-drop-right
    string-fill!
    string-find
    string-foldcase
    string-join
    string-length
    string-port?
    string-prefix?
    string-ref
    string-replace
    string-set!
    string-split
    string-suffix?
    string-take
    string-take-right
    string-titlecase
    string-trim
    string-trim-left
    string-trim-right
    string-upcase
    string-utf-8-length
    string<=?
    string<?
    string=?
    string>=?
    string>?
    string?
    struct->list
    struct->vector
    struct-accessor-procedure?
    struct-constructor-procedure?
    struct-mutator-procedure?
    struct-predicate-procedure?
    struct-type-authentic?
    struct-type-property-accessor-procedure?
    struct-type-property-predicate-procedure?
    struct-type-property?
    struct-type?
    struct?
    sub1
    subbytes
    substring
    symbol->immutable-string
    symbol->string
    symbol-interned?
    symbol<?
    symbol=?
    symbol?
    syntax->datum
    syntax->list
    syntax-column
    syntax-e
    syntax-line
    syntax-position
    syntax-source
    syntax-span
    syntax-srcloc
    syntax-srclocs
    syntax?
    system-big-endian?
    take
    take-common-prefix
    take-right
    takef
    takef-right
    tan
    tanh
    tenth
    third
    thirteenth
    truncate
    twelfth
    unbox
    unboxed
    unquoted-printing-string
    unquoted-printing-string-value
    unquoted-printing-string?
    unsafe-bytes-length
    unsafe-bytes-ref
    unsafe-bytes-set!
    unsafe-car
    unsafe-cdr
    unsafe-fl/
    unsafe-flabs
    unsafe-flacos
    unsafe-flacosh
    unsafe-flasin
    unsafe-flasinh
    unsafe-flatan
    unsafe-flatanh
    unsafe-flceiling
    unsafe-flcos
    unsafe-flcosh
    unsafe-flexp
    unsafe-flexpt
    unsafe-flfloor
    unsafe-fllog
    unsafe-flmax
    unsafe-flmin
    unsafe-flrandom
    unsafe-flround
    unsafe-flsin
    unsafe-flsingle
    unsafe-flsinh
    unsafe-flsqrt
    unsafe-fltan
    unsafe-fltanh
    unsafe-fltruncate
    unsafe-fx*
    unsafe-fx*/wraparound
    unsafe-fx+
    unsafe-fx+/wraparound
    unsafe-fx-
    unsafe-fx-/wraparound
    unsafe-fx<
    unsafe-fx<=
    unsafe-fx=
    unsafe-fx>
    unsafe-fx>=
    unsafe-fxabs
    unsafe-fxand
    unsafe-fxior
    unsafe-fxlshift
    unsafe-fxlshift/wraparound
    unsafe-fxmax
    unsafe-fxmin
    unsafe-fxmodulo
    unsafe-fxnot
    unsafe-fxpopcount
    unsafe-fxpopcount16
    unsafe-fxpopcount32
    unsafe-fxquotient
    unsafe-fxremainder
    unsafe-fxrshift
    unsafe-fxrshift/logical
    unsafe-fxxor
    unsafe-string-length
    unsafe-struct-ref
    unsafe-struct-set!
    unsafe-vector*-length
    unsafe-vector*-ref
    unsafe-vector*-set!
    unsafe-vector-length
    unsafe-vector-ref
    unsafe-vector-set!
    values
    variable-reference-constant?
    variable-reference-from-unsafe?
    vector
    vector->immutable-vector
    vector->list
    vector->values
    vector-append
    vector-argmax
    vector-argmin
    vector-copy
    vector-copy!
    vector-count
    vector-drop
    vector-drop-right
    vector-empty?
    vector-extend
    vector-fill!
    vector-filter
    vector-filter-not
    vector-immutable
    vector-length
    vector-map
    vector-map!
    vector-member
    vector-memq
    vector-memv
    vector-ref
    vector-set!
    vector-set/copy
    vector-sort
    vector-sort!
    vector-split-at
    vector-split-at-right
    vector-take
    vector-take-right
    vector?
    void
    void?
    webracket-vfs-write-file
    with-input-from-file
    with-output-to-file
    write-byte
    write-bytes
    write-char
    write-string
    xor
    zero?
    ))

(provide
  implemented-primitives
  *
  +
  -
  ->fl
  /
  <
  <=
  =
  >
  >=
  abs
  acos
  acosh
  add-between
  add1
  alt-reverse
  andmap
  append
  append*
  append-map
  apply
  argmax
  argmin
  arithmetic-shift
  arity-at-least-value
  arity-at-least?
  asin
  asinh
  assf
  assoc
  assq
  assv
  assw
  atan
  atanh
  bitwise-and
  bitwise-bit-field
  bitwise-bit-set?
  bitwise-first-bit-set
  bitwise-ior
  bitwise-not
  bitwise-xor
  boolean=?
  boolean?
  box
  box-immutable
  box?
  boxed
  boxed?
  build-list
  build-string
  build-vector
  byte-ready?
  byte?
  bytes
  bytes->immutable-bytes
  bytes->list
  bytes->path
  bytes->string/latin-1
  bytes->string/utf-8
  bytes-append
  bytes-append*
  bytes-copy
  bytes-copy!
  bytes-fill!
  bytes-join
  bytes-length
  bytes-ref
  bytes-set!
  bytes-utf-8-length
  bytes<?
  bytes=?
  bytes>?
  bytes?
  caaaar
  caaadr
  caaar
  caadar
  caaddr
  caadr
  caar
  cadaar
  cadadr
  cadar
  caddar
  cadddr
  caddr
  cadr
  call-with-exception-handler
  call-with-input-file
  call-with-input-file*
  call-with-output-file
  call-with-output-file*
  call-with-output-string
  call-with-values
  car
  cartesian-product
  catch
  catch*
  cdaaar
  cdaadr
  cdaar
  cdadar
  cdaddr
  cdadr
  cdar
  cddaar
  cddadr
  cddar
  cdddar
  cddddr
  cdddr
  cddr
  cdr
  ceiling
  char->integer
  char-alphabetic?
  char-blank?
  char-ci<=?
  char-ci<?
  char-ci=?
  char-ci>=?
  char-ci>?
  char-downcase
  char-extended-pictographic?
  char-foldcase
  char-general-category
  char-grapheme-break-property
  char-grapheme-step
  char-graphic?
  char-iso-control?
  char-lower-case?
  char-numeric?
  char-punctuation?
  char-ready?
  char-symbolic?
  char-title-case?
  char-titlecase
  char-upcase
  char-upper-case?
  char-utf-8-length
  char-whitespace?
  char<=?
  char<?
  char=?
  char>=?
  char>?
  char?
  check-list
  check-mlist
  check-naturals
  check-range
  check-range-generic
  check-string
  cons
  cons?
  copy-file
  copy-directory/files
  correlated->datum
  correlated-column
  correlated-e
  correlated-line
  correlated-position
  correlated-property
  correlated-property-symbol-keys
  correlated-source
  correlated-span
  correlated?
  cos
  cosh
  count
  current-continuation-marks
  current-inspector
  custom-write-accessor
  custom-write?
  datum->correlated
  datum->syntax
  degrees->radians
  delete-directory
  delete-directory/files
  delete-file
  directory-exists?
  directory-list
  display-lines-to-file
  display-to-file
  double-flonum?
  drop
  drop-common-prefix
  drop-right
  dropf
  dropf-right
  eighth
  eleventh
  empty?
  eof-object?
  eq-hash-code
  eq?
  equal-always?
  equal-hash-code
  equal?
  eqv-hash-code
  eqv?
  even?
  exact->inexact
  exact-ceiling
  exact-floor
  exact-integer?
  exact-nonnegative-integer?
  exact-positive-integer?
  exact-round
  exact-truncate
  exact?
  exn
  exn-continuation-marks
  exn-message
  exn:fail
  exn:fail:contract
  exn:fail:contract:arity
  exn:fail:contract:arity?
  exn:fail:contract:divide-by-zero
  exn:fail:contract:divide-by-zero?
  exn:fail:contract:non-fixnum-result
  exn:fail:contract:non-fixnum-result?
  exn:fail:contract:variable
  exn:fail:contract:variable-id
  exn:fail:contract:variable?
  exn:fail:contract?
  exn:fail:read
  exn:fail:read-srclocs
  exn:fail:read:eof
  exn:fail:read:eof?
  exn:fail:read:non-char
  exn:fail:read:non-char?
  exn:fail:read?
  exn:fail:syntax
  exn:fail:syntax-exprs
  exn:fail:syntax:missing-module
  exn:fail:syntax:missing-module-path
  exn:fail:syntax:missing-module?
  exn:fail:syntax:unbound
  exn:fail:syntax:unbound?
  exn:fail:syntax?
  exn:fail?
  exn?
  exp
  expt
  external-number->flonum
  external-string->string
  external?
  false?
  fasl->s-exp
  fifteenth
  file->bytes
  file->bytes-lines
  file->lines
  file->string
  file-exists?
  file-or-directory-identity
  file-or-directory-modify-seconds
  file-or-directory-permissions
  file-or-directory-stat
  file-or-directory-type
  file-size
  fifth
  filter
  filter-map
  filter-not
  findf
  first
  fixnum-for-every-system?
  fixnum?
  fl*
  fl+
  fl-
  fl->exact-integer
  fl->fx
  fl/
  fl<
  fl<=
  fl=
  fl>
  fl>=
  flabs
  flacos
  flacosh
  flasin
  flasinh
  flatan
  flatanh
  flatten
  flbit-field
  flceiling
  flcos
  flcosh
  flexp
  flexpt
  flfloor
  fllog
  flmax
  flmin
  floating-point-bytes->real
  flonum?
  floor
  flrandom
  flround
  flsin
  flsingle
  flsinh
  flsqrt
  fltan
  fltanh
  fltruncate
  foldl
  foldr
  for-each
  fourteenth
  fourth
  fx*
  fx*/wraparound
  fx+
  fx+/wraparound
  fx-
  fx-/wraparound
  fx->fl
  fx<
  fx<=
  fx=
  fx>
  fx>=
  fxabs
  fxand
  fxior
  fxlshift
  fxlshift/wraparound
  fxmax
  fxmin
  fxmodulo
  fxnot
  fxpopcount
  fxpopcount16
  fxpopcount32
  fxquotient
  fxremainder
  fxrshift
  fxrshift/logical
  fxxor
  fxzero?
  gcd
  gensym
  get-output-bytes
  get-output-string
  group-by
  hash->list
  hash-clear!
  hash-count
  hash-empty?
  hash-eq?
  hash-equal-always?
  hash-equal?
  hash-eqv?
  hash-filter
  hash-filter-keys
  hash-filter-values
  hash-for-each
  hash-has-key?
  hash-keys
  hash-map
  hash-map/copy
  hash-ref
  hash-ref!
  hash-remove!
  hash-set!
  hash-update!
  hash-values
  hash?
  identifier?
  immutable-box?
  immutable-bytes?
  immutable-hash?
  immutable-string?
  immutable-vector?
  immutable?
  inclusive-range
  inclusive-range-proc
  index-of
  index-where
  indexes-of
  indexes-where
  inexact->exact
  inexact-real?
  inexact?
  infinite?
  input-port?
  instance-data
  instance-name
  instance-set-variable-value!
  instance-unset-variable!
  instance-variable-box
  instance-variable-names
  instance-variable-value
  instance?
  instantiate-linklet
  integer->char
  integer-length
  integer-sqrt
  integer-sqrt/remainder
  integer?
  js-log
  keyword->immutable-string
  keyword->string
  keyword<?
  keyword?
  last
  last-pair
  lcm
  length
  linklet-export-variables
  linklet-import-variables
  linklet-name
  linklet?
  list
  list*
  list->bytes
  list->string
  list->vector
  list-prefix?
  list-ref
  list-set
  list-tail
  list-update
  list?
  log
  make-bytes
  make-compiled-linklet
  make-empty-hash
  make-empty-hashalw
  make-empty-hasheq
  make-empty-hasheqv
  make-empty-namespace
  make-exn
  make-exn:fail
  make-exn:fail:contract
  make-exn:fail:contract:arity
  make-exn:fail:contract:divide-by-zero
  make-exn:fail:contract:non-fixnum-result
  make-exn:fail:contract:variable
  make-exn:fail:read
  make-exn:fail:read:eof
  make-exn:fail:read:non-char
  make-exn:fail:syntax
  make-exn:fail:syntax:missing-module
  make-exn:fail:syntax:unbound
  make-hash
  make-hashalw
  make-hasheq
  make-hasheqv
  make-input-port
  make-instance
  make-list
  make-directory
  make-directory*
  make-parent-directory*
  make-temporary-directory
  make-temporary-directory*
  make-temporary-file
  make-temporary-file*
  make-srcloc
  make-string
  make-struct-field-accessor
  make-struct-field-mutator
  make-struct-type
  make-struct-type-property
  make-vector
  make-void
  make-weak-hash
  make-weak-hashalw
  make-weak-hasheq
  make-weak-hasheqv
  map
  match:error
  max
  mcar
  mcdr
  mcons
  member
  memf
  memq
  memv
  memw
  min
  modulo
  most-negative-fixnum
  most-positive-fixnum
  mpair?
  mutable-box?
  mutable-bytes?
  mutable-hash-iterate-first
  mutable-hash-iterate-key
  mutable-hash-iterate-key+value
  mutable-hash-iterate-next
  mutable-hash-iterate-pair
  mutable-hash-iterate-value
  mutable-hash?
  mutable-string?
  mutable-vector?
  namespace-set-variable-value!
  namespace-undefine-variable!
  namespace-variable-value-simple
  namespace?
  nan?
  natural?
  negative-integer?
  negative?
  newline
  ninth
  non-empty-string?
  nonnegative-integer?
  nonpositive-integer?
  not
  null?
  number->string
  number?
  object-name
  odd?
  open-input-bytes
  open-input-file
  open-input-string
  open-output-bytes
  open-output-file
  open-output-string
  order-of-magnitude
  ormap
  output-port?
  pair?
  partition
  path->bytes
  path->string
  path-for-some-system?
  path-string?
  path?
  peek-byte
  peek-bytes
  peek-bytes!
  peek-bytes-avail!
  peek-bytes-avail!*
  peek-char
  peek-string
  peek-string!
  permutations
  port-count-lines!
  port-counts-lines?
  port-next-location
  port?
  positive-integer?
  positive?
  primitive-closure?
  primitive-result-arity
  primitive?
  procedure->external
  procedure-arity
  procedure-arity-includes?
  procedure-arity-mask
  procedure-rename
  procedure?
  progress-evt?
  quotient
  quotient/remainder
  radians->degrees
  raise
  raise-read-eof-error
  raise-read-error
  raise-unbound-variable-reference
  random
  range
  range-proc
  read-byte
  read-bytes
  read-bytes!
  read-bytes-avail!
  read-bytes-avail!*
  read-char
  read-line
  read-string
  read-string!
  real->double-flonum
  real->floating-point-bytes
  real?
  remainder
  remf
  remf*
  remove
  remove*
  remq
  remq*
  remv
  remv*
  remw
  remw*
  rename-file-or-directory
  rest
  reverse
  round
  s-exp->fasl
  second
  set-box!
  set-boxed!
  set-mcar!
  set-mcdr!
  seventh
  sgn
  shuffle
  sin
  single-flonum-available?
  single-flonum?
  sinh
  sixth
  sort
  split-at
  split-at-right
  split-common-prefix
  splitf-at
  splitf-at-right
  sqr
  sqrt
  srcloc
  srcloc->string
  srcloc-column
  srcloc-line
  srcloc-position
  srcloc-source
  srcloc-span
  srcloc?
  string
  string->bytes/utf-8
  string->immutable-string
  string->keyword
  string->list
  string->number
  string->symbol
  string->uninterned-symbol
  string-append
  string-append*
  string-append-immutable
  string-ci<=?
  string-ci<?
  string-ci=?
  string-ci>=?
  string-ci>?
  string-contains?
  string-copy
  string-copy!
  string-downcase
  string-drop
  string-drop-right
  string-fill!
  string-find
  string-foldcase
  string-join
  string-length
  string-port?
  string-prefix?
  string-ref
  string-replace
  string-set!
  string-split
  string-suffix?
  string-take
  string-take-right
  string-titlecase
  string-trim
  string-trim-left
  string-trim-right
  string-upcase
  string-utf-8-length
  string<=?
  string<?
  string=?
  string>=?
  string>?
  string?
  struct->list
  struct->vector
  struct-accessor-procedure?
  struct-constructor-procedure?
  struct-mutator-procedure?
  struct-predicate-procedure?
  struct-type-authentic?
  struct-type-property-accessor-procedure?
  struct-type-property-predicate-procedure?
  struct-type-property?
  struct-type?
  struct?
  sub1
  subbytes
  substring
  symbol->immutable-string
  symbol->string
  symbol-interned?
  symbol<?
  symbol=?
  symbol?
  syntax->datum
  syntax->list
  syntax-column
  syntax-e
  syntax-line
  syntax-position
  syntax-source
  syntax-span
  syntax-srcloc
  syntax-srclocs
  syntax?
  system-big-endian?
  take
  take-common-prefix
  take-right
  takef
  takef-right
  tan
  tanh
  tenth
  third
  thirteenth
  truncate
  twelfth
  unbox
  unboxed
  unquoted-printing-string
  unquoted-printing-string-value
  unquoted-printing-string?
  unsafe-bytes-length
  unsafe-bytes-ref
  unsafe-bytes-set!
  unsafe-car
  unsafe-cdr
  unsafe-fl/
  unsafe-flabs
  unsafe-flacos
  unsafe-flacosh
  unsafe-flasin
  unsafe-flasinh
  unsafe-flatan
  unsafe-flatanh
  unsafe-flceiling
  unsafe-flcos
  unsafe-flcosh
  unsafe-flexp
  unsafe-flexpt
  unsafe-flfloor
  unsafe-fllog
  unsafe-flmax
  unsafe-flmin
  unsafe-flrandom
  unsafe-flround
  unsafe-flsin
  unsafe-flsingle
  unsafe-flsinh
  unsafe-flsqrt
  unsafe-fltan
  unsafe-fltanh
  unsafe-fltruncate
  unsafe-fx*
  unsafe-fx*/wraparound
  unsafe-fx+
  unsafe-fx+/wraparound
  unsafe-fx-
  unsafe-fx-/wraparound
  unsafe-fx<
  unsafe-fx<=
  unsafe-fx=
  unsafe-fx>
  unsafe-fx>=
  unsafe-fxabs
  unsafe-fxand
  unsafe-fxior
  unsafe-fxlshift
  unsafe-fxlshift/wraparound
  unsafe-fxmax
  unsafe-fxmin
  unsafe-fxmodulo
  unsafe-fxnot
  unsafe-fxpopcount
  unsafe-fxpopcount16
  unsafe-fxpopcount32
  unsafe-fxquotient
  unsafe-fxremainder
  unsafe-fxrshift
  unsafe-fxrshift/logical
  unsafe-fxxor
  unsafe-string-length
  unsafe-struct-ref
  unsafe-struct-set!
  unsafe-vector*-length
  unsafe-vector*-ref
  unsafe-vector*-set!
  unsafe-vector-length
  unsafe-vector-ref
  unsafe-vector-set!
  values
  variable-reference-constant?
  variable-reference-from-unsafe?
  vector
  vector->immutable-vector
  vector->list
  vector->values
  vector-append
  vector-argmax
  vector-argmin
  vector-copy
  vector-copy!
  vector-count
  vector-drop
  vector-drop-right
  vector-empty?
  vector-extend
  vector-fill!
  vector-filter
  vector-filter-not
  vector-immutable
  vector-length
  vector-map
  vector-map!
  vector-member
  vector-memq
  vector-memv
  vector-ref
  vector-set!
  vector-set/copy
  vector-sort
  vector-sort!
  vector-split-at
  vector-split-at-right
  vector-take
  vector-take-right
  vector?
  void
  void?
  webracket-vfs-write-file
  with-input-from-file
  with-output-to-file
  write-byte
  write-bytes
  write-char
  write-string
  xor
  zero?
  (for-label (all-defined-out)))

(define * any/c)
(define + any/c)
(define - any/c)
(define ->fl any/c)
(define / any/c)
(define < any/c)
(define <= any/c)
(define = any/c)
(define > any/c)
(define >= any/c)
(define abs any/c)
(define acos any/c)
(define acosh any/c)
(define add-between any/c)
(define add1 any/c)
(define alt-reverse any/c)
(define andmap any/c)
(define append any/c)
(define append* any/c)
(define append-map any/c)
(define apply any/c)
(define argmax any/c)
(define argmin any/c)
(define arithmetic-shift any/c)
(define arity-at-least-value any/c)
(define arity-at-least? any/c)
(define asin any/c)
(define asinh any/c)
(define assf any/c)
(define assoc any/c)
(define assq any/c)
(define assv any/c)
(define assw any/c)
(define atan any/c)
(define atanh any/c)
(define bitwise-and any/c)
(define bitwise-bit-field any/c)
(define bitwise-bit-set? any/c)
(define bitwise-first-bit-set any/c)
(define bitwise-ior any/c)
(define bitwise-not any/c)
(define bitwise-xor any/c)
(define boolean=? any/c)
(define boolean? any/c)
(define box any/c)
(define box-immutable any/c)
(define box? any/c)
(define boxed any/c)
(define boxed? any/c)
(define build-list any/c)
(define build-string any/c)
(define build-vector any/c)
(define byte-ready? any/c)
(define byte? any/c)
(define bytes any/c)
(define bytes->immutable-bytes any/c)
(define bytes->list any/c)
(define bytes->path any/c)
(define bytes->string/latin-1 any/c)
(define bytes->string/utf-8 any/c)
(define bytes-append any/c)
(define bytes-append* any/c)
(define bytes-copy any/c)
(define bytes-copy! any/c)
(define bytes-fill! any/c)
(define bytes-join any/c)
(define bytes-length any/c)
(define bytes-ref any/c)
(define bytes-set! any/c)
(define bytes-utf-8-length any/c)
(define bytes<? any/c)
(define bytes=? any/c)
(define bytes>? any/c)
(define bytes? any/c)
(define caaaar any/c)
(define caaadr any/c)
(define caaar any/c)
(define caadar any/c)
(define caaddr any/c)
(define caadr any/c)
(define caar any/c)
(define cadaar any/c)
(define cadadr any/c)
(define cadar any/c)
(define caddar any/c)
(define cadddr any/c)
(define caddr any/c)
(define cadr any/c)
(define call-with-exception-handler any/c)
(define call-with-input-file any/c)
(define call-with-input-file* any/c)
(define call-with-output-file any/c)
(define call-with-output-file* any/c)
(define call-with-output-string any/c)
(define call-with-values any/c)
(define car any/c)
(define cartesian-product any/c)
(define catch any/c)
(define catch* any/c)
(define cdaaar any/c)
(define cdaadr any/c)
(define cdaar any/c)
(define cdadar any/c)
(define cdaddr any/c)
(define cdadr any/c)
(define cdar any/c)
(define cddaar any/c)
(define cddadr any/c)
(define cddar any/c)
(define cdddar any/c)
(define cddddr any/c)
(define cdddr any/c)
(define cddr any/c)
(define cdr any/c)
(define ceiling any/c)
(define char->integer any/c)
(define char-alphabetic? any/c)
(define char-blank? any/c)
(define char-ci<=? any/c)
(define char-ci<? any/c)
(define char-ci=? any/c)
(define char-ci>=? any/c)
(define char-ci>? any/c)
(define char-downcase any/c)
(define char-extended-pictographic? any/c)
(define char-foldcase any/c)
(define char-general-category any/c)
(define char-grapheme-break-property any/c)
(define char-grapheme-step any/c)
(define char-graphic? any/c)
(define char-iso-control? any/c)
(define char-lower-case? any/c)
(define char-numeric? any/c)
(define char-punctuation? any/c)
(define char-ready? any/c)
(define char-symbolic? any/c)
(define char-title-case? any/c)
(define char-titlecase any/c)
(define char-upcase any/c)
(define char-upper-case? any/c)
(define char-utf-8-length any/c)
(define char-whitespace? any/c)
(define char<=? any/c)
(define char<? any/c)
(define char=? any/c)
(define char>=? any/c)
(define char>? any/c)
(define char? any/c)
(define check-list any/c)
(define check-mlist any/c)
(define check-naturals any/c)
(define check-range any/c)
(define check-range-generic any/c)
(define check-string any/c)
(define cons any/c)
(define cons? any/c)
(define copy-file any/c)
(define copy-directory/files any/c)
(define correlated->datum any/c)
(define correlated-column any/c)
(define correlated-e any/c)
(define correlated-line any/c)
(define correlated-position any/c)
(define correlated-property any/c)
(define correlated-property-symbol-keys any/c)
(define correlated-source any/c)
(define correlated-span any/c)
(define correlated? any/c)
(define cos any/c)
(define cosh any/c)
(define count any/c)
(define current-continuation-marks any/c)
(define current-inspector any/c)
(define custom-write-accessor any/c)
(define custom-write? any/c)
(define datum->correlated any/c)
(define datum->syntax any/c)
(define degrees->radians any/c)
(define delete-directory any/c)
(define delete-directory/files any/c)
(define delete-file any/c)
(define directory-exists? any/c)
(define directory-list any/c)
(define display-lines-to-file any/c)
(define display-to-file any/c)
(define double-flonum? any/c)
(define drop any/c)
(define drop-common-prefix any/c)
(define drop-right any/c)
(define dropf any/c)
(define dropf-right any/c)
(define eighth any/c)
(define eleventh any/c)
(define empty? any/c)
(define eof-object? any/c)
(define eq-hash-code any/c)
(define eq? any/c)
(define equal-always? any/c)
(define equal-hash-code any/c)
(define equal? any/c)
(define eqv-hash-code any/c)
(define eqv? any/c)
(define even? any/c)
(define exact->inexact any/c)
(define exact-ceiling any/c)
(define exact-floor any/c)
(define exact-integer? any/c)
(define exact-nonnegative-integer? any/c)
(define exact-positive-integer? any/c)
(define exact-round any/c)
(define exact-truncate any/c)
(define exact? any/c)
(define exn any/c)
(define exn-continuation-marks any/c)
(define exn-message any/c)
(define exn:fail any/c)
(define exn:fail:contract any/c)
(define exn:fail:contract:arity any/c)
(define exn:fail:contract:arity? any/c)
(define exn:fail:contract:divide-by-zero any/c)
(define exn:fail:contract:divide-by-zero? any/c)
(define exn:fail:contract:non-fixnum-result any/c)
(define exn:fail:contract:non-fixnum-result? any/c)
(define exn:fail:contract:variable any/c)
(define exn:fail:contract:variable-id any/c)
(define exn:fail:contract:variable? any/c)
(define exn:fail:contract? any/c)
(define exn:fail:read any/c)
(define exn:fail:read-srclocs any/c)
(define exn:fail:read:eof any/c)
(define exn:fail:read:eof? any/c)
(define exn:fail:read:non-char any/c)
(define exn:fail:read:non-char? any/c)
(define exn:fail:read? any/c)
(define exn:fail:syntax any/c)
(define exn:fail:syntax-exprs any/c)
(define exn:fail:syntax:missing-module any/c)
(define exn:fail:syntax:missing-module-path any/c)
(define exn:fail:syntax:missing-module? any/c)
(define exn:fail:syntax:unbound any/c)
(define exn:fail:syntax:unbound? any/c)
(define exn:fail:syntax? any/c)
(define exn:fail? any/c)
(define exn? any/c)
(define exp any/c)
(define expt any/c)
(define external-number->flonum any/c)
(define external-string->string any/c)
(define external? any/c)
(define false? any/c)
(define fasl->s-exp any/c)
(define fifteenth any/c)
(define file->bytes any/c)
(define file->bytes-lines any/c)
(define file->lines any/c)
(define file->string any/c)
(define file-exists? any/c)
(define file-or-directory-identity any/c)
(define file-or-directory-modify-seconds any/c)
(define file-or-directory-permissions any/c)
(define file-or-directory-stat any/c)
(define file-or-directory-type any/c)
(define file-size any/c)
(define fifth any/c)
(define filter any/c)
(define filter-map any/c)
(define filter-not any/c)
(define findf any/c)
(define first any/c)
(define fixnum-for-every-system? any/c)
(define fixnum? any/c)
(define fl* any/c)
(define fl+ any/c)
(define fl- any/c)
(define fl->exact-integer any/c)
(define fl->fx any/c)
(define fl/ any/c)
(define fl< any/c)
(define fl<= any/c)
(define fl= any/c)
(define fl> any/c)
(define fl>= any/c)
(define flabs any/c)
(define flacos any/c)
(define flacosh any/c)
(define flasin any/c)
(define flasinh any/c)
(define flatan any/c)
(define flatanh any/c)
(define flatten any/c)
(define flbit-field any/c)
(define flceiling any/c)
(define flcos any/c)
(define flcosh any/c)
(define flexp any/c)
(define flexpt any/c)
(define flfloor any/c)
(define fllog any/c)
(define flmax any/c)
(define flmin any/c)
(define floating-point-bytes->real any/c)
(define flonum? any/c)
(define floor any/c)
(define flrandom any/c)
(define flround any/c)
(define flsin any/c)
(define flsingle any/c)
(define flsinh any/c)
(define flsqrt any/c)
(define fltan any/c)
(define fltanh any/c)
(define fltruncate any/c)
(define foldl any/c)
(define foldr any/c)
(define for-each any/c)
(define fourteenth any/c)
(define fourth any/c)
(define fx* any/c)
(define fx*/wraparound any/c)
(define fx+ any/c)
(define fx+/wraparound any/c)
(define fx- any/c)
(define fx-/wraparound any/c)
(define fx->fl any/c)
(define fx< any/c)
(define fx<= any/c)
(define fx= any/c)
(define fx> any/c)
(define fx>= any/c)
(define fxabs any/c)
(define fxand any/c)
(define fxior any/c)
(define fxlshift any/c)
(define fxlshift/wraparound any/c)
(define fxmax any/c)
(define fxmin any/c)
(define fxmodulo any/c)
(define fxnot any/c)
(define fxpopcount any/c)
(define fxpopcount16 any/c)
(define fxpopcount32 any/c)
(define fxquotient any/c)
(define fxremainder any/c)
(define fxrshift any/c)
(define fxrshift/logical any/c)
(define fxxor any/c)
(define fxzero? any/c)
(define gcd any/c)
(define gensym any/c)
(define get-output-bytes any/c)
(define get-output-string any/c)
(define group-by any/c)
(define hash->list any/c)
(define hash-clear! any/c)
(define hash-count any/c)
(define hash-empty? any/c)
(define hash-eq? any/c)
(define hash-equal-always? any/c)
(define hash-equal? any/c)
(define hash-eqv? any/c)
(define hash-filter any/c)
(define hash-filter-keys any/c)
(define hash-filter-values any/c)
(define hash-for-each any/c)
(define hash-has-key? any/c)
(define hash-keys any/c)
(define hash-map any/c)
(define hash-map/copy any/c)
(define hash-ref any/c)
(define hash-ref! any/c)
(define hash-remove! any/c)
(define hash-set! any/c)
(define hash-update! any/c)
(define hash-values any/c)
(define hash? any/c)
(define identifier? any/c)
(define immutable-box? any/c)
(define immutable-bytes? any/c)
(define immutable-hash? any/c)
(define immutable-string? any/c)
(define immutable-vector? any/c)
(define immutable? any/c)
(define inclusive-range any/c)
(define inclusive-range-proc any/c)
(define index-of any/c)
(define index-where any/c)
(define indexes-of any/c)
(define indexes-where any/c)
(define inexact->exact any/c)
(define inexact-real? any/c)
(define inexact? any/c)
(define infinite? any/c)
(define input-port? any/c)
(define instance-data any/c)
(define instance-name any/c)
(define instance-set-variable-value! any/c)
(define instance-unset-variable! any/c)
(define instance-variable-box any/c)
(define instance-variable-names any/c)
(define instance-variable-value any/c)
(define instance? any/c)
(define instantiate-linklet any/c)
(define integer->char any/c)
(define integer-length any/c)
(define integer-sqrt any/c)
(define integer-sqrt/remainder any/c)
(define integer? any/c)
(define js-log any/c)
(define keyword->immutable-string any/c)
(define keyword->string any/c)
(define keyword<? any/c)
(define keyword? any/c)
(define last any/c)
(define last-pair any/c)
(define lcm any/c)
(define length any/c)
(define linklet-export-variables any/c)
(define linklet-import-variables any/c)
(define linklet-name any/c)
(define linklet? any/c)
(define list any/c)
(define list* any/c)
(define list->bytes any/c)
(define list->string any/c)
(define list->vector any/c)
(define list-prefix? any/c)
(define list-ref any/c)
(define list-set any/c)
(define list-tail any/c)
(define list-update any/c)
(define list? any/c)
(define log any/c)
(define make-bytes any/c)
(define make-compiled-linklet any/c)
(define make-empty-hash any/c)
(define make-empty-hashalw any/c)
(define make-empty-hasheq any/c)
(define make-empty-hasheqv any/c)
(define make-empty-namespace any/c)
(define make-exn any/c)
(define make-exn:fail any/c)
(define make-exn:fail:contract any/c)
(define make-exn:fail:contract:arity any/c)
(define make-exn:fail:contract:divide-by-zero any/c)
(define make-exn:fail:contract:non-fixnum-result any/c)
(define make-exn:fail:contract:variable any/c)
(define make-exn:fail:read any/c)
(define make-exn:fail:read:eof any/c)
(define make-exn:fail:read:non-char any/c)
(define make-exn:fail:syntax any/c)
(define make-exn:fail:syntax:missing-module any/c)
(define make-exn:fail:syntax:unbound any/c)
(define make-hash any/c)
(define make-hashalw any/c)
(define make-hasheq any/c)
(define make-hasheqv any/c)
(define make-input-port any/c)
(define make-instance any/c)
(define make-list any/c)
(define make-directory any/c)
(define make-directory* any/c)
(define make-parent-directory* any/c)
(define make-temporary-directory any/c)
(define make-temporary-directory* any/c)
(define make-temporary-file any/c)
(define make-temporary-file* any/c)
(define make-srcloc any/c)
(define make-string any/c)
(define make-struct-field-accessor any/c)
(define make-struct-field-mutator any/c)
(define make-struct-type any/c)
(define make-struct-type-property any/c)
(define make-vector any/c)
(define make-void any/c)
(define make-weak-hash any/c)
(define make-weak-hashalw any/c)
(define make-weak-hasheq any/c)
(define make-weak-hasheqv any/c)
(define map any/c)
(define match:error any/c)
(define max any/c)
(define mcar any/c)
(define mcdr any/c)
(define mcons any/c)
(define member any/c)
(define memf any/c)
(define memq any/c)
(define memv any/c)
(define memw any/c)
(define min any/c)
(define modulo any/c)
(define most-negative-fixnum any/c)
(define most-positive-fixnum any/c)
(define mpair? any/c)
(define mutable-box? any/c)
(define mutable-bytes? any/c)
(define mutable-hash-iterate-first any/c)
(define mutable-hash-iterate-key any/c)
(define mutable-hash-iterate-key+value any/c)
(define mutable-hash-iterate-next any/c)
(define mutable-hash-iterate-pair any/c)
(define mutable-hash-iterate-value any/c)
(define mutable-hash? any/c)
(define mutable-string? any/c)
(define mutable-vector? any/c)
(define namespace-set-variable-value! any/c)
(define namespace-undefine-variable! any/c)
(define namespace-variable-value-simple any/c)
(define namespace? any/c)
(define nan? any/c)
(define natural? any/c)
(define negative-integer? any/c)
(define negative? any/c)
(define newline any/c)
(define ninth any/c)
(define non-empty-string? any/c)
(define nonnegative-integer? any/c)
(define nonpositive-integer? any/c)
(define not any/c)
(define null? any/c)
(define number->string any/c)
(define number? any/c)
(define object-name any/c)
(define odd? any/c)
(define open-input-bytes any/c)
(define open-input-file any/c)
(define open-input-string any/c)
(define open-output-bytes any/c)
(define open-output-file any/c)
(define open-output-string any/c)
(define order-of-magnitude any/c)
(define ormap any/c)
(define output-port? any/c)
(define pair? any/c)
(define partition any/c)
(define path->bytes any/c)
(define path->string any/c)
(define path-for-some-system? any/c)
(define path-string? any/c)
(define path? any/c)
(define peek-byte any/c)
(define peek-bytes any/c)
(define peek-bytes! any/c)
(define peek-bytes-avail! any/c)
(define peek-bytes-avail!* any/c)
(define peek-char any/c)
(define peek-string any/c)
(define peek-string! any/c)
(define permutations any/c)
(define port-count-lines! any/c)
(define port-counts-lines? any/c)
(define port-next-location any/c)
(define port? any/c)
(define positive-integer? any/c)
(define positive? any/c)
(define primitive-closure? any/c)
(define primitive-result-arity any/c)
(define primitive? any/c)
(define procedure->external any/c)
(define procedure-arity any/c)
(define procedure-arity-includes? any/c)
(define procedure-arity-mask any/c)
(define procedure-rename any/c)
(define procedure? any/c)
(define progress-evt? any/c)
(define quotient any/c)
(define quotient/remainder any/c)
(define radians->degrees any/c)
(define raise any/c)
(define raise-read-eof-error any/c)
(define raise-read-error any/c)
(define raise-unbound-variable-reference any/c)
(define random any/c)
(define range any/c)
(define range-proc any/c)
(define read-byte any/c)
(define read-bytes any/c)
(define read-bytes! any/c)
(define read-bytes-avail! any/c)
(define read-bytes-avail!* any/c)
(define read-char any/c)
(define read-line any/c)
(define read-string any/c)
(define read-string! any/c)
(define real->double-flonum any/c)
(define real->floating-point-bytes any/c)
(define real? any/c)
(define remainder any/c)
(define remf any/c)
(define remf* any/c)
(define remove any/c)
(define remove* any/c)
(define remq any/c)
(define remq* any/c)
(define remv any/c)
(define remv* any/c)
(define remw any/c)
(define remw* any/c)
(define rename-file-or-directory any/c)
(define rest any/c)
(define reverse any/c)
(define round any/c)
(define s-exp->fasl any/c)
(define second any/c)
(define set-box! any/c)
(define set-boxed! any/c)
(define set-mcar! any/c)
(define set-mcdr! any/c)
(define seventh any/c)
(define sgn any/c)
(define shuffle any/c)
(define sin any/c)
(define single-flonum-available? any/c)
(define single-flonum? any/c)
(define sinh any/c)
(define sixth any/c)
(define sort any/c)
(define split-at any/c)
(define split-at-right any/c)
(define split-common-prefix any/c)
(define splitf-at any/c)
(define splitf-at-right any/c)
(define sqr any/c)
(define sqrt any/c)
(define srcloc any/c)
(define srcloc->string any/c)
(define srcloc-column any/c)
(define srcloc-line any/c)
(define srcloc-position any/c)
(define srcloc-source any/c)
(define srcloc-span any/c)
(define srcloc? any/c)
(define string any/c)
(define string->bytes/utf-8 any/c)
(define string->immutable-string any/c)
(define string->keyword any/c)
(define string->list any/c)
(define string->number any/c)
(define string->symbol any/c)
(define string->uninterned-symbol any/c)
(define string-append any/c)
(define string-append* any/c)
(define string-append-immutable any/c)
(define string-ci<=? any/c)
(define string-ci<? any/c)
(define string-ci=? any/c)
(define string-ci>=? any/c)
(define string-ci>? any/c)
(define string-contains? any/c)
(define string-copy any/c)
(define string-copy! any/c)
(define string-downcase any/c)
(define string-drop any/c)
(define string-drop-right any/c)
(define string-fill! any/c)
(define string-find any/c)
(define string-foldcase any/c)
(define string-join any/c)
(define string-length any/c)
(define string-port? any/c)
(define string-prefix? any/c)
(define string-ref any/c)
(define string-replace any/c)
(define string-set! any/c)
(define string-split any/c)
(define string-suffix? any/c)
(define string-take any/c)
(define string-take-right any/c)
(define string-titlecase any/c)
(define string-trim any/c)
(define string-trim-left any/c)
(define string-trim-right any/c)
(define string-upcase any/c)
(define string-utf-8-length any/c)
(define string<=? any/c)
(define string<? any/c)
(define string=? any/c)
(define string>=? any/c)
(define string>? any/c)
(define string? any/c)
(define struct->list any/c)
(define struct->vector any/c)
(define struct-accessor-procedure? any/c)
(define struct-constructor-procedure? any/c)
(define struct-mutator-procedure? any/c)
(define struct-predicate-procedure? any/c)
(define struct-type-authentic? any/c)
(define struct-type-property-accessor-procedure? any/c)
(define struct-type-property-predicate-procedure? any/c)
(define struct-type-property? any/c)
(define struct-type? any/c)
(define struct? any/c)
(define sub1 any/c)
(define subbytes any/c)
(define substring any/c)
(define symbol->immutable-string any/c)
(define symbol->string any/c)
(define symbol-interned? any/c)
(define symbol<? any/c)
(define symbol=? any/c)
(define symbol? any/c)
(define syntax->datum any/c)
(define syntax->list any/c)
(define syntax-column any/c)
(define syntax-e any/c)
(define syntax-line any/c)
(define syntax-position any/c)
(define syntax-source any/c)
(define syntax-span any/c)
(define syntax-srcloc any/c)
(define syntax-srclocs any/c)
(define syntax? any/c)
(define system-big-endian? any/c)
(define take any/c)
(define take-common-prefix any/c)
(define take-right any/c)
(define takef any/c)
(define takef-right any/c)
(define tan any/c)
(define tanh any/c)
(define tenth any/c)
(define third any/c)
(define thirteenth any/c)
(define truncate any/c)
(define twelfth any/c)
(define unbox any/c)
(define unboxed any/c)
(define unquoted-printing-string any/c)
(define unquoted-printing-string-value any/c)
(define unquoted-printing-string? any/c)
(define unsafe-bytes-length any/c)
(define unsafe-bytes-ref any/c)
(define unsafe-bytes-set! any/c)
(define unsafe-car any/c)
(define unsafe-cdr any/c)
(define unsafe-fl/ any/c)
(define unsafe-flabs any/c)
(define unsafe-flacos any/c)
(define unsafe-flacosh any/c)
(define unsafe-flasin any/c)
(define unsafe-flasinh any/c)
(define unsafe-flatan any/c)
(define unsafe-flatanh any/c)
(define unsafe-flceiling any/c)
(define unsafe-flcos any/c)
(define unsafe-flcosh any/c)
(define unsafe-flexp any/c)
(define unsafe-flexpt any/c)
(define unsafe-flfloor any/c)
(define unsafe-fllog any/c)
(define unsafe-flmax any/c)
(define unsafe-flmin any/c)
(define unsafe-flrandom any/c)
(define unsafe-flround any/c)
(define unsafe-flsin any/c)
(define unsafe-flsingle any/c)
(define unsafe-flsinh any/c)
(define unsafe-flsqrt any/c)
(define unsafe-fltan any/c)
(define unsafe-fltanh any/c)
(define unsafe-fltruncate any/c)
(define unsafe-fx* any/c)
(define unsafe-fx*/wraparound any/c)
(define unsafe-fx+ any/c)
(define unsafe-fx+/wraparound any/c)
(define unsafe-fx- any/c)
(define unsafe-fx-/wraparound any/c)
(define unsafe-fx< any/c)
(define unsafe-fx<= any/c)
(define unsafe-fx= any/c)
(define unsafe-fx> any/c)
(define unsafe-fx>= any/c)
(define unsafe-fxabs any/c)
(define unsafe-fxand any/c)
(define unsafe-fxior any/c)
(define unsafe-fxlshift any/c)
(define unsafe-fxlshift/wraparound any/c)
(define unsafe-fxmax any/c)
(define unsafe-fxmin any/c)
(define unsafe-fxmodulo any/c)
(define unsafe-fxnot any/c)
(define unsafe-fxpopcount any/c)
(define unsafe-fxpopcount16 any/c)
(define unsafe-fxpopcount32 any/c)
(define unsafe-fxquotient any/c)
(define unsafe-fxremainder any/c)
(define unsafe-fxrshift any/c)
(define unsafe-fxrshift/logical any/c)
(define unsafe-fxxor any/c)
(define unsafe-string-length any/c)
(define unsafe-struct-ref any/c)
(define unsafe-struct-set! any/c)
(define unsafe-vector*-length any/c)
(define unsafe-vector*-ref any/c)
(define unsafe-vector*-set! any/c)
(define unsafe-vector-length any/c)
(define unsafe-vector-ref any/c)
(define unsafe-vector-set! any/c)
(define values any/c)
(define variable-reference-constant? any/c)
(define variable-reference-from-unsafe? any/c)
(define vector any/c)
(define vector->immutable-vector any/c)
(define vector->list any/c)
(define vector->values any/c)
(define vector-append any/c)
(define vector-argmax any/c)
(define vector-argmin any/c)
(define vector-copy any/c)
(define vector-copy! any/c)
(define vector-count any/c)
(define vector-drop any/c)
(define vector-drop-right any/c)
(define vector-empty? any/c)
(define vector-extend any/c)
(define vector-fill! any/c)
(define vector-filter any/c)
(define vector-filter-not any/c)
(define vector-immutable any/c)
(define vector-length any/c)
(define vector-map any/c)
(define vector-map! any/c)
(define vector-member any/c)
(define vector-memq any/c)
(define vector-memv any/c)
(define vector-ref any/c)
(define vector-set! any/c)
(define vector-set/copy any/c)
(define vector-sort any/c)
(define vector-sort! any/c)
(define vector-split-at any/c)
(define vector-split-at-right any/c)
(define vector-take any/c)
(define vector-take-right any/c)
(define vector? any/c)
(define void any/c)
(define void? any/c)
(define webracket-vfs-write-file any/c)
(define with-input-from-file any/c)
(define with-output-to-file any/c)
(define write-byte any/c)
(define write-bytes any/c)
(define write-char any/c)
(define write-string any/c)
(define xor any/c)
(define zero? any/c)
