#lang racket/base

(require racket/contract/base)

;; This module provides docs-only fake bindings for Scribble linking.
;; web-easy is written in #lang webracket, so its source bindings are not
;; available to Scribble as ordinary Racket for-label bindings.
;;
;; This file is generated by scribblings/generate-web-easy-labels.rkt.
;; To refresh it, run:
;;   racket scribblings/generate-web-easy-labels.rkt
;;
;; To make links resolve correctly in web-easy.scrbl:
;; 1. Require this module with for-label, and
;; 2. Use @declare-exporting with the exact same module path.
;;
;; If these paths differ, Scribble will render plain symbols or bad links.
(provide
  text-content/c
  html-element
  html-element-children
  P
  A
  Img
  Button
  Span
  Strong
  Em
  Code
  Pre
  Small
  B
  I
  U
  S
  Mark
  Sub
  Sup
  Kbd
  Samp
  Var
  Q
  Cite
  Dfn
  Abbr
  Time
  Data
  Del
  Ins
  Br
  Wbr
  Hr
  Div
  Section
  Article
  Nav
  Main
  Header
  Footer
  Aside
  Form
  Label
  Ul
  Menu
  Ol
  Li
  Dl
  Dt
  Dd
  Table
  Caption
  Thead
  Tbody
  Tfoot
  Tr
  Th
  Td
  Audio
  Video
  Source
  Track
  Canvas
  Iframe
  Embed
  Object
  Input
  Select
  Option
  Textarea
  Details
  Dialog
  Summary
  Figure
  Figcaption
  Hgroup
  Address
  Blockquote
  Ruby
  Rt
  Rp
  Bdi
  Bdo
  Progress
  Meter
  Output
  Fieldset
  Legend
  Datalist
  Optgroup
  Colgroup
  Col
  Map
  Area
  Script
  Link
  Meta
  Title
  Base
  Style
  Slot
  window
  vpanel
  hpanel
  container
  grid
  stack
  inline
  Fragment
  spacer
  divider
  group
  text
  heading
  h1
  h2
  h3
  h4
  h5
  h6
  display-heading
  display-1
  display-2
  display-3
  display-4
  display-5
  display-6
  heading-with-subtitle
  display-heading-with-subtitle
  lead
  blockquote
  image
  link
  button
  close-button
  button-group
  toggle-button-group
  button-toolbar
  toolbar
  toolbar-group
  input
  textarea
  checkbox
  radios
  choice
  slider
  pagination
  breadcrumb
  alert
  alert-rich
  toast
  badge
  spinner
  progress
  placeholder
  list-group
  tab-panel
  dropdown
  menu-bar
  menu
  menu-item
  navigation-bar
  top-bar
  table
  list-view
  card
  accordion
  carousel
  scrollspy
  dialog
  modal
  offcanvas
  tooltip
  popover
  observable-view
  if-view
  cond-view
  case-view
  collapse
  H1
  H2
  H3
  H4
  H5
  H6
  (for-label (all-defined-out)))

(define text-content/c any/c)
(define html-element any/c)
(define html-element-children any/c)
(define P any/c)
(define A any/c)
(define Img any/c)
(define Button any/c)
(define Span any/c)
(define Strong any/c)
(define Em any/c)
(define Code any/c)
(define Pre any/c)
(define Small any/c)
(define B any/c)
(define I any/c)
(define U any/c)
(define S any/c)
(define Mark any/c)
(define Sub any/c)
(define Sup any/c)
(define Kbd any/c)
(define Samp any/c)
(define Var any/c)
(define Q any/c)
(define Cite any/c)
(define Dfn any/c)
(define Abbr any/c)
(define Time any/c)
(define Data any/c)
(define Del any/c)
(define Ins any/c)
(define Br any/c)
(define Wbr any/c)
(define Hr any/c)
(define Div any/c)
(define Section any/c)
(define Article any/c)
(define Nav any/c)
(define Main any/c)
(define Header any/c)
(define Footer any/c)
(define Aside any/c)
(define Form any/c)
(define Label any/c)
(define Ul any/c)
(define Menu any/c)
(define Ol any/c)
(define Li any/c)
(define Dl any/c)
(define Dt any/c)
(define Dd any/c)
(define Table any/c)
(define Caption any/c)
(define Thead any/c)
(define Tbody any/c)
(define Tfoot any/c)
(define Tr any/c)
(define Th any/c)
(define Td any/c)
(define Audio any/c)
(define Video any/c)
(define Source any/c)
(define Track any/c)
(define Canvas any/c)
(define Iframe any/c)
(define Embed any/c)
(define Object any/c)
(define Input any/c)
(define Select any/c)
(define Option any/c)
(define Textarea any/c)
(define Details any/c)
(define Dialog any/c)
(define Summary any/c)
(define Figure any/c)
(define Figcaption any/c)
(define Hgroup any/c)
(define Address any/c)
(define Blockquote any/c)
(define Ruby any/c)
(define Rt any/c)
(define Rp any/c)
(define Bdi any/c)
(define Bdo any/c)
(define Progress any/c)
(define Meter any/c)
(define Output any/c)
(define Fieldset any/c)
(define Legend any/c)
(define Datalist any/c)
(define Optgroup any/c)
(define Colgroup any/c)
(define Col any/c)
(define Map any/c)
(define Area any/c)
(define Script any/c)
(define Link any/c)
(define Meta any/c)
(define Title any/c)
(define Base any/c)
(define Style any/c)
(define Slot any/c)
(define window any/c)
(define vpanel any/c)
(define hpanel any/c)
(define container any/c)
(define grid any/c)
(define stack any/c)
(define inline any/c)
(define Fragment any/c)
(define spacer any/c)
(define divider any/c)
(define group any/c)
(define text any/c)
(define heading any/c)
(define h1 any/c)
(define h2 any/c)
(define h3 any/c)
(define h4 any/c)
(define h5 any/c)
(define h6 any/c)
(define display-heading any/c)
(define display-1 any/c)
(define display-2 any/c)
(define display-3 any/c)
(define display-4 any/c)
(define display-5 any/c)
(define display-6 any/c)
(define heading-with-subtitle any/c)
(define display-heading-with-subtitle any/c)
(define lead any/c)
(define blockquote any/c)
(define image any/c)
(define link any/c)
(define button any/c)
(define close-button any/c)
(define button-group any/c)
(define toggle-button-group any/c)
(define button-toolbar any/c)
(define toolbar any/c)
(define toolbar-group any/c)
(define input any/c)
(define textarea any/c)
(define checkbox any/c)
(define radios any/c)
(define choice any/c)
(define slider any/c)
(define pagination any/c)
(define breadcrumb any/c)
(define alert any/c)
(define alert-rich any/c)
(define toast any/c)
(define badge any/c)
(define spinner any/c)
(define progress any/c)
(define placeholder any/c)
(define list-group any/c)
(define tab-panel any/c)
(define dropdown any/c)
(define menu-bar any/c)
(define menu any/c)
(define menu-item any/c)
(define navigation-bar any/c)
(define top-bar any/c)
(define table any/c)
(define list-view any/c)
(define card any/c)
(define accordion any/c)
(define carousel any/c)
(define scrollspy any/c)
(define dialog any/c)
(define modal any/c)
(define offcanvas any/c)
(define tooltip any/c)
(define popover any/c)
(define observable-view any/c)
(define if-view any/c)
(define cond-view any/c)
(define case-view any/c)
(define collapse any/c)
(define H1 any/c)
(define H2 any/c)
(define H3 any/c)
(define H4 any/c)
(define H5 any/c)
(define H6 any/c)
