;;;
;;; web-easy HTML Element Tests
;;;

;; Focused tests for primitive HTML element constructors generated by define/element.
;; These tests rely on helper procedures from test-web-easy-body.rkt.

;; Regression: primitive html-element constructors render their real tag on initial render
;; (not fallback div) for leaf and container primitives.
(define r-primitive-initial-tags
  (render
   (window
    (vpanel
     (H1 "Reg H1" #:id "reg-h1")
     (P "Reg P" #:id "reg-p")
     (Span "Reg Span" #:id "reg-span")
     (Img #:src "reg.png" #:alt "Reg Img" #:id "reg-img")
     (Div #:id "reg-div"
          (Span "Div child" #:id "reg-div-child"))))))
(define primitive-initial-tags-panel (node-child (renderer-root r-primitive-initial-tags) 0))
(define reg-h1-node (node-child primitive-initial-tags-panel 0))
(define reg-p-node (node-child primitive-initial-tags-panel 1))
(define reg-span-node (node-child primitive-initial-tags-panel 2))
(define reg-img-node (node-child primitive-initial-tags-panel 3))
(define reg-div-node (node-child primitive-initial-tags-panel 4))
(define reg-div-child-node (node-child reg-div-node 0))
(check-equal (dom-node-tag reg-h1-node) 'h1 "H1 initial primitive tag remains h1 (no div fallback)")
(check-equal (dom-node-tag reg-p-node) 'p "P initial primitive tag remains p (no div fallback)")
(check-equal (dom-node-tag reg-span-node) 'span "Span initial primitive tag remains span (no div fallback)")
(check-equal (dom-node-tag reg-img-node) 'img "Img initial primitive tag remains img (no div fallback)")
(check-equal (dom-node-tag reg-div-node) 'div "Div initial primitive tag remains div")
(check-equal (dom-node-tag reg-div-child-node) 'span "Div child primitive tag remains span")

;; H1 renders as a primitive h1 tag and accepts allowed attributes (including spec-listed align)
(define r-h1-basic
  (render
   (window
    (vpanel
     (H1 "Plain H1"
         #:align "left"
         #:id "hero-title")))))
(define h1-basic-panel (node-child (renderer-root r-h1-basic) 0))
(define h1-basic-node  (node-child h1-basic-panel 0))
(check-equal (dom-node-tag h1-basic-node) 'h1 "H1 primitive tag is h1")
(check-equal (dom-node-text h1-basic-node) "Plain H1" "H1 text content")
(check-equal (node-attr h1-basic-node 'align) "left" "H1 accepts allowed align attribute")
(check-equal (node-attr h1-basic-node 'id) "hero-title" "H1 accepts id as normal attribute")
(check-equal (node-attr h1-basic-node 'data-we-widget) #f "H1 does not use semantic heading widget marker")

;; H2..H6 render primitive heading tags and accept spec-listed align attribute
(define r-hx-basic
  (render
   (window
    (vpanel
     (H2 "H2" #:align "left")
     (H3 "H3" #:align "center")
     (H4 "H4" #:align "right")
     (H5 "H5" #:align "left")
     (H6 "H6" #:align "center")))))
(define hx-panel (node-child (renderer-root r-hx-basic) 0))
(define h2-node (node-child hx-panel 0))
(define h3-node (node-child hx-panel 1))
(define h4-node (node-child hx-panel 2))
(define h5-node (node-child hx-panel 3))
(define h6-node (node-child hx-panel 4))
(check-equal (dom-node-tag h2-node) 'h2 "H2 primitive tag is h2")
(check-equal (dom-node-tag h3-node) 'h3 "H3 primitive tag is h3")
(check-equal (dom-node-tag h4-node) 'h4 "H4 primitive tag is h4")
(check-equal (dom-node-tag h5-node) 'h5 "H5 primitive tag is h5")
(check-equal (dom-node-tag h6-node) 'h6 "H6 primitive tag is h6")
(check-equal (node-attr h2-node 'align) "left" "H2 accepts allowed align attribute")
(check-equal (node-attr h3-node 'align) "center" "H3 accepts allowed align attribute")
(check-equal (node-attr h4-node 'align) "right" "H4 accepts allowed align attribute")

;; H1 rejects unknown attributes early
(check-exn (lambda ()
             (H1 "Bad attr"
                 #:foo "bar"))
           "H1 rejects unknown keyword attribute")
(check-exn (lambda ()
             (H4 "Bad attr"
                 #:foo "bar"))
           "H4 rejects unknown keyword attribute")

;; H1 keeps class merge/dedupe behavior through root decorators
(define r-h1-class-merge
  (render
   (window
    (vpanel
     (H1 "Class merge"
         #:class '(alpha beta alpha)
         #:attrs '((class gamma) (class beta) (title "ok")))))))
(define h1-class-panel (node-child (renderer-root r-h1-class-merge) 0))
(define h1-class-node  (node-child h1-class-panel 0))
(define h1-class-value (node-attr h1-class-node 'class))
(check-equal (if (or (equal? h1-class-value "alpha beta gamma")
                     (equal? h1-class-value "alpha gamma beta")
                     (equal? h1-class-value "beta alpha gamma")
                     (equal? h1-class-value "beta gamma alpha")
                     (equal? h1-class-value "gamma alpha beta")
                     (equal? h1-class-value "gamma beta alpha"))
                 #t
                 #f)
             #t
             "H1 class values merge and dedupe across #:class and #:attrs")
(check-equal (node-attr h1-class-node 'title) "ok" "H1 preserves non-class attrs when merging classes")

;; H1 supports observable #:style and #:class values on primitive html-element rendering
(define @h1-style (@ "color: red;"))
(define @h1-class (@ "alpha"))
(define r-h1-reactive
  (render
   (window
    (vpanel
     (H1 "Reactive attrs"
         #:style @h1-style
         #:class @h1-class)))))
(define h1-reactive-panel (node-child (renderer-root r-h1-reactive) 0))
(define h1-reactive-node  (node-child h1-reactive-panel 0))
(check-equal (node-attr h1-reactive-node 'style) "color: red;" "H1 initial style from observable")
(check-equal (node-attr h1-reactive-node 'class) "alpha" "H1 initial class from observable")
(:= @h1-style "color: blue;")
(:= @h1-class '(alpha beta))
(check-equal (node-attr h1-reactive-node 'style) "color: blue;" "H1 style updates from observable")
(check-equal (node-attr h1-reactive-node 'class) "alpha beta" "H1 class updates from observable")

;; H1 supports reactive scalar attributes beyond style/class
(define @h1-title (@ "Draft"))
(define @h1-lang (@ "en"))
(define @h1-tabindex (@ 0))
(define @h1-hidden (@ #f))
(define r-h1-reactive-scalars
  (render
   (window
    (vpanel
     (H1 "Reactive scalar attrs"
         #:title @h1-title
         #:lang @h1-lang
         #:tabindex @h1-tabindex
         #:hidden @h1-hidden)))))
(define h1-reactive-scalars-panel (node-child (renderer-root r-h1-reactive-scalars) 0))
(define h1-reactive-scalars-node  (node-child h1-reactive-scalars-panel 0))
(check-equal (node-attr h1-reactive-scalars-node 'title) "Draft" "H1 initial title from observable")
(check-equal (node-attr h1-reactive-scalars-node 'lang) "en" "H1 initial lang from observable")
(check-equal (node-attr h1-reactive-scalars-node 'tabindex) 0 "H1 initial tabindex from observable")
(check-equal (node-attr h1-reactive-scalars-node 'hidden) #f "H1 initial hidden from observable")
(:= @h1-title "Published")
(:= @h1-lang "da")
(:= @h1-tabindex 2)
(:= @h1-hidden #t)
(check-equal (node-attr h1-reactive-scalars-node 'title) "Published" "H1 title updates from observable")
(check-equal (node-attr h1-reactive-scalars-node 'lang) "da" "H1 lang updates from observable")
(check-equal (node-attr h1-reactive-scalars-node 'tabindex) 2 "H1 tabindex updates from observable")
(check-equal (node-attr h1-reactive-scalars-node 'hidden) #t "H1 hidden updates from observable")

;; H1 rejects procedure-valued attributes (including via #:attrs escape hatch)
(check-exn (lambda ()
             (H1 "Bad title proc"
                 #:title (lambda () "x")))
           "H1 rejects procedure-valued keyword attrs")
(check-exn (lambda ()
             (H1 "Bad attrs proc"
                 #:attrs (list (list 'title (lambda () "x")))))
           "H1 rejects procedure-valued #:attrs entries")

;; H1 ignores procedure-valued observable attr updates (keeps last valid value)
(define @h1-safe-title (@ "initial"))
(define h1-warning-messages '())
(call-with-web-easy-warning-handler
 (lambda (msg)
   (set! h1-warning-messages
         (cons msg h1-warning-messages)))
 (lambda ()
   (define r-h1-safe-title
     (render
      (window
       (vpanel
        (H1 "Safe title"
            #:title @h1-safe-title)))))
   (define h1-safe-title-panel (node-child (renderer-root r-h1-safe-title) 0))
   (define h1-safe-title-node  (node-child h1-safe-title-panel 0))
   (check-equal (node-attr h1-safe-title-node 'title) "initial" "H1 safe title initial value")
   (:= @h1-safe-title "next")
   (check-equal (node-attr h1-safe-title-node 'title) "next" "H1 safe title valid observable update")
   (:= @h1-safe-title (lambda () "bad"))
   (check-equal (node-attr h1-safe-title-node 'title) "next" "H1 ignores procedure observable update and keeps last valid title")))
(check-equal (if (null? h1-warning-messages) #f #t)
             #t
             "H1 procedure observable update emits warning via warning handler")

;; H1 supports reactive data-* and aria-* attributes
(define @h1-data-testid (@ "hero-1"))
(define @h1-aria-label (@ "Primary title"))
(define r-h1-reactive-data-aria
  (render
   (window
    (vpanel
     (H1 "Reactive data/aria"
         #:data-testid @h1-data-testid
         #:aria-label @h1-aria-label)))))
(define h1-reactive-data-aria-panel (node-child (renderer-root r-h1-reactive-data-aria) 0))
(define h1-reactive-data-aria-node  (node-child h1-reactive-data-aria-panel 0))
(check-equal (node-attr h1-reactive-data-aria-node 'data-testid) "hero-1" "H1 initial data-* attr from observable")
(check-equal (node-attr h1-reactive-data-aria-node 'aria-label) "Primary title" "H1 initial aria-* attr from observable")
(:= @h1-data-testid "hero-2")
(:= @h1-aria-label "Secondary title")
(check-equal (node-attr h1-reactive-data-aria-node 'data-testid) "hero-2" "H1 data-* attr updates from observable")
(check-equal (node-attr h1-reactive-data-aria-node 'aria-label) "Secondary title" "H1 aria-* attr updates from observable")

;; H1 wildcard attribute matching requires proper `data-` / `aria-` prefixes
(check-exn (lambda ()
             (H1 "Bad wildcard data"
                 #:datatest "x"))
           "H1 rejects non-prefixed data wildcard lookalike")
(check-exn (lambda ()
             (H1 "Bad wildcard aria"
                 #:arialabel "x"))
           "H1 rejects non-prefixed aria wildcard lookalike")

;; define/element parsing edge cases (kept in this file for simplicity)
(define r-h1-keyword-order
  (render
   (window
    (vpanel
     (H1 #:id "ordered-id"
         "Keyword order ok")))))
(define h1-order-panel (node-child (renderer-root r-h1-keyword-order) 0))
(define h1-order-node  (node-child h1-order-panel 0))
(check-equal (dom-node-text h1-order-node) "Keyword order ok" "H1 supports positional content after keywords")
(check-equal (node-attr h1-order-node 'id) "ordered-id" "H1 supports keyword-before-positional order")

(define r-h1-attrs-false
  (render
   (window
    (vpanel
     (H1 "Attrs false"
         #:attrs #f
         #:title "from-keyword")))))
(define h1-attrs-false-panel (node-child (renderer-root r-h1-attrs-false) 0))
(define h1-attrs-false-node  (node-child h1-attrs-false-panel 0))
(check-equal (node-attr h1-attrs-false-node 'title) "from-keyword" "H1 allows #:attrs #f with keyword attrs")

(define r-h1-attrs-mixed
  (render
   (window
    (vpanel
     (H1 "Attrs mixed"
         #:attrs '((title "from-attrs"))
         #:lang "da")))))
(define h1-attrs-mixed-panel (node-child (renderer-root r-h1-attrs-mixed) 0))
(define h1-attrs-mixed-node  (node-child h1-attrs-mixed-panel 0))
(check-equal (node-attr h1-attrs-mixed-node 'title) "from-attrs" "H1 merges #:attrs and keyword attrs")
(check-equal (node-attr h1-attrs-mixed-node 'lang) "da" "H1 preserves keyword attrs when mixed with #:attrs")

(check-exn (lambda () (H1))
           "H1 rejects missing required positional content")
(check-exn (lambda () (H1 "a" "b"))
           "H1 rejects too many positional arguments")

;; P and Span render primitive tags and validate attributes
(define r-p-span-basic
  (render
   (window
    (vpanel
     (P "Paragraph"
        #:align "left"
        #:id "p1")
     (Span "Inline"
           #:title "tip"
           #:lang "en")))))
(define p-span-panel (node-child (renderer-root r-p-span-basic) 0))
(define p-node (node-child p-span-panel 0))
(define span-node (node-child p-span-panel 1))
(check-equal (dom-node-tag p-node) 'p "P primitive tag is p")
(check-equal (dom-node-tag span-node) 'span "Span primitive tag is span")
(check-equal (node-attr p-node 'align) "left" "P accepts spec-listed align attribute")
(check-equal (node-attr p-node 'id) "p1" "P accepts id attribute")
(check-equal (node-attr span-node 'title) "tip" "Span accepts title global attribute")
(check-equal (node-attr span-node 'lang) "en" "Span accepts lang global attribute")
(check-exn (lambda ()
             (P "Bad P attr"
                #:foo "x"))
           "P rejects unknown keyword attribute")
(check-exn (lambda ()
             (Span "Bad Span attr"
                   #:foo "x"))
           "Span rejects unknown keyword attribute")

;; P and Span support reactive scalar/data/aria attrs
(define @p-title (@ "p-a"))
(define @p-data (@ "p-1"))
(define @span-aria (@ "Inline label A"))
(define @span-tabindex (@ 0))
(define r-p-span-reactive
  (render
   (window
    (vpanel
     (P "P reactive"
        #:title @p-title
        #:data-testid @p-data)
     (Span "Span reactive"
           #:aria-label @span-aria
           #:tabindex @span-tabindex)))))
(define p-span-reactive-panel (node-child (renderer-root r-p-span-reactive) 0))
(define p-reactive-node    (node-child p-span-reactive-panel 0))
(define span-reactive-node (node-child p-span-reactive-panel 1))
(check-equal (node-attr p-reactive-node 'title) "p-a" "P initial title from observable")
(check-equal (node-attr p-reactive-node 'data-testid) "p-1" "P initial data-* from observable")
(check-equal (node-attr span-reactive-node 'aria-label) "Inline label A" "Span initial aria-* from observable")
(check-equal (node-attr span-reactive-node 'tabindex) 0 "Span initial tabindex from observable")
(:= @p-title "p-b")
(:= @p-data "p-2")
(:= @span-aria "Inline label B")
(:= @span-tabindex 3)
(check-equal (node-attr p-reactive-node 'title) "p-b" "P title updates from observable")
(check-equal (node-attr p-reactive-node 'data-testid) "p-2" "P data-* updates from observable")
(check-equal (node-attr span-reactive-node 'aria-label) "Inline label B" "Span aria-* updates from observable")
(check-equal (node-attr span-reactive-node 'tabindex) 3 "Span tabindex updates from observable")

;; P/Span wildcard boundary checks require proper data-/aria- prefix with hyphen
(check-exn (lambda ()
             (P "Bad p wildcard"
                #:datatest "x"))
           "P rejects non-prefixed data wildcard lookalike")
(check-exn (lambda ()
             (Span "Bad span wildcard"
                   #:arialabel "x"))
           "Span rejects non-prefixed aria wildcard lookalike")

;; Img requires #:src and supports validated/reactive attrs
(define r-img-basic
  (render
   (window
    (vpanel
     (Img #:src "avatar-a.png"
          #:alt "Avatar"
          #:data-testid "avatar-img")))))
(define img-basic-panel (node-child (renderer-root r-img-basic) 0))
(define img-basic-node  (node-child img-basic-panel 0))
(check-equal (dom-node-tag img-basic-node) 'img "Img primitive tag is img")
(check-equal (node-attr img-basic-node 'src) "avatar-a.png" "Img accepts required #:src")
(check-equal (node-attr img-basic-node 'alt) "Avatar" "Img accepts alt attribute")
(check-equal (node-attr img-basic-node 'data-testid) "avatar-img" "Img accepts data-* attributes")
(check-equal (dom-node-text img-basic-node) "" "Img uses empty leaf text payload")

(define @img-src-html (@ "avatar-b.png"))
(define r-img-reactive
  (render
   (window
    (vpanel
     (Img #:src @img-src-html
          #:alt "Reactive avatar")))))
(define img-reactive-panel (node-child (renderer-root r-img-reactive) 0))
(define img-reactive-node  (node-child img-reactive-panel 0))
(check-equal (node-attr img-reactive-node 'src) "avatar-b.png" "Img initial observable src")
(:= @img-src-html "avatar-c.png")
(check-equal (node-attr img-reactive-node 'src) "avatar-c.png" "Img updates src from observable")

(check-exn (lambda ()
             (Img))
           "Img requires #:src keyword")
(check-exn (lambda ()
             (Img #:src "a.png" #:src "b.png"))
           "Img rejects duplicate #:src keyword")
(check-exn (lambda ()
             (Img "a.png" #:src "b.png"))
           "Img rejects positional arguments; use #:src")
(check-exn (lambda ()
             (Img #:src "a.png" #:foo "x"))
           "Img rejects unknown keyword attributes")

;; A and Button render primitive tags and validate attributes
(define r-a-button-basic
  (render
   (window
    (vpanel
     (A "Open docs"
        #:href "/docs"
        #:target "_blank"
        #:id "docs-link")
     (Button "Save"
             #:type "button"
             #:disabled #f
             #:name "save-btn")))))
(define a-button-panel (node-child (renderer-root r-a-button-basic) 0))
(define a-node      (node-child a-button-panel 0))
(define button-node (node-child a-button-panel 1))
(check-equal (dom-node-tag a-node) 'a "A primitive tag is a")
(check-equal (dom-node-tag button-node) 'button "Button primitive tag is button")
(check-equal (node-attr a-node 'href) "/docs" "A accepts href")
(check-equal (node-attr a-node 'target) "_blank" "A accepts target")
(check-equal (node-attr button-node 'type) "button" "Button accepts type")
(check-equal (node-attr button-node 'disabled) #f "Button accepts disabled")
(check-exn (lambda ()
             (A "Bad A attr"
                #:foo "x"))
           "A rejects unknown keyword attribute")
(check-exn (lambda ()
             (Button "Bad Button attr"
                     #:foo "x"))
           "Button rejects unknown keyword attribute")

;; A and Button support reactive scalar/data/aria attrs
(define @a-href (@ "/start"))
(define @a-data (@ "a-1"))
(define @button-disabled (@ #f))
(define @button-aria (@ "Primary action"))
(define r-a-button-reactive
  (render
   (window
    (vpanel
     (A "Reactive A"
        #:href @a-href
        #:data-testid @a-data)
     (Button "Reactive Button"
             #:disabled @button-disabled
             #:aria-label @button-aria)))))
(define a-button-reactive-panel (node-child (renderer-root r-a-button-reactive) 0))
(define a-reactive-node      (node-child a-button-reactive-panel 0))
(define button-reactive-node (node-child a-button-reactive-panel 1))
(check-equal (node-attr a-reactive-node 'href) "/start" "A initial href from observable")
(check-equal (node-attr a-reactive-node 'data-testid) "a-1" "A initial data-* from observable")
(check-equal (node-attr button-reactive-node 'disabled) #f "Button initial disabled from observable")
(check-equal (node-attr button-reactive-node 'aria-label) "Primary action" "Button initial aria-* from observable")
(:= @a-href "/finish")
(:= @a-data "a-2")
(:= @button-disabled #t)
(:= @button-aria "Secondary action")
(check-equal (node-attr a-reactive-node 'href) "/finish" "A href updates from observable")
(check-equal (node-attr a-reactive-node 'data-testid) "a-2" "A data-* updates from observable")
(check-equal (node-attr button-reactive-node 'disabled) #t "Button disabled updates from observable")
(check-equal (node-attr button-reactive-node 'aria-label) "Secondary action" "Button aria-* updates from observable")

;; A/Button wildcard boundary checks require proper data-/aria- prefix
(check-exn (lambda ()
             (A "Bad A wildcard"
                #:datatest "x"))
           "A rejects non-prefixed data wildcard lookalike")
(check-exn (lambda ()
             (Button "Bad Button wildcard"
                     #:arialabel "x"))
           "Button rejects non-prefixed aria wildcard lookalike")

;; Div and Section are primitive uppercase elements with children
(define r-div-section
  (render
   (window
    (Div
     #:id "page-root"
     #:data-testid "page"
     (Section
      #:title "Main section"
      (H2 "Overview")
      (P "Paragraph in section"))))))
(define div-node (node-child (renderer-root r-div-section) 0))
(define section-node (node-child div-node 0))
(define section-h2-node (node-child section-node 0))
(define section-p-node  (node-child section-node 1))
(check-equal (dom-node-tag div-node) 'div "Div primitive tag is div")
(check-equal (node-attr div-node 'id) "page-root" "Div accepts global id")
(check-equal (node-attr div-node 'data-testid) "page" "Div accepts data-* attrs")
(check-equal (dom-node-tag section-node) 'section "Section primitive tag is section")
(check-equal (node-attr section-node 'title) "Main section" "Section accepts global attrs")
(check-equal (dom-node-tag section-h2-node) 'h2 "Section child H2 renders")
(check-equal (dom-node-text section-p-node) "Paragraph in section" "Section child P renders")
(check-exn (lambda ()
             (Div #:foo "x" (P "bad")))
           "Div rejects unknown attrs")
(check-exn (lambda ()
             (Section #:foo "x" (P "bad")))
           "Section rejects unknown attrs")

;; Article, Nav, and Main are uppercase primitives with children
(define r-article-nav-main
  (render
   (window
    (Main
     #:id "main-root"
     (Nav
      #:aria-label "Primary nav"
      (A "Home" #:href "/")
      (A "Docs" #:href "/docs"))
     (Article
      #:title "Post"
      #:data-testid "article-1"
      (H2 "Title")
      (P "Body"))))))
(define main-node (node-child (renderer-root r-article-nav-main) 0))
(define nav-node (node-child main-node 0))
(define article-node (node-child main-node 1))
(check-equal (dom-node-tag main-node) 'main "Main primitive tag is main")
(check-equal (node-attr main-node 'id) "main-root" "Main accepts global attrs")
(check-equal (dom-node-tag nav-node) 'nav "Nav primitive tag is nav")
(check-equal (node-attr nav-node 'aria-label) "Primary nav" "Nav accepts aria-* attrs")
(check-equal (dom-node-tag article-node) 'article "Article primitive tag is article")
(check-equal (node-attr article-node 'title) "Post" "Article accepts global attrs")
(check-equal (node-attr article-node 'data-testid) "article-1" "Article accepts data-* attrs")
(check-exn (lambda ()
             (Main #:foo "x" (P "bad")))
           "Main rejects unknown attrs")
(check-exn (lambda ()
             (Nav #:foo "x" (P "bad")))
           "Nav rejects unknown attrs")
(check-exn (lambda ()
             (Article #:foo "x" (P "bad")))
           "Article rejects unknown attrs")

;; Header, Footer, and Aside are uppercase primitives with children
(define r-header-footer-aside
  (render
   (window
    (Header
     #:id "site-header"
     (H2 "Site title")
     (Aside
      #:title "Sidebar"
      (P "Links"))
     (Footer
      #:data-testid "site-footer"
      (Span "Footer text"))))))
(define header-node (node-child (renderer-root r-header-footer-aside) 0))
(define header-h2-node (node-child header-node 0))
(define aside-node (node-child header-node 1))
(define footer-node (node-child header-node 2))
(check-equal (dom-node-tag header-node) 'header "Header primitive tag is header")
(check-equal (node-attr header-node 'id) "site-header" "Header accepts global attrs")
(check-equal (dom-node-tag header-h2-node) 'h2 "Header child renders")
(check-equal (dom-node-tag aside-node) 'aside "Aside primitive tag is aside")
(check-equal (node-attr aside-node 'title) "Sidebar" "Aside accepts global attrs")
(check-equal (dom-node-tag footer-node) 'footer "Footer primitive tag is footer")
(check-equal (node-attr footer-node 'data-testid) "site-footer" "Footer accepts data-* attrs")
(check-exn (lambda ()
             (Header #:foo "x" (P "bad")))
           "Header rejects unknown attrs")
(check-exn (lambda ()
             (Footer #:foo "x" (P "bad")))
           "Footer rejects unknown attrs")
(check-exn (lambda ()
             (Aside #:foo "x" (P "bad")))
           "Aside rejects unknown attrs")

;; Form and Label primitives
(define @form-action (@ "/submit"))
(define @label-text (@ "Name"))
(define r-form-label
  (render
   (window
    (Form
     #:action @form-action
     #:method "post"
     (Label @label-text
            #:for "name-input"
            #:aria-label "Name label")
     (P "Body")))))
(define form-node (node-child (renderer-root r-form-label) 0))
(define form-label-node (node-child form-node 0))
(check-equal (dom-node-tag form-node) 'form "Form primitive tag is form")
(check-equal (node-attr form-node 'action) "/submit" "Form supports reactive action")
(check-equal (node-attr form-node 'method) "post" "Form accepts method")
(check-equal (dom-node-tag form-label-node) 'label "Label primitive tag is label")
(check-equal (dom-node-text form-label-node) "Name" "Label content supports observables")
(check-equal (node-attr form-label-node 'for) "name-input" "Label accepts #:for")
(check-equal (node-attr form-label-node 'aria-label) "Name label" "Label accepts aria-* attrs")
(:= @form-action "/save")
(:= @label-text "Full name")
(check-equal (node-attr form-node 'action) "/save" "Form updates reactive action")
(check-equal (dom-node-text form-label-node) "Full name" "Label updates reactive text")
(check-exn (lambda ()
             (Form #:foo "x" (P "bad")))
           "Form rejects unknown attrs")
(check-exn (lambda ()
             (Label "x" #:foo "x"))
           "Label rejects unknown attrs")

;; Ul, Ol, and Li are uppercase primitives with children
(define r-lists
  (render
   (window
    (vpanel
     (Ul
      #:type "disc"
      (Li (Span "One"))
      (Li (Span "Two")))
     (Ol
      #:start 3
      #:reversed #t
      (Li (Span "Third"))
      (Li (Span "Second")))))))
(define lists-panel (node-child (renderer-root r-lists) 0))
(define ul-node (node-child lists-panel 0))
(define ol-node (node-child lists-panel 1))
(define ul-li1 (node-child ul-node 0))
(define ul-li2 (node-child ul-node 1))
(define ol-li1 (node-child ol-node 0))
(check-equal (dom-node-tag ul-node) 'ul "Ul primitive tag is ul")
(check-equal (node-attr ul-node 'type) "disc" "Ul accepts type attr")
(check-equal (dom-node-tag ul-li1) 'li "Ul child Li renders")
(check-equal (dom-node-text (node-child ul-li2 0)) "Two" "Ul second Li child text renders")
(check-equal (dom-node-tag ol-node) 'ol "Ol primitive tag is ol")
(check-equal (node-attr ol-node 'start) 3 "Ol accepts start attr")
(check-equal (node-attr ol-node 'reversed) #t "Ol accepts reversed attr")
(check-equal (dom-node-tag ol-li1) 'li "Ol child Li renders")
(check-exn (lambda ()
             (Ul #:foo "x" (Li (Span "bad"))))
           "Ul rejects unknown attrs")
(check-exn (lambda ()
             (Ol #:foo "x" (Li (Span "bad"))))
           "Ol rejects unknown attrs")
(check-exn (lambda ()
             (Li #:foo "x" (Span "bad")))
           "Li rejects unknown attrs")
