;;;
;;; Web Pict Entry
;;;

;; Shared export boundary for the public `web-pict` library surface.

(define-values (rgb-color
                rgb-color?
                rgb-color-r
                rgb-color-g
                rgb-color-b
                rgb-color-a
                color
                color?
                color-value
                make-rgb-color
                make-color
                color->string
                font
                font?
                font-family
                font-size
                font-style
                font-variant
                font-weight
                font-line-height
                make-font
                font-family?
                font-family->string
                font-size?
                font-size->string
                font-style?
                font-style->string
                font-variant?
                font-variant->string
                font-weight?
                font-weight->string
                line-height?
                line-height->string
                font->string
                canvas-context->dc
                pict
                pict?
                pict-draw
                pict-width
                pict-height
                pict-ascent
                pict-descent
                pict-children
                pict-panbox
                pict-last
                make-pict
                set-pict-children!
                set-pict-panbox!
                set-pict-last!
                child
                child?
                child-pict
                child-dx
                child-dy
                child-sx
                child-sy
                child-sxy
                child-syx
                make-child
                draw-pict
                make-pict-drawer
                blank
                drop-below-ascent
                lift-above-baseline
                baseless
                record
                extend-pict
                ghost
                clip-descent
                clip-ascent
                inset
                black-and-white
                colorize
                thickness
                hline
                vline
                dash-hline
                dash-vline
                dash-frame
                frame
                pict-convertible?
                pict-convert
                pict-path?
                find-lt
                find-lc
                find-lb
                find-ltl
                find-lbl
                find-ct
                find-cc
                find-cb
                find-ctl
                find-cbl
                find-rt
                find-rc
                find-rb
                find-rtl
                find-rbl
                lt-find
                lc-find
                lb-find
                ltl-find
                lbl-find
                ct-find
                cc-find
                cb-find
                ctl-find
                cbl-find
                rt-find
                rc-find
                rb-find
                rtl-find
                rbl-find
                refocus
                panorama
                launder
                use-last*
                last*
                use-last
                oval
                oval/radius
                vl-append
                vc-append
                vr-append
                ht-append
                hc-append
                hb-append
                htl-append
                hbl-append
                lt-superimpose
                lb-superimpose
                lc-superimpose
                ltl-superimpose
                lbl-superimpose
                rt-superimpose
                rb-superimpose
                rc-superimpose
                rtl-superimpose
                rbl-superimpose
                ct-superimpose
                cb-superimpose
                cc-superimpose
                ctl-superimpose
                cbl-superimpose
                picture*
                picture
                cons-picture
                cons-picture*
                place-over
                place-under
                pin-over
                pin-under
                dc
                circle
                ellipse
                filled-ellipse
                disk
                rectangle
                filled-rectangle
                rounded-rectangle
                filled-rounded-rectangle
                bitmap
                standard-fish
                scale-to-fit
                scale
                flip-x
                flip-y
                translate
                shear
                rotate
                cellophane
                linewidth
                linestyle
                clip
                hyperlinkize
                freeze
                fade-pict
                fail-gracefully
                slide-pict
                slide-pict/center
                fade-around-pict
                sequence-animations
                reverse-animations
                fast-start
                fast-end
                fast-edges
                fast-middle
                split-phase
                table
                connect
                ~connect
                explain
                explain-child
                inset/clip
                single-pict
                prog-picture
                text
                color-frame
                color-round-frame
                color-dash-frame
                round-frame
                pict->bitmap
                bitmap-ref
                load-bitmap)
  (let ()
    (include "support.rkt")
    (include "core.rkt")
    (include "bitmap.rkt")
    (values rgb-color
            rgb-color?
            rgb-color-r
            rgb-color-g
            rgb-color-b
            rgb-color-a
            color
            color?
            color-value
            make-rgb-color
            make-color
            color->string
            font
            font?
            font-family
            font-size
            font-style
            font-variant
            font-weight
            font-line-height
            make-font
            font-family?
            font-family->string
            font-size?
            font-size->string
            font-style?
            font-style->string
            font-variant?
            font-variant->string
            font-weight?
            font-weight->string
            line-height?
            line-height->string
            font->string
            canvas-context->dc
            pict
            pict?
            pict-draw
            pict-width
            pict-height
            pict-ascent
            pict-descent
            pict-children
            pict-panbox
            pict-last
            make-pict
            set-pict-children!
            set-pict-panbox!
            set-pict-last!
            child
            child?
            child-pict
            child-dx
            child-dy
            child-sx
            child-sy
            child-sxy
            child-syx
            make-child
            draw-pict
            make-pict-drawer
            blank
            drop-below-ascent
            lift-above-baseline
            baseless
            record
            extend-pict
            ghost
            clip-descent
            clip-ascent
            inset
            black-and-white
            colorize
            thickness
            hline
            vline
            dash-hline
            dash-vline
            dash-frame
            frame
            pict-convertible?
            pict-convert
            pict-path?
            find-lt
            find-lc
            find-lb
            find-ltl
            find-lbl
            find-ct
            find-cc
            find-cb
            find-ctl
            find-cbl
            find-rt
            find-rc
            find-rb
            find-rtl
            find-rbl
            lt-find
            lc-find
            lb-find
            ltl-find
            lbl-find
            ct-find
            cc-find
            cb-find
            ctl-find
            cbl-find
            rt-find
            rc-find
            rb-find
            rtl-find
            rbl-find
            refocus
            panorama
            launder
            use-last*
            last*
            use-last
            oval
            oval/radius
            vl-append
            vc-append
            vr-append
            ht-append
            hc-append
            hb-append
            htl-append
            hbl-append
            lt-superimpose
            lb-superimpose
            lc-superimpose
            ltl-superimpose
            lbl-superimpose
            rt-superimpose
            rb-superimpose
            rc-superimpose
            rtl-superimpose
            rbl-superimpose
            ct-superimpose
            cb-superimpose
            cc-superimpose
            ctl-superimpose
            cbl-superimpose
            picture*
            picture
            cons-picture
            cons-picture*
            place-over
            place-under
            pin-over
            pin-under
            dc
            circle
            ellipse
            filled-ellipse
            disk
            rectangle
            filled-rectangle
            rounded-rectangle
            filled-rounded-rectangle
            bitmap
            standard-fish
            scale-to-fit
            scale
            flip-x
            flip-y
            translate
            shear
            rotate
            cellophane
            linewidth
            linestyle
            clip
            hyperlinkize
            freeze
            fade-pict
            fail-gracefully
            slide-pict
            slide-pict/center
            fade-around-pict
            sequence-animations
            reverse-animations
            fast-start
            fast-end
            fast-edges
            fast-middle
            split-phase
            table
            connect
            ~connect
            explain
            explain-child
            inset/clip
            single-pict
            prog-picture
            text
            color-frame
            color-round-frame
            color-dash-frame
            round-frame
            pict->bitmap
            bitmap-ref
            load-bitmap)))
